/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AdminVendorDocument
 */
export interface AdminVendorDocument {
	/**
	 *
	 * @type {string}
	 * @memberof AdminVendorDocument
	 */
	type?: string;
	/**
	 *
	 * @type {string}
	 * @memberof AdminVendorDocument
	 */
	url?: string;
}

/**
 * Check if a given object implements the AdminVendorDocument interface.
 */
export function instanceOfAdminVendorDocument(value: object): value is AdminVendorDocument {
	return true;
}

export function AdminVendorDocumentFromJSON(json: any): AdminVendorDocument {
	return AdminVendorDocumentFromJSONTyped(json, false);
}

export function AdminVendorDocumentFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): AdminVendorDocument {
	if (json == null) {
		return json;
	}
	return {
		type: json["type"] == null ? undefined : json["type"],
		url: json["url"] == null ? undefined : json["url"]
	};
}

export function AdminVendorDocumentToJSON(json: any): AdminVendorDocument {
	return AdminVendorDocumentToJSONTyped(json, false);
}

export function AdminVendorDocumentToJSONTyped(
	value?: AdminVendorDocument | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		type: value["type"],
		url: value["url"]
	};
}
