/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { AdminAdminUserResponse } from "./AdminAdminUserResponse";
import {
	AdminAdminUserResponseFromJSON,
	AdminAdminUserResponseFromJSONTyped,
	AdminAdminUserResponseToJSON,
	AdminAdminUserResponseToJSONTyped
} from "./AdminAdminUserResponse";

/**
 *
 * @export
 * @interface AdminListUsersResponse
 */
export interface AdminListUsersResponse {
	/**
	 *
	 * @type {number}
	 * @memberof AdminListUsersResponse
	 */
	limit?: number;
	/**
	 *
	 * @type {number}
	 * @memberof AdminListUsersResponse
	 */
	page?: number;
	/**
	 *
	 * @type {number}
	 * @memberof AdminListUsersResponse
	 */
	total?: number;
	/**
	 *
	 * @type {Array<AdminAdminUserResponse>}
	 * @memberof AdminListUsersResponse
	 */
	users?: Array<AdminAdminUserResponse>;
}

/**
 * Check if a given object implements the AdminListUsersResponse interface.
 */
export function instanceOfAdminListUsersResponse(value: object): value is AdminListUsersResponse {
	return true;
}

export function AdminListUsersResponseFromJSON(json: any): AdminListUsersResponse {
	return AdminListUsersResponseFromJSONTyped(json, false);
}

export function AdminListUsersResponseFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): AdminListUsersResponse {
	if (json == null) {
		return json;
	}
	return {
		limit: json["limit"] == null ? undefined : json["limit"],
		page: json["page"] == null ? undefined : json["page"],
		total: json["total"] == null ? undefined : json["total"],
		users:
			json["users"] == null
				? undefined
				: (json["users"] as Array<any>).map(AdminAdminUserResponseFromJSON)
	};
}

export function AdminListUsersResponseToJSON(json: any): AdminListUsersResponse {
	return AdminListUsersResponseToJSONTyped(json, false);
}

export function AdminListUsersResponseToJSONTyped(
	value?: AdminListUsersResponse | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		limit: value["limit"],
		page: value["page"],
		total: value["total"],
		users:
			value["users"] == null
				? undefined
				: (value["users"] as Array<any>).map(AdminAdminUserResponseToJSON)
	};
}
