/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { AdminCategoryResponse } from "./AdminCategoryResponse";
import {
	AdminCategoryResponseFromJSON,
	AdminCategoryResponseFromJSONTyped,
	AdminCategoryResponseToJSON,
	AdminCategoryResponseToJSONTyped
} from "./AdminCategoryResponse";

/**
 *
 * @export
 * @interface AdminCategoryListResponse
 */
export interface AdminCategoryListResponse {
	/**
	 *
	 * @type {Array<AdminCategoryResponse>}
	 * @memberof AdminCategoryListResponse
	 */
	categories?: Array<AdminCategoryResponse>;
	/**
	 *
	 * @type {boolean}
	 * @memberof AdminCategoryListResponse
	 */
	hasMore?: boolean;
	/**
	 *
	 * @type {number}
	 * @memberof AdminCategoryListResponse
	 */
	limit?: number;
	/**
	 *
	 * @type {number}
	 * @memberof AdminCategoryListResponse
	 */
	page?: number;
	/**
	 *
	 * @type {number}
	 * @memberof AdminCategoryListResponse
	 */
	total?: number;
}

/**
 * Check if a given object implements the AdminCategoryListResponse interface.
 */
export function instanceOfAdminCategoryListResponse(
	value: object
): value is AdminCategoryListResponse {
	return true;
}

export function AdminCategoryListResponseFromJSON(json: any): AdminCategoryListResponse {
	return AdminCategoryListResponseFromJSONTyped(json, false);
}

export function AdminCategoryListResponseFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): AdminCategoryListResponse {
	if (json == null) {
		return json;
	}
	return {
		categories:
			json["categories"] == null
				? undefined
				: (json["categories"] as Array<any>).map(AdminCategoryResponseFromJSON),
		hasMore: json["has_more"] == null ? undefined : json["has_more"],
		limit: json["limit"] == null ? undefined : json["limit"],
		page: json["page"] == null ? undefined : json["page"],
		total: json["total"] == null ? undefined : json["total"]
	};
}

export function AdminCategoryListResponseToJSON(json: any): AdminCategoryListResponse {
	return AdminCategoryListResponseToJSONTyped(json, false);
}

export function AdminCategoryListResponseToJSONTyped(
	value?: AdminCategoryListResponse | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		categories:
			value["categories"] == null
				? undefined
				: (value["categories"] as Array<any>).map(AdminCategoryResponseToJSON),
		has_more: value["hasMore"],
		limit: value["limit"],
		page: value["page"],
		total: value["total"]
	};
}
