/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { AdminCourierDocument } from "./AdminCourierDocument";
import {
	AdminCourierDocumentFromJSON,
	AdminCourierDocumentFromJSONTyped,
	AdminCourierDocumentToJSON,
	AdminCourierDocumentToJSONTyped
} from "./AdminCourierDocument";
import type { AdminVehicleTypeResponse } from "./AdminVehicleTypeResponse";
import {
	AdminVehicleTypeResponseFromJSON,
	AdminVehicleTypeResponseFromJSONTyped,
	AdminVehicleTypeResponseToJSON,
	AdminVehicleTypeResponseToJSONTyped
} from "./AdminVehicleTypeResponse";
import type { CourierprofileStatus } from "./CourierprofileStatus";
import {
	CourierprofileStatusFromJSON,
	CourierprofileStatusFromJSONTyped,
	CourierprofileStatusToJSON,
	CourierprofileStatusToJSONTyped
} from "./CourierprofileStatus";

/**
 *
 * @export
 * @interface AdminAdminCourierResponse
 */
export interface AdminAdminCourierResponse {
	/**
	 *
	 * @type {string}
	 * @memberof AdminAdminCourierResponse
	 */
	createdAt?: string;
	/**
	 *
	 * @type {Array<AdminCourierDocument>}
	 * @memberof AdminAdminCourierResponse
	 */
	documents?: Array<AdminCourierDocument>;
	/**
	 *
	 * @type {string}
	 * @memberof AdminAdminCourierResponse
	 */
	email?: string;
	/**
	 *
	 * @type {boolean}
	 * @memberof AdminAdminCourierResponse
	 */
	emailVerified?: boolean;
	/**
	 *
	 * @type {string}
	 * @memberof AdminAdminCourierResponse
	 */
	firstName?: string;
	/**
	 *
	 * @type {string}
	 * @memberof AdminAdminCourierResponse
	 */
	id?: string;
	/**
	 *
	 * @type {string}
	 * @memberof AdminAdminCourierResponse
	 */
	lastLogin?: string;
	/**
	 *
	 * @type {string}
	 * @memberof AdminAdminCourierResponse
	 */
	lastName?: string;
	/**
	 *
	 * @type {string}
	 * @memberof AdminAdminCourierResponse
	 */
	phone?: string;
	/**
	 *
	 * @type {boolean}
	 * @memberof AdminAdminCourierResponse
	 */
	phoneVerified?: boolean;
	/**
	 *
	 * @type {CourierprofileStatus}
	 * @memberof AdminAdminCourierResponse
	 */
	status?: CourierprofileStatus;
	/**
	 *
	 * @type {string}
	 * @memberof AdminAdminCourierResponse
	 */
	stripeAccountId?: string;
	/**
	 *
	 * @type {boolean}
	 * @memberof AdminAdminCourierResponse
	 */
	stripeActive?: boolean;
	/**
	 *
	 * @type {string}
	 * @memberof AdminAdminCourierResponse
	 */
	updatedAt?: string;
	/**
	 *
	 * @type {AdminVehicleTypeResponse}
	 * @memberof AdminAdminCourierResponse
	 */
	vehicleType?: AdminVehicleTypeResponse;
}

/**
 * Check if a given object implements the AdminAdminCourierResponse interface.
 */
export function instanceOfAdminAdminCourierResponse(
	value: object
): value is AdminAdminCourierResponse {
	return true;
}

export function AdminAdminCourierResponseFromJSON(json: any): AdminAdminCourierResponse {
	return AdminAdminCourierResponseFromJSONTyped(json, false);
}

export function AdminAdminCourierResponseFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): AdminAdminCourierResponse {
	if (json == null) {
		return json;
	}
	return {
		createdAt: json["created_at"] == null ? undefined : json["created_at"],
		documents:
			json["documents"] == null
				? undefined
				: (json["documents"] as Array<any>).map(AdminCourierDocumentFromJSON),
		email: json["email"] == null ? undefined : json["email"],
		emailVerified: json["email_verified"] == null ? undefined : json["email_verified"],
		firstName: json["first_name"] == null ? undefined : json["first_name"],
		id: json["id"] == null ? undefined : json["id"],
		lastLogin: json["last_login"] == null ? undefined : json["last_login"],
		lastName: json["last_name"] == null ? undefined : json["last_name"],
		phone: json["phone"] == null ? undefined : json["phone"],
		phoneVerified: json["phone_verified"] == null ? undefined : json["phone_verified"],
		status: json["status"] == null ? undefined : CourierprofileStatusFromJSON(json["status"]),
		stripeAccountId: json["stripe_account_id"] == null ? undefined : json["stripe_account_id"],
		stripeActive: json["stripe_active"] == null ? undefined : json["stripe_active"],
		updatedAt: json["updated_at"] == null ? undefined : json["updated_at"],
		vehicleType:
			json["vehicle_type"] == null
				? undefined
				: AdminVehicleTypeResponseFromJSON(json["vehicle_type"])
	};
}

export function AdminAdminCourierResponseToJSON(json: any): AdminAdminCourierResponse {
	return AdminAdminCourierResponseToJSONTyped(json, false);
}

export function AdminAdminCourierResponseToJSONTyped(
	value?: AdminAdminCourierResponse | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		created_at: value["createdAt"],
		documents:
			value["documents"] == null
				? undefined
				: (value["documents"] as Array<any>).map(AdminCourierDocumentToJSON),
		email: value["email"],
		email_verified: value["emailVerified"],
		first_name: value["firstName"],
		id: value["id"],
		last_login: value["lastLogin"],
		last_name: value["lastName"],
		phone: value["phone"],
		phone_verified: value["phoneVerified"],
		status: CourierprofileStatusToJSON(value["status"]),
		stripe_account_id: value["stripeAccountId"],
		stripe_active: value["stripeActive"],
		updated_at: value["updatedAt"],
		vehicle_type: AdminVehicleTypeResponseToJSON(value["vehicleType"])
	};
}
