/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AdminCreateCategoryRequest
 */
export interface AdminCreateCategoryRequest {
	/**
	 *
	 * @type {string}
	 * @memberof AdminCreateCategoryRequest
	 */
	name: string;
}

/**
 * Check if a given object implements the AdminCreateCategoryRequest interface.
 */
export function instanceOfAdminCreateCategoryRequest(
	value: object
): value is AdminCreateCategoryRequest {
	if (!("name" in value) || value["name"] === undefined) return false;
	return true;
}

export function AdminCreateCategoryRequestFromJSON(json: any): AdminCreateCategoryRequest {
	return AdminCreateCategoryRequestFromJSONTyped(json, false);
}

export function AdminCreateCategoryRequestFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): AdminCreateCategoryRequest {
	if (json == null) {
		return json;
	}
	return {
		name: json["name"]
	};
}

export function AdminCreateCategoryRequestToJSON(json: any): AdminCreateCategoryRequest {
	return AdminCreateCategoryRequestToJSONTyped(json, false);
}

export function AdminCreateCategoryRequestToJSONTyped(
	value?: AdminCreateCategoryRequest | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		name: value["name"]
	};
}
