/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { SchemaRole } from "./SchemaRole";
import {
	SchemaRoleFromJSON,
	SchemaRoleFromJSONTyped,
	SchemaRoleToJSON,
	SchemaRoleToJSONTyped
} from "./SchemaRole";
import type { UserStatus } from "./UserStatus";
import {
	UserStatusFromJSON,
	UserStatusFromJSONTyped,
	UserStatusToJSON,
	UserStatusToJSONTyped
} from "./UserStatus";

/**
 *
 * @export
 * @interface AdminUpdateUserRequest
 */
export interface AdminUpdateUserRequest {
	/**
	 *
	 * @type {boolean}
	 * @memberof AdminUpdateUserRequest
	 */
	emailVerified?: boolean;
	/**
	 *
	 * @type {string}
	 * @memberof AdminUpdateUserRequest
	 */
	firstName?: string;
	/**
	 *
	 * @type {string}
	 * @memberof AdminUpdateUserRequest
	 */
	lastName?: string;
	/**
	 *
	 * @type {string}
	 * @memberof AdminUpdateUserRequest
	 */
	phone?: string;
	/**
	 *
	 * @type {boolean}
	 * @memberof AdminUpdateUserRequest
	 */
	phoneVerified?: boolean;
	/**
	 *
	 * @type {SchemaRole}
	 * @memberof AdminUpdateUserRequest
	 */
	role?: SchemaRole;
	/**
	 *
	 * @type {UserStatus}
	 * @memberof AdminUpdateUserRequest
	 */
	status?: UserStatus;
}

/**
 * Check if a given object implements the AdminUpdateUserRequest interface.
 */
export function instanceOfAdminUpdateUserRequest(value: object): value is AdminUpdateUserRequest {
	return true;
}

export function AdminUpdateUserRequestFromJSON(json: any): AdminUpdateUserRequest {
	return AdminUpdateUserRequestFromJSONTyped(json, false);
}

export function AdminUpdateUserRequestFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): AdminUpdateUserRequest {
	if (json == null) {
		return json;
	}
	return {
		emailVerified: json["email_verified"] == null ? undefined : json["email_verified"],
		firstName: json["first_name"] == null ? undefined : json["first_name"],
		lastName: json["last_name"] == null ? undefined : json["last_name"],
		phone: json["phone"] == null ? undefined : json["phone"],
		phoneVerified: json["phone_verified"] == null ? undefined : json["phone_verified"],
		role: json["role"] == null ? undefined : SchemaRoleFromJSON(json["role"]),
		status: json["status"] == null ? undefined : UserStatusFromJSON(json["status"])
	};
}

export function AdminUpdateUserRequestToJSON(json: any): AdminUpdateUserRequest {
	return AdminUpdateUserRequestToJSONTyped(json, false);
}

export function AdminUpdateUserRequestToJSONTyped(
	value?: AdminUpdateUserRequest | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		email_verified: value["emailVerified"],
		first_name: value["firstName"],
		last_name: value["lastName"],
		phone: value["phone"],
		phone_verified: value["phoneVerified"],
		role: SchemaRoleToJSON(value["role"]),
		status: UserStatusToJSON(value["status"])
	};
}
