/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { AdminVendorDocument } from "./AdminVendorDocument";
import {
	AdminVendorDocumentFromJSON,
	AdminVendorDocumentFromJSONTyped,
	AdminVendorDocumentToJSON,
	AdminVendorDocumentToJSONTyped
} from "./AdminVendorDocument";
import type { VendorprofileStatus } from "./VendorprofileStatus";
import {
	VendorprofileStatusFromJSON,
	VendorprofileStatusFromJSONTyped,
	VendorprofileStatusToJSON,
	VendorprofileStatusToJSONTyped
} from "./VendorprofileStatus";

/**
 *
 * @export
 * @interface AdminAdminVendorResponse
 */
export interface AdminAdminVendorResponse {
	/**
	 *
	 * @type {string}
	 * @memberof AdminAdminVendorResponse
	 */
	address?: string;
	/**
	 *
	 * @type {Array<object>}
	 * @memberof AdminAdminVendorResponse
	 */
	businessDays?: Array<object>;
	/**
	 *
	 * @type {string}
	 * @memberof AdminAdminVendorResponse
	 */
	businessName?: string;
	/**
	 *
	 * @type {string}
	 * @memberof AdminAdminVendorResponse
	 */
	city?: string;
	/**
	 *
	 * @type {string}
	 * @memberof AdminAdminVendorResponse
	 */
	createdAt?: string;
	/**
	 *
	 * @type {string}
	 * @memberof AdminAdminVendorResponse
	 */
	description?: string;
	/**
	 *
	 * @type {Array<AdminVendorDocument>}
	 * @memberof AdminAdminVendorResponse
	 */
	documents?: Array<AdminVendorDocument>;
	/**
	 *
	 * @type {string}
	 * @memberof AdminAdminVendorResponse
	 */
	email?: string;
	/**
	 *
	 * @type {boolean}
	 * @memberof AdminAdminVendorResponse
	 */
	emailVerified?: boolean;
	/**
	 *
	 * @type {string}
	 * @memberof AdminAdminVendorResponse
	 */
	firstName?: string;
	/**
	 *
	 * @type {string}
	 * @memberof AdminAdminVendorResponse
	 */
	id?: string;
	/**
	 *
	 * @type {string}
	 * @memberof AdminAdminVendorResponse
	 */
	lastLogin?: string;
	/**
	 *
	 * @type {string}
	 * @memberof AdminAdminVendorResponse
	 */
	lastName?: string;
	/**
	 *
	 * @type {number}
	 * @memberof AdminAdminVendorResponse
	 */
	latitude?: number;
	/**
	 *
	 * @type {number}
	 * @memberof AdminAdminVendorResponse
	 */
	longitude?: number;
	/**
	 *
	 * @type {number}
	 * @memberof AdminAdminVendorResponse
	 */
	minOrderAmount?: number;
	/**
	 *
	 * @type {string}
	 * @memberof AdminAdminVendorResponse
	 */
	phone?: string;
	/**
	 *
	 * @type {boolean}
	 * @memberof AdminAdminVendorResponse
	 */
	phoneVerified?: boolean;
	/**
	 *
	 * @type {string}
	 * @memberof AdminAdminVendorResponse
	 */
	postalCode?: string;
	/**
	 *
	 * @type {number}
	 * @memberof AdminAdminVendorResponse
	 */
	preparationTimeMinutes?: number;
	/**
	 *
	 * @type {string}
	 * @memberof AdminAdminVendorResponse
	 */
	siret?: string;
	/**
	 *
	 * @type {VendorprofileStatus}
	 * @memberof AdminAdminVendorResponse
	 */
	status?: VendorprofileStatus;
	/**
	 *
	 * @type {string}
	 * @memberof AdminAdminVendorResponse
	 */
	stripeAccountId?: string;
	/**
	 *
	 * @type {boolean}
	 * @memberof AdminAdminVendorResponse
	 */
	stripeActive?: boolean;
	/**
	 *
	 * @type {string}
	 * @memberof AdminAdminVendorResponse
	 */
	timezone?: string;
	/**
	 *
	 * @type {string}
	 * @memberof AdminAdminVendorResponse
	 */
	updatedAt?: string;
}

/**
 * Check if a given object implements the AdminAdminVendorResponse interface.
 */
export function instanceOfAdminAdminVendorResponse(
	value: object
): value is AdminAdminVendorResponse {
	return true;
}

export function AdminAdminVendorResponseFromJSON(json: any): AdminAdminVendorResponse {
	return AdminAdminVendorResponseFromJSONTyped(json, false);
}

export function AdminAdminVendorResponseFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): AdminAdminVendorResponse {
	if (json == null) {
		return json;
	}
	return {
		address: json["address"] == null ? undefined : json["address"],
		businessDays: json["business_days"] == null ? undefined : json["business_days"],
		businessName: json["business_name"] == null ? undefined : json["business_name"],
		city: json["city"] == null ? undefined : json["city"],
		createdAt: json["created_at"] == null ? undefined : json["created_at"],
		description: json["description"] == null ? undefined : json["description"],
		documents:
			json["documents"] == null
				? undefined
				: (json["documents"] as Array<any>).map(AdminVendorDocumentFromJSON),
		email: json["email"] == null ? undefined : json["email"],
		emailVerified: json["email_verified"] == null ? undefined : json["email_verified"],
		firstName: json["first_name"] == null ? undefined : json["first_name"],
		id: json["id"] == null ? undefined : json["id"],
		lastLogin: json["last_login"] == null ? undefined : json["last_login"],
		lastName: json["last_name"] == null ? undefined : json["last_name"],
		latitude: json["latitude"] == null ? undefined : json["latitude"],
		longitude: json["longitude"] == null ? undefined : json["longitude"],
		minOrderAmount: json["min_order_amount"] == null ? undefined : json["min_order_amount"],
		phone: json["phone"] == null ? undefined : json["phone"],
		phoneVerified: json["phone_verified"] == null ? undefined : json["phone_verified"],
		postalCode: json["postal_code"] == null ? undefined : json["postal_code"],
		preparationTimeMinutes:
			json["preparation_time_minutes"] == null ? undefined : json["preparation_time_minutes"],
		siret: json["siret"] == null ? undefined : json["siret"],
		status: json["status"] == null ? undefined : VendorprofileStatusFromJSON(json["status"]),
		stripeAccountId: json["stripe_account_id"] == null ? undefined : json["stripe_account_id"],
		stripeActive: json["stripe_active"] == null ? undefined : json["stripe_active"],
		timezone: json["timezone"] == null ? undefined : json["timezone"],
		updatedAt: json["updated_at"] == null ? undefined : json["updated_at"]
	};
}

export function AdminAdminVendorResponseToJSON(json: any): AdminAdminVendorResponse {
	return AdminAdminVendorResponseToJSONTyped(json, false);
}

export function AdminAdminVendorResponseToJSONTyped(
	value?: AdminAdminVendorResponse | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		address: value["address"],
		business_days: value["businessDays"],
		business_name: value["businessName"],
		city: value["city"],
		created_at: value["createdAt"],
		description: value["description"],
		documents:
			value["documents"] == null
				? undefined
				: (value["documents"] as Array<any>).map(AdminVendorDocumentToJSON),
		email: value["email"],
		email_verified: value["emailVerified"],
		first_name: value["firstName"],
		id: value["id"],
		last_login: value["lastLogin"],
		last_name: value["lastName"],
		latitude: value["latitude"],
		longitude: value["longitude"],
		min_order_amount: value["minOrderAmount"],
		phone: value["phone"],
		phone_verified: value["phoneVerified"],
		postal_code: value["postalCode"],
		preparation_time_minutes: value["preparationTimeMinutes"],
		siret: value["siret"],
		status: VendorprofileStatusToJSON(value["status"]),
		stripe_account_id: value["stripeAccountId"],
		stripe_active: value["stripeActive"],
		timezone: value["timezone"],
		updated_at: value["updatedAt"]
	};
}
