/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AdminVehicleTypeResponse
 */
export interface AdminVehicleTypeResponse {
	/**
	 *
	 * @type {number}
	 * @memberof AdminVehicleTypeResponse
	 */
	id?: number;
	/**
	 *
	 * @type {string}
	 * @memberof AdminVehicleTypeResponse
	 */
	label?: string;
	/**
	 *
	 * @type {number}
	 * @memberof AdminVehicleTypeResponse
	 */
	maxDistanceKm?: number;
	/**
	 *
	 * @type {number}
	 * @memberof AdminVehicleTypeResponse
	 */
	maxHeightCm?: number;
	/**
	 *
	 * @type {number}
	 * @memberof AdminVehicleTypeResponse
	 */
	maxLengthCm?: number;
	/**
	 *
	 * @type {number}
	 * @memberof AdminVehicleTypeResponse
	 */
	maxWeightKg?: number;
	/**
	 *
	 * @type {number}
	 * @memberof AdminVehicleTypeResponse
	 */
	maxWidthCm?: number;
	/**
	 *
	 * @type {boolean}
	 * @memberof AdminVehicleTypeResponse
	 */
	needsDocuments?: boolean;
}

/**
 * Check if a given object implements the AdminVehicleTypeResponse interface.
 */
export function instanceOfAdminVehicleTypeResponse(
	value: object
): value is AdminVehicleTypeResponse {
	return true;
}

export function AdminVehicleTypeResponseFromJSON(json: any): AdminVehicleTypeResponse {
	return AdminVehicleTypeResponseFromJSONTyped(json, false);
}

export function AdminVehicleTypeResponseFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): AdminVehicleTypeResponse {
	if (json == null) {
		return json;
	}
	return {
		id: json["id"] == null ? undefined : json["id"],
		label: json["label"] == null ? undefined : json["label"],
		maxDistanceKm: json["max_distance_km"] == null ? undefined : json["max_distance_km"],
		maxHeightCm: json["max_height_cm"] == null ? undefined : json["max_height_cm"],
		maxLengthCm: json["max_length_cm"] == null ? undefined : json["max_length_cm"],
		maxWeightKg: json["max_weight_kg"] == null ? undefined : json["max_weight_kg"],
		maxWidthCm: json["max_width_cm"] == null ? undefined : json["max_width_cm"],
		needsDocuments: json["needs_documents"] == null ? undefined : json["needs_documents"]
	};
}

export function AdminVehicleTypeResponseToJSON(json: any): AdminVehicleTypeResponse {
	return AdminVehicleTypeResponseToJSONTyped(json, false);
}

export function AdminVehicleTypeResponseToJSONTyped(
	value?: AdminVehicleTypeResponse | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		id: value["id"],
		label: value["label"],
		max_distance_km: value["maxDistanceKm"],
		max_height_cm: value["maxHeightCm"],
		max_length_cm: value["maxLengthCm"],
		max_weight_kg: value["maxWeightKg"],
		max_width_cm: value["maxWidthCm"],
		needs_documents: value["needsDocuments"]
	};
}
