/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { AdminAdminCourierResponse } from "./AdminAdminCourierResponse";
import {
	AdminAdminCourierResponseFromJSON,
	AdminAdminCourierResponseFromJSONTyped,
	AdminAdminCourierResponseToJSON,
	AdminAdminCourierResponseToJSONTyped
} from "./AdminAdminCourierResponse";

/**
 *
 * @export
 * @interface AdminListCouriersResponse
 */
export interface AdminListCouriersResponse {
	/**
	 *
	 * @type {Array<AdminAdminCourierResponse>}
	 * @memberof AdminListCouriersResponse
	 */
	couriers?: Array<AdminAdminCourierResponse>;
	/**
	 *
	 * @type {number}
	 * @memberof AdminListCouriersResponse
	 */
	limit?: number;
	/**
	 *
	 * @type {number}
	 * @memberof AdminListCouriersResponse
	 */
	page?: number;
	/**
	 *
	 * @type {number}
	 * @memberof AdminListCouriersResponse
	 */
	total?: number;
}

/**
 * Check if a given object implements the AdminListCouriersResponse interface.
 */
export function instanceOfAdminListCouriersResponse(
	value: object
): value is AdminListCouriersResponse {
	return true;
}

export function AdminListCouriersResponseFromJSON(json: any): AdminListCouriersResponse {
	return AdminListCouriersResponseFromJSONTyped(json, false);
}

export function AdminListCouriersResponseFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): AdminListCouriersResponse {
	if (json == null) {
		return json;
	}
	return {
		couriers:
			json["couriers"] == null
				? undefined
				: (json["couriers"] as Array<any>).map(AdminAdminCourierResponseFromJSON),
		limit: json["limit"] == null ? undefined : json["limit"],
		page: json["page"] == null ? undefined : json["page"],
		total: json["total"] == null ? undefined : json["total"]
	};
}

export function AdminListCouriersResponseToJSON(json: any): AdminListCouriersResponse {
	return AdminListCouriersResponseToJSONTyped(json, false);
}

export function AdminListCouriersResponseToJSONTyped(
	value?: AdminListCouriersResponse | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		couriers:
			value["couriers"] == null
				? undefined
				: (value["couriers"] as Array<any>).map(AdminAdminCourierResponseToJSON),
		limit: value["limit"],
		page: value["page"],
		total: value["total"]
	};
}
