/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AdminCategoryResponse
 */
export interface AdminCategoryResponse {
	/**
	 *
	 * @type {string}
	 * @memberof AdminCategoryResponse
	 */
	createdAt?: string;
	/**
	 *
	 * @type {string}
	 * @memberof AdminCategoryResponse
	 */
	id?: string;
	/**
	 *
	 * @type {string}
	 * @memberof AdminCategoryResponse
	 */
	name?: string;
	/**
	 *
	 * @type {string}
	 * @memberof AdminCategoryResponse
	 */
	updatedAt?: string;
}

/**
 * Check if a given object implements the AdminCategoryResponse interface.
 */
export function instanceOfAdminCategoryResponse(value: object): value is AdminCategoryResponse {
	return true;
}

export function AdminCategoryResponseFromJSON(json: any): AdminCategoryResponse {
	return AdminCategoryResponseFromJSONTyped(json, false);
}

export function AdminCategoryResponseFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): AdminCategoryResponse {
	if (json == null) {
		return json;
	}
	return {
		createdAt: json["created_at"] == null ? undefined : json["created_at"],
		id: json["id"] == null ? undefined : json["id"],
		name: json["name"] == null ? undefined : json["name"],
		updatedAt: json["updated_at"] == null ? undefined : json["updated_at"]
	};
}

export function AdminCategoryResponseToJSON(json: any): AdminCategoryResponse {
	return AdminCategoryResponseToJSONTyped(json, false);
}

export function AdminCategoryResponseToJSONTyped(
	value?: AdminCategoryResponse | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		created_at: value["createdAt"],
		id: value["id"],
		name: value["name"],
		updated_at: value["updatedAt"]
	};
}
