/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AdminCourierDocument
 */
export interface AdminCourierDocument {
	/**
	 *
	 * @type {string}
	 * @memberof AdminCourierDocument
	 */
	type?: string;
	/**
	 *
	 * @type {string}
	 * @memberof AdminCourierDocument
	 */
	url?: string;
}

/**
 * Check if a given object implements the AdminCourierDocument interface.
 */
export function instanceOfAdminCourierDocument(value: object): value is AdminCourierDocument {
	return true;
}

export function AdminCourierDocumentFromJSON(json: any): AdminCourierDocument {
	return AdminCourierDocumentFromJSONTyped(json, false);
}

export function AdminCourierDocumentFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): AdminCourierDocument {
	if (json == null) {
		return json;
	}
	return {
		type: json["type"] == null ? undefined : json["type"],
		url: json["url"] == null ? undefined : json["url"]
	};
}

export function AdminCourierDocumentToJSON(json: any): AdminCourierDocument {
	return AdminCourierDocumentToJSONTyped(json, false);
}

export function AdminCourierDocumentToJSONTyped(
	value?: AdminCourierDocument | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		type: value["type"],
		url: value["url"]
	};
}
