/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { SchemaRole } from "./SchemaRole";
import {
	SchemaRoleFromJSON,
	SchemaRoleFromJSONTyped,
	SchemaRoleToJSON,
	SchemaRoleToJSONTyped
} from "./SchemaRole";
import type { UserStatus } from "./UserStatus";
import {
	UserStatusFromJSON,
	UserStatusFromJSONTyped,
	UserStatusToJSON,
	UserStatusToJSONTyped
} from "./UserStatus";

/**
 *
 * @export
 * @interface AdminAdminUserResponse
 */
export interface AdminAdminUserResponse {
	/**
	 *
	 * @type {string}
	 * @memberof AdminAdminUserResponse
	 */
	approvalStatus?: string;
	/**
	 *
	 * @type {string}
	 * @memberof AdminAdminUserResponse
	 */
	createdAt?: string;
	/**
	 *
	 * @type {string}
	 * @memberof AdminAdminUserResponse
	 */
	email?: string;
	/**
	 *
	 * @type {boolean}
	 * @memberof AdminAdminUserResponse
	 */
	emailVerified?: boolean;
	/**
	 *
	 * @type {string}
	 * @memberof AdminAdminUserResponse
	 */
	firstName?: string;
	/**
	 *
	 * @type {string}
	 * @memberof AdminAdminUserResponse
	 */
	id?: string;
	/**
	 *
	 * @type {string}
	 * @memberof AdminAdminUserResponse
	 */
	lastLogin?: string;
	/**
	 *
	 * @type {string}
	 * @memberof AdminAdminUserResponse
	 */
	lastName?: string;
	/**
	 *
	 * @type {string}
	 * @memberof AdminAdminUserResponse
	 */
	phone?: string;
	/**
	 *
	 * @type {boolean}
	 * @memberof AdminAdminUserResponse
	 */
	phoneVerified?: boolean;
	/**
	 *
	 * @type {SchemaRole}
	 * @memberof AdminAdminUserResponse
	 */
	role?: SchemaRole;
	/**
	 *
	 * @type {UserStatus}
	 * @memberof AdminAdminUserResponse
	 */
	status?: UserStatus;
	/**
	 *
	 * @type {string}
	 * @memberof AdminAdminUserResponse
	 */
	updatedAt?: string;
}

/**
 * Check if a given object implements the AdminAdminUserResponse interface.
 */
export function instanceOfAdminAdminUserResponse(value: object): value is AdminAdminUserResponse {
	return true;
}

export function AdminAdminUserResponseFromJSON(json: any): AdminAdminUserResponse {
	return AdminAdminUserResponseFromJSONTyped(json, false);
}

export function AdminAdminUserResponseFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): AdminAdminUserResponse {
	if (json == null) {
		return json;
	}
	return {
		approvalStatus: json["approval_status"] == null ? undefined : json["approval_status"],
		createdAt: json["created_at"] == null ? undefined : json["created_at"],
		email: json["email"] == null ? undefined : json["email"],
		emailVerified: json["email_verified"] == null ? undefined : json["email_verified"],
		firstName: json["first_name"] == null ? undefined : json["first_name"],
		id: json["id"] == null ? undefined : json["id"],
		lastLogin: json["last_login"] == null ? undefined : json["last_login"],
		lastName: json["last_name"] == null ? undefined : json["last_name"],
		phone: json["phone"] == null ? undefined : json["phone"],
		phoneVerified: json["phone_verified"] == null ? undefined : json["phone_verified"],
		role: json["role"] == null ? undefined : SchemaRoleFromJSON(json["role"]),
		status: json["status"] == null ? undefined : UserStatusFromJSON(json["status"]),
		updatedAt: json["updated_at"] == null ? undefined : json["updated_at"]
	};
}

export function AdminAdminUserResponseToJSON(json: any): AdminAdminUserResponse {
	return AdminAdminUserResponseToJSONTyped(json, false);
}

export function AdminAdminUserResponseToJSONTyped(
	value?: AdminAdminUserResponse | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		approval_status: value["approvalStatus"],
		created_at: value["createdAt"],
		email: value["email"],
		email_verified: value["emailVerified"],
		first_name: value["firstName"],
		id: value["id"],
		last_login: value["lastLogin"],
		last_name: value["lastName"],
		phone: value["phone"],
		phone_verified: value["phoneVerified"],
		role: SchemaRoleToJSON(value["role"]),
		status: UserStatusToJSON(value["status"]),
		updated_at: value["updatedAt"]
	};
}
