/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { AdminAdminVendorResponse } from "./AdminAdminVendorResponse";
import {
	AdminAdminVendorResponseFromJSON,
	AdminAdminVendorResponseFromJSONTyped,
	AdminAdminVendorResponseToJSON,
	AdminAdminVendorResponseToJSONTyped
} from "./AdminAdminVendorResponse";

/**
 *
 * @export
 * @interface AdminListVendorsResponse
 */
export interface AdminListVendorsResponse {
	/**
	 *
	 * @type {number}
	 * @memberof AdminListVendorsResponse
	 */
	limit?: number;
	/**
	 *
	 * @type {number}
	 * @memberof AdminListVendorsResponse
	 */
	page?: number;
	/**
	 *
	 * @type {number}
	 * @memberof AdminListVendorsResponse
	 */
	total?: number;
	/**
	 *
	 * @type {Array<AdminAdminVendorResponse>}
	 * @memberof AdminListVendorsResponse
	 */
	vendors?: Array<AdminAdminVendorResponse>;
}

/**
 * Check if a given object implements the AdminListVendorsResponse interface.
 */
export function instanceOfAdminListVendorsResponse(
	value: object
): value is AdminListVendorsResponse {
	return true;
}

export function AdminListVendorsResponseFromJSON(json: any): AdminListVendorsResponse {
	return AdminListVendorsResponseFromJSONTyped(json, false);
}

export function AdminListVendorsResponseFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): AdminListVendorsResponse {
	if (json == null) {
		return json;
	}
	return {
		limit: json["limit"] == null ? undefined : json["limit"],
		page: json["page"] == null ? undefined : json["page"],
		total: json["total"] == null ? undefined : json["total"],
		vendors:
			json["vendors"] == null
				? undefined
				: (json["vendors"] as Array<any>).map(AdminAdminVendorResponseFromJSON)
	};
}

export function AdminListVendorsResponseToJSON(json: any): AdminListVendorsResponse {
	return AdminListVendorsResponseToJSONTyped(json, false);
}

export function AdminListVendorsResponseToJSONTyped(
	value?: AdminListVendorsResponse | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		limit: value["limit"],
		page: value["page"],
		total: value["total"],
		vendors:
			value["vendors"] == null
				? undefined
				: (value["vendors"] as Array<any>).map(AdminAdminVendorResponseToJSON)
	};
}
