/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AdminUpdateCategoryRequest
 */
export interface AdminUpdateCategoryRequest {
	/**
	 *
	 * @type {string}
	 * @memberof AdminUpdateCategoryRequest
	 */
	name?: string;
}

/**
 * Check if a given object implements the AdminUpdateCategoryRequest interface.
 */
export function instanceOfAdminUpdateCategoryRequest(
	value: object
): value is AdminUpdateCategoryRequest {
	return true;
}

export function AdminUpdateCategoryRequestFromJSON(json: any): AdminUpdateCategoryRequest {
	return AdminUpdateCategoryRequestFromJSONTyped(json, false);
}

export function AdminUpdateCategoryRequestFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): AdminUpdateCategoryRequest {
	if (json == null) {
		return json;
	}
	return {
		name: json["name"] == null ? undefined : json["name"]
	};
}

export function AdminUpdateCategoryRequestToJSON(json: any): AdminUpdateCategoryRequest {
	return AdminUpdateCategoryRequestToJSONTyped(json, false);
}

export function AdminUpdateCategoryRequestToJSONTyped(
	value?: AdminUpdateCategoryRequest | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		name: value["name"]
	};
}
