/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AdminCreateVehicleTypeRequest
 */
export interface AdminCreateVehicleTypeRequest {
	/**
	 *
	 * @type {string}
	 * @memberof AdminCreateVehicleTypeRequest
	 */
	label: string;
	/**
	 *
	 * @type {number}
	 * @memberof AdminCreateVehicleTypeRequest
	 */
	maxDistanceKm: number;
	/**
	 *
	 * @type {number}
	 * @memberof AdminCreateVehicleTypeRequest
	 */
	maxHeightCm: number;
	/**
	 *
	 * @type {number}
	 * @memberof AdminCreateVehicleTypeRequest
	 */
	maxLengthCm: number;
	/**
	 *
	 * @type {number}
	 * @memberof AdminCreateVehicleTypeRequest
	 */
	maxWeightKg: number;
	/**
	 *
	 * @type {number}
	 * @memberof AdminCreateVehicleTypeRequest
	 */
	maxWidthCm: number;
	/**
	 *
	 * @type {boolean}
	 * @memberof AdminCreateVehicleTypeRequest
	 */
	needsDocuments?: boolean;
}

/**
 * Check if a given object implements the AdminCreateVehicleTypeRequest interface.
 */
export function instanceOfAdminCreateVehicleTypeRequest(
	value: object
): value is AdminCreateVehicleTypeRequest {
	if (!("label" in value) || value["label"] === undefined) return false;
	if (!("maxDistanceKm" in value) || value["maxDistanceKm"] === undefined) return false;
	if (!("maxHeightCm" in value) || value["maxHeightCm"] === undefined) return false;
	if (!("maxLengthCm" in value) || value["maxLengthCm"] === undefined) return false;
	if (!("maxWeightKg" in value) || value["maxWeightKg"] === undefined) return false;
	if (!("maxWidthCm" in value) || value["maxWidthCm"] === undefined) return false;
	return true;
}

export function AdminCreateVehicleTypeRequestFromJSON(json: any): AdminCreateVehicleTypeRequest {
	return AdminCreateVehicleTypeRequestFromJSONTyped(json, false);
}

export function AdminCreateVehicleTypeRequestFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): AdminCreateVehicleTypeRequest {
	if (json == null) {
		return json;
	}
	return {
		label: json["label"],
		maxDistanceKm: json["max_distance_km"],
		maxHeightCm: json["max_height_cm"],
		maxLengthCm: json["max_length_cm"],
		maxWeightKg: json["max_weight_kg"],
		maxWidthCm: json["max_width_cm"],
		needsDocuments: json["needs_documents"] == null ? undefined : json["needs_documents"]
	};
}

export function AdminCreateVehicleTypeRequestToJSON(json: any): AdminCreateVehicleTypeRequest {
	return AdminCreateVehicleTypeRequestToJSONTyped(json, false);
}

export function AdminCreateVehicleTypeRequestToJSONTyped(
	value?: AdminCreateVehicleTypeRequest | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		label: value["label"],
		max_distance_km: value["maxDistanceKm"],
		max_height_cm: value["maxHeightCm"],
		max_length_cm: value["maxLengthCm"],
		max_weight_kg: value["maxWeightKg"],
		max_width_cm: value["maxWidthCm"],
		needs_documents: value["needsDocuments"]
	};
}
