/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const CourierprofileStatus = {
	DefaultStatus: "pending_approval",
	StatusPendingApproval: "pending_approval",
	StatusApproved: "approved",
	StatusActive: "active",
	StatusRejected: "rejected"
} as const;
export type CourierprofileStatus = (typeof CourierprofileStatus)[keyof typeof CourierprofileStatus];

export function instanceOfCourierprofileStatus(value: any): boolean {
	for (const key in CourierprofileStatus) {
		if (Object.prototype.hasOwnProperty.call(CourierprofileStatus, key)) {
			if (CourierprofileStatus[key as keyof typeof CourierprofileStatus] === value) {
				return true;
			}
		}
	}
	return false;
}

export function CourierprofileStatusFromJSON(json: any): CourierprofileStatus {
	return CourierprofileStatusFromJSONTyped(json, false);
}

export function CourierprofileStatusFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): CourierprofileStatus {
	return json as CourierprofileStatus;
}

export function CourierprofileStatusToJSON(value?: CourierprofileStatus | null): any {
	return value as any;
}

export function CourierprofileStatusToJSONTyped(
	value: any,
	ignoreDiscriminator: boolean
): CourierprofileStatus {
	return value as CourierprofileStatus;
}
