/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { EntCourierProfileEdges } from "./EntCourierProfileEdges";
import {
	EntCourierProfileEdgesFromJSON,
	EntCourierProfileEdgesFromJSONTyped,
	EntCourierProfileEdgesToJSON,
	EntCourierProfileEdgesToJSONTyped
} from "./EntCourierProfileEdges";
import type { CourierprofileStatus } from "./CourierprofileStatus";
import {
	CourierprofileStatusFromJSON,
	CourierprofileStatusFromJSONTyped,
	CourierprofileStatusToJSON,
	CourierprofileStatusToJSONTyped
} from "./CourierprofileStatus";

/**
 *
 * @export
 * @interface EntCourierProfile
 */
export interface EntCourierProfile {
	/**
	 * AttestationDate holds the value of the "attestation_date" field.
	 * @type {string}
	 * @memberof EntCourierProfile
	 */
	attestationDate?: string;
	/**
	 * AttestationIP holds the value of the "attestation_ip" field.
	 * @type {string}
	 * @memberof EntCourierProfile
	 */
	attestationIp?: string;
	/**
	 * AttestationText holds the value of the "attestation_text" field.
	 * @type {string}
	 * @memberof EntCourierProfile
	 */
	attestationText?: string;
	/**
	 * CreatedAt holds the value of the "created_at" field.
	 * @type {string}
	 * @memberof EntCourierProfile
	 */
	createdAt?: string;
	/**
	 * DriverLicenseS3 holds the value of the "driver_license_s3" field.
	 * @type {string}
	 * @memberof EntCourierProfile
	 */
	driverLicenseS3?: string;
	/**
	 * Edges holds the relations/edges for other nodes in the graph.
	 * The values are being populated by the CourierProfileQuery when eager-loading is set.
	 * @type {EntCourierProfileEdges}
	 * @memberof EntCourierProfile
	 */
	edges?: EntCourierProfileEdges;
	/**
	 * ID of the ent.
	 * @type {string}
	 * @memberof EntCourierProfile
	 */
	id?: string;
	/**
	 * ProfessionalLiabilityS3 holds the value of the "professional_liability_s3" field.
	 * @type {string}
	 * @memberof EntCourierProfile
	 */
	professionalLiabilityS3?: string;
	/**
	 * Status holds the value of the "status" field.
	 * @type {CourierprofileStatus}
	 * @memberof EntCourierProfile
	 */
	status?: CourierprofileStatus;
	/**
	 * StripeAccountID holds the value of the "stripe_account_id" field.
	 * @type {string}
	 * @memberof EntCourierProfile
	 */
	stripeAccountId?: string;
	/**
	 * StripeActive holds the value of the "stripe_active" field.
	 * @type {boolean}
	 * @memberof EntCourierProfile
	 */
	stripeActive?: boolean;
	/**
	 * TransportLicenseS3 holds the value of the "transport_license_s3" field.
	 * @type {string}
	 * @memberof EntCourierProfile
	 */
	transportLicenseS3?: string;
	/**
	 * UpdatedAt holds the value of the "updated_at" field.
	 * @type {string}
	 * @memberof EntCourierProfile
	 */
	updatedAt?: string;
	/**
	 * UserID holds the value of the "user_id" field.
	 * @type {string}
	 * @memberof EntCourierProfile
	 */
	userId?: string;
	/**
	 * VehicleInspectionS3 holds the value of the "vehicle_inspection_s3" field.
	 * @type {string}
	 * @memberof EntCourierProfile
	 */
	vehicleInspectionS3?: string;
	/**
	 * VehicleInsuranceS3 holds the value of the "vehicle_insurance_s3" field.
	 * @type {string}
	 * @memberof EntCourierProfile
	 */
	vehicleInsuranceS3?: string;
	/**
	 * VehicleRegistrationS3 holds the value of the "vehicle_registration_s3" field.
	 * @type {string}
	 * @memberof EntCourierProfile
	 */
	vehicleRegistrationS3?: string;
	/**
	 * VehicleTypeID holds the value of the "vehicle_type_id" field.
	 * @type {number}
	 * @memberof EntCourierProfile
	 */
	vehicleTypeId?: number;
}

/**
 * Check if a given object implements the EntCourierProfile interface.
 */
export function instanceOfEntCourierProfile(value: object): value is EntCourierProfile {
	return true;
}

export function EntCourierProfileFromJSON(json: any): EntCourierProfile {
	return EntCourierProfileFromJSONTyped(json, false);
}

export function EntCourierProfileFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): EntCourierProfile {
	if (json == null) {
		return json;
	}
	return {
		attestationDate: json["attestation_date"] == null ? undefined : json["attestation_date"],
		attestationIp: json["attestation_ip"] == null ? undefined : json["attestation_ip"],
		attestationText: json["attestation_text"] == null ? undefined : json["attestation_text"],
		createdAt: json["created_at"] == null ? undefined : json["created_at"],
		driverLicenseS3: json["driver_license_s3"] == null ? undefined : json["driver_license_s3"],
		edges: json["edges"] == null ? undefined : EntCourierProfileEdgesFromJSON(json["edges"]),
		id: json["id"] == null ? undefined : json["id"],
		professionalLiabilityS3:
			json["professional_liability_s3"] == null ? undefined : json["professional_liability_s3"],
		status: json["status"] == null ? undefined : CourierprofileStatusFromJSON(json["status"]),
		stripeAccountId: json["stripe_account_id"] == null ? undefined : json["stripe_account_id"],
		stripeActive: json["stripe_active"] == null ? undefined : json["stripe_active"],
		transportLicenseS3:
			json["transport_license_s3"] == null ? undefined : json["transport_license_s3"],
		updatedAt: json["updated_at"] == null ? undefined : json["updated_at"],
		userId: json["user_id"] == null ? undefined : json["user_id"],
		vehicleInspectionS3:
			json["vehicle_inspection_s3"] == null ? undefined : json["vehicle_inspection_s3"],
		vehicleInsuranceS3:
			json["vehicle_insurance_s3"] == null ? undefined : json["vehicle_insurance_s3"],
		vehicleRegistrationS3:
			json["vehicle_registration_s3"] == null ? undefined : json["vehicle_registration_s3"],
		vehicleTypeId: json["vehicle_type_id"] == null ? undefined : json["vehicle_type_id"]
	};
}

export function EntCourierProfileToJSON(json: any): EntCourierProfile {
	return EntCourierProfileToJSONTyped(json, false);
}

export function EntCourierProfileToJSONTyped(
	value?: EntCourierProfile | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		attestation_date: value["attestationDate"],
		attestation_ip: value["attestationIp"],
		attestation_text: value["attestationText"],
		created_at: value["createdAt"],
		driver_license_s3: value["driverLicenseS3"],
		edges: EntCourierProfileEdgesToJSON(value["edges"]),
		id: value["id"],
		professional_liability_s3: value["professionalLiabilityS3"],
		status: CourierprofileStatusToJSON(value["status"]),
		stripe_account_id: value["stripeAccountId"],
		stripe_active: value["stripeActive"],
		transport_license_s3: value["transportLicenseS3"],
		updated_at: value["updatedAt"],
		user_id: value["userId"],
		vehicle_inspection_s3: value["vehicleInspectionS3"],
		vehicle_insurance_s3: value["vehicleInsuranceS3"],
		vehicle_registration_s3: value["vehicleRegistrationS3"],
		vehicle_type_id: value["vehicleTypeId"]
	};
}
