/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { EntUser } from "./EntUser";
import {
	EntUserFromJSON,
	EntUserFromJSONTyped,
	EntUserToJSON,
	EntUserToJSONTyped
} from "./EntUser";
import type { EntVehicleType } from "./EntVehicleType";
import {
	EntVehicleTypeFromJSON,
	EntVehicleTypeFromJSONTyped,
	EntVehicleTypeToJSON,
	EntVehicleTypeToJSONTyped
} from "./EntVehicleType";

/**
 *
 * @export
 * @interface EntCourierProfileEdges
 */
export interface EntCourierProfileEdges {
	/**
	 * User holds the value of the user edge.
	 * @type {EntUser}
	 * @memberof EntCourierProfileEdges
	 */
	user?: EntUser;
	/**
	 * VehicleType holds the value of the vehicle_type edge.
	 * @type {EntVehicleType}
	 * @memberof EntCourierProfileEdges
	 */
	vehicleType?: EntVehicleType;
}

/**
 * Check if a given object implements the EntCourierProfileEdges interface.
 */
export function instanceOfEntCourierProfileEdges(value: object): value is EntCourierProfileEdges {
	return true;
}

export function EntCourierProfileEdgesFromJSON(json: any): EntCourierProfileEdges {
	return EntCourierProfileEdgesFromJSONTyped(json, false);
}

export function EntCourierProfileEdgesFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): EntCourierProfileEdges {
	if (json == null) {
		return json;
	}
	return {
		user: json["user"] == null ? undefined : EntUserFromJSON(json["user"]),
		vehicleType:
			json["vehicle_type"] == null ? undefined : EntVehicleTypeFromJSON(json["vehicle_type"])
	};
}

export function EntCourierProfileEdgesToJSON(json: any): EntCourierProfileEdges {
	return EntCourierProfileEdgesToJSONTyped(json, false);
}

export function EntCourierProfileEdgesToJSONTyped(
	value?: EntCourierProfileEdges | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		user: EntUserToJSON(value["user"]),
		vehicle_type: EntVehicleTypeToJSON(value["vehicleType"])
	};
}
