/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { EntUser } from "./EntUser";
import {
	EntUserFromJSON,
	EntUserFromJSONTyped,
	EntUserToJSON,
	EntUserToJSONTyped
} from "./EntUser";

/**
 *
 * @export
 * @interface EntClientProfileEdges
 */
export interface EntClientProfileEdges {
	/**
	 * User holds the value of the user edge.
	 * @type {EntUser}
	 * @memberof EntClientProfileEdges
	 */
	user?: EntUser;
}

/**
 * Check if a given object implements the EntClientProfileEdges interface.
 */
export function instanceOfEntClientProfileEdges(value: object): value is EntClientProfileEdges {
	return true;
}

export function EntClientProfileEdgesFromJSON(json: any): EntClientProfileEdges {
	return EntClientProfileEdgesFromJSONTyped(json, false);
}

export function EntClientProfileEdgesFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): EntClientProfileEdges {
	if (json == null) {
		return json;
	}
	return {
		user: json["user"] == null ? undefined : EntUserFromJSON(json["user"])
	};
}

export function EntClientProfileEdgesToJSON(json: any): EntClientProfileEdges {
	return EntClientProfileEdgesToJSONTyped(json, false);
}

export function EntClientProfileEdgesToJSONTyped(
	value?: EntClientProfileEdges | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		user: EntUserToJSON(value["user"])
	};
}
