/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { EntClientProfileEdges } from "./EntClientProfileEdges";
import {
	EntClientProfileEdgesFromJSON,
	EntClientProfileEdgesFromJSONTyped,
	EntClientProfileEdgesToJSON,
	EntClientProfileEdgesToJSONTyped
} from "./EntClientProfileEdges";

/**
 *
 * @export
 * @interface EntClientProfile
 */
export interface EntClientProfile {
	/**
	 * CreatedAt holds the value of the "created_at" field.
	 * @type {string}
	 * @memberof EntClientProfile
	 */
	createdAt?: string;
	/**
	 * DeliveryAddresses holds the value of the "delivery_addresses" field.
	 * @type {Array<string>}
	 * @memberof EntClientProfile
	 */
	deliveryAddresses?: Array<string>;
	/**
	 * Edges holds the relations/edges for other nodes in the graph.
	 * The values are being populated by the ClientProfileQuery when eager-loading is set.
	 * @type {EntClientProfileEdges}
	 * @memberof EntClientProfile
	 */
	edges?: EntClientProfileEdges;
	/**
	 * ID of the ent.
	 * @type {string}
	 * @memberof EntClientProfile
	 */
	id?: string;
	/**
	 * StripeCustomerID holds the value of the "stripe_customer_id" field.
	 * @type {string}
	 * @memberof EntClientProfile
	 */
	stripeCustomerId?: string;
	/**
	 * UpdatedAt holds the value of the "updated_at" field.
	 * @type {string}
	 * @memberof EntClientProfile
	 */
	updatedAt?: string;
	/**
	 * UserID holds the value of the "user_id" field.
	 * @type {string}
	 * @memberof EntClientProfile
	 */
	userId?: string;
}

/**
 * Check if a given object implements the EntClientProfile interface.
 */
export function instanceOfEntClientProfile(value: object): value is EntClientProfile {
	return true;
}

export function EntClientProfileFromJSON(json: any): EntClientProfile {
	return EntClientProfileFromJSONTyped(json, false);
}

export function EntClientProfileFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): EntClientProfile {
	if (json == null) {
		return json;
	}
	return {
		createdAt: json["created_at"] == null ? undefined : json["created_at"],
		deliveryAddresses: json["delivery_addresses"] == null ? undefined : json["delivery_addresses"],
		edges: json["edges"] == null ? undefined : EntClientProfileEdgesFromJSON(json["edges"]),
		id: json["id"] == null ? undefined : json["id"],
		stripeCustomerId: json["stripe_customer_id"] == null ? undefined : json["stripe_customer_id"],
		updatedAt: json["updated_at"] == null ? undefined : json["updated_at"],
		userId: json["user_id"] == null ? undefined : json["user_id"]
	};
}

export function EntClientProfileToJSON(json: any): EntClientProfile {
	return EntClientProfileToJSONTyped(json, false);
}

export function EntClientProfileToJSONTyped(
	value?: EntClientProfile | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		created_at: value["createdAt"],
		delivery_addresses: value["deliveryAddresses"],
		edges: EntClientProfileEdgesToJSON(value["edges"]),
		id: value["id"],
		stripe_customer_id: value["stripeCustomerId"],
		updated_at: value["updatedAt"],
		user_id: value["userId"]
	};
}
