/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { EntVendorProfile } from "./EntVendorProfile";
import {
	EntVendorProfileFromJSON,
	EntVendorProfileFromJSONTyped,
	EntVendorProfileToJSON,
	EntVendorProfileToJSONTyped
} from "./EntVendorProfile";
import type { EntProductCategory } from "./EntProductCategory";
import {
	EntProductCategoryFromJSON,
	EntProductCategoryFromJSONTyped,
	EntProductCategoryToJSON,
	EntProductCategoryToJSONTyped
} from "./EntProductCategory";

/**
 *
 * @export
 * @interface EntProductEdges
 */
export interface EntProductEdges {
	/**
	 * Category holds the value of the category edge.
	 * @type {EntProductCategory}
	 * @memberof EntProductEdges
	 */
	category?: EntProductCategory;
	/**
	 * Vendor holds the value of the vendor edge.
	 * @type {EntVendorProfile}
	 * @memberof EntProductEdges
	 */
	vendor?: EntVendorProfile;
}

/**
 * Check if a given object implements the EntProductEdges interface.
 */
export function instanceOfEntProductEdges(value: object): value is EntProductEdges {
	return true;
}

export function EntProductEdgesFromJSON(json: any): EntProductEdges {
	return EntProductEdgesFromJSONTyped(json, false);
}

export function EntProductEdgesFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): EntProductEdges {
	if (json == null) {
		return json;
	}
	return {
		category: json["category"] == null ? undefined : EntProductCategoryFromJSON(json["category"]),
		vendor: json["vendor"] == null ? undefined : EntVendorProfileFromJSON(json["vendor"])
	};
}

export function EntProductEdgesToJSON(json: any): EntProductEdges {
	return EntProductEdgesToJSONTyped(json, false);
}

export function EntProductEdgesToJSONTyped(
	value?: EntProductEdges | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		category: EntProductCategoryToJSON(value["category"]),
		vendor: EntVendorProfileToJSON(value["vendor"])
	};
}
