/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { EntProductCategoryEdges } from "./EntProductCategoryEdges";
import {
	EntProductCategoryEdgesFromJSON,
	EntProductCategoryEdgesFromJSONTyped,
	EntProductCategoryEdgesToJSON,
	EntProductCategoryEdgesToJSONTyped
} from "./EntProductCategoryEdges";

/**
 *
 * @export
 * @interface EntProductCategory
 */
export interface EntProductCategory {
	/**
	 * CreatedAt holds the value of the "created_at" field.
	 * @type {string}
	 * @memberof EntProductCategory
	 */
	createdAt?: string;
	/**
	 * Edges holds the relations/edges for other nodes in the graph.
	 * The values are being populated by the ProductCategoryQuery when eager-loading is set.
	 * @type {EntProductCategoryEdges}
	 * @memberof EntProductCategory
	 */
	edges?: EntProductCategoryEdges;
	/**
	 * ID of the ent.
	 * @type {string}
	 * @memberof EntProductCategory
	 */
	id?: string;
	/**
	 * Name holds the value of the "name" field.
	 * @type {string}
	 * @memberof EntProductCategory
	 */
	name?: string;
	/**
	 * UpdatedAt holds the value of the "updated_at" field.
	 * @type {string}
	 * @memberof EntProductCategory
	 */
	updatedAt?: string;
}

/**
 * Check if a given object implements the EntProductCategory interface.
 */
export function instanceOfEntProductCategory(value: object): value is EntProductCategory {
	return true;
}

export function EntProductCategoryFromJSON(json: any): EntProductCategory {
	return EntProductCategoryFromJSONTyped(json, false);
}

export function EntProductCategoryFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): EntProductCategory {
	if (json == null) {
		return json;
	}
	return {
		createdAt: json["created_at"] == null ? undefined : json["created_at"],
		edges: json["edges"] == null ? undefined : EntProductCategoryEdgesFromJSON(json["edges"]),
		id: json["id"] == null ? undefined : json["id"],
		name: json["name"] == null ? undefined : json["name"],
		updatedAt: json["updated_at"] == null ? undefined : json["updated_at"]
	};
}

export function EntProductCategoryToJSON(json: any): EntProductCategory {
	return EntProductCategoryToJSONTyped(json, false);
}

export function EntProductCategoryToJSONTyped(
	value?: EntProductCategory | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		created_at: value["createdAt"],
		edges: EntProductCategoryEdgesToJSON(value["edges"]),
		id: value["id"],
		name: value["name"],
		updated_at: value["updatedAt"]
	};
}
