/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { EntProduct } from "./EntProduct";
import {
	EntProductFromJSON,
	EntProductFromJSONTyped,
	EntProductToJSON,
	EntProductToJSONTyped
} from "./EntProduct";

/**
 *
 * @export
 * @interface EntProductCategoryEdges
 */
export interface EntProductCategoryEdges {
	/**
	 * Products holds the value of the products edge.
	 * @type {Array<EntProduct>}
	 * @memberof EntProductCategoryEdges
	 */
	products?: Array<EntProduct>;
}

/**
 * Check if a given object implements the EntProductCategoryEdges interface.
 */
export function instanceOfEntProductCategoryEdges(value: object): value is EntProductCategoryEdges {
	return true;
}

export function EntProductCategoryEdgesFromJSON(json: any): EntProductCategoryEdges {
	return EntProductCategoryEdgesFromJSONTyped(json, false);
}

export function EntProductCategoryEdgesFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): EntProductCategoryEdges {
	if (json == null) {
		return json;
	}
	return {
		products:
			json["products"] == null
				? undefined
				: (json["products"] as Array<any>).map(EntProductFromJSON)
	};
}

export function EntProductCategoryEdgesToJSON(json: any): EntProductCategoryEdges {
	return EntProductCategoryEdgesToJSONTyped(json, false);
}

export function EntProductCategoryEdgesToJSONTyped(
	value?: EntProductCategoryEdges | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		products:
			value["products"] == null
				? undefined
				: (value["products"] as Array<any>).map(EntProductToJSON)
	};
}
