/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ProductStatus } from "./ProductStatus";
import {
	ProductStatusFromJSON,
	ProductStatusFromJSONTyped,
	ProductStatusToJSON,
	ProductStatusToJSONTyped
} from "./ProductStatus";
import type { EntProductEdges } from "./EntProductEdges";
import {
	EntProductEdgesFromJSON,
	EntProductEdgesFromJSONTyped,
	EntProductEdgesToJSON,
	EntProductEdgesToJSONTyped
} from "./EntProductEdges";

/**
 *
 * @export
 * @interface EntProduct
 */
export interface EntProduct {
	/**
	 * CategoryID holds the value of the "category_id" field.
	 * @type {string}
	 * @memberof EntProduct
	 */
	categoryId?: string;
	/**
	 * CreatedAt holds the value of the "created_at" field.
	 * @type {string}
	 * @memberof EntProduct
	 */
	createdAt?: string;
	/**
	 * Description holds the value of the "description" field.
	 * @type {string}
	 * @memberof EntProduct
	 */
	description?: string;
	/**
	 * Edges holds the relations/edges for other nodes in the graph.
	 * The values are being populated by the ProductQuery when eager-loading is set.
	 * @type {EntProductEdges}
	 * @memberof EntProduct
	 */
	edges?: EntProductEdges;
	/**
	 * Height holds the value of the "height" field.
	 * @type {number}
	 * @memberof EntProduct
	 */
	height?: number;
	/**
	 * ID of the ent.
	 * @type {string}
	 * @memberof EntProduct
	 */
	id?: string;
	/**
	 * Length holds the value of the "length" field.
	 * @type {number}
	 * @memberof EntProduct
	 */
	length?: number;
	/**
	 * Name holds the value of the "name" field.
	 * @type {string}
	 * @memberof EntProduct
	 */
	name?: string;
	/**
	 * Price holds the value of the "price" field.
	 * @type {number}
	 * @memberof EntProduct
	 */
	price?: number;
	/**
	 * ProductImages holds the value of the "product_images" field.
	 * @type {Array<string>}
	 * @memberof EntProduct
	 */
	productImages?: Array<string>;
	/**
	 * Reference holds the value of the "reference" field.
	 * @type {string}
	 * @memberof EntProduct
	 */
	reference?: string;
	/**
	 * Status holds the value of the "status" field.
	 * @type {ProductStatus}
	 * @memberof EntProduct
	 */
	status?: ProductStatus;
	/**
	 * StockQuantity holds the value of the "stock_quantity" field.
	 * @type {number}
	 * @memberof EntProduct
	 */
	stockQuantity?: number;
	/**
	 * UpdatedAt holds the value of the "updated_at" field.
	 * @type {string}
	 * @memberof EntProduct
	 */
	updatedAt?: string;
	/**
	 * VendorID holds the value of the "vendor_id" field.
	 * @type {string}
	 * @memberof EntProduct
	 */
	vendorId?: string;
	/**
	 * Weight holds the value of the "weight" field.
	 * @type {number}
	 * @memberof EntProduct
	 */
	weight?: number;
	/**
	 * Width holds the value of the "width" field.
	 * @type {number}
	 * @memberof EntProduct
	 */
	width?: number;
}

/**
 * Check if a given object implements the EntProduct interface.
 */
export function instanceOfEntProduct(value: object): value is EntProduct {
	return true;
}

export function EntProductFromJSON(json: any): EntProduct {
	return EntProductFromJSONTyped(json, false);
}

export function EntProductFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntProduct {
	if (json == null) {
		return json;
	}
	return {
		categoryId: json["category_id"] == null ? undefined : json["category_id"],
		createdAt: json["created_at"] == null ? undefined : json["created_at"],
		description: json["description"] == null ? undefined : json["description"],
		edges: json["edges"] == null ? undefined : EntProductEdgesFromJSON(json["edges"]),
		height: json["height"] == null ? undefined : json["height"],
		id: json["id"] == null ? undefined : json["id"],
		length: json["length"] == null ? undefined : json["length"],
		name: json["name"] == null ? undefined : json["name"],
		price: json["price"] == null ? undefined : json["price"],
		productImages: json["product_images"] == null ? undefined : json["product_images"],
		reference: json["reference"] == null ? undefined : json["reference"],
		status: json["status"] == null ? undefined : ProductStatusFromJSON(json["status"]),
		stockQuantity: json["stock_quantity"] == null ? undefined : json["stock_quantity"],
		updatedAt: json["updated_at"] == null ? undefined : json["updated_at"],
		vendorId: json["vendor_id"] == null ? undefined : json["vendor_id"],
		weight: json["weight"] == null ? undefined : json["weight"],
		width: json["width"] == null ? undefined : json["width"]
	};
}

export function EntProductToJSON(json: any): EntProduct {
	return EntProductToJSONTyped(json, false);
}

export function EntProductToJSONTyped(
	value?: EntProduct | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		category_id: value["categoryId"],
		created_at: value["createdAt"],
		description: value["description"],
		edges: EntProductEdgesToJSON(value["edges"]),
		height: value["height"],
		id: value["id"],
		length: value["length"],
		name: value["name"],
		price: value["price"],
		product_images: value["productImages"],
		reference: value["reference"],
		status: ProductStatusToJSON(value["status"]),
		stock_quantity: value["stockQuantity"],
		updated_at: value["updatedAt"],
		vendor_id: value["vendorId"],
		weight: value["weight"],
		width: value["width"]
	};
}
