/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { SchemaRole } from "./SchemaRole";
import {
	SchemaRoleFromJSON,
	SchemaRoleFromJSONTyped,
	SchemaRoleToJSON,
	SchemaRoleToJSONTyped
} from "./SchemaRole";
import type { EntUserEdges } from "./EntUserEdges";
import {
	EntUserEdgesFromJSON,
	EntUserEdgesFromJSONTyped,
	EntUserEdgesToJSON,
	EntUserEdgesToJSONTyped
} from "./EntUserEdges";
import type { UserStatus } from "./UserStatus";
import {
	UserStatusFromJSON,
	UserStatusFromJSONTyped,
	UserStatusToJSON,
	UserStatusToJSONTyped
} from "./UserStatus";

/**
 *
 * @export
 * @interface EntUser
 */
export interface EntUser {
	/**
	 * CreatedAt holds the value of the "created_at" field.
	 * @type {string}
	 * @memberof EntUser
	 */
	createdAt?: string;
	/**
	 * Edges holds the relations/edges for other nodes in the graph.
	 * The values are being populated by the UserQuery when eager-loading is set.
	 * @type {EntUserEdges}
	 * @memberof EntUser
	 */
	edges?: EntUserEdges;
	/**
	 * Email holds the value of the "email" field.
	 * @type {string}
	 * @memberof EntUser
	 */
	email?: string;
	/**
	 * EmailVerified holds the value of the "email_verified" field.
	 * @type {boolean}
	 * @memberof EntUser
	 */
	emailVerified?: boolean;
	/**
	 * FirstName holds the value of the "first_name" field.
	 * @type {string}
	 * @memberof EntUser
	 */
	firstName?: string;
	/**
	 * ID of the ent.
	 * @type {string}
	 * @memberof EntUser
	 */
	id?: string;
	/**
	 * LastLogin holds the value of the "last_login" field.
	 * @type {string}
	 * @memberof EntUser
	 */
	lastLogin?: string;
	/**
	 * LastName holds the value of the "last_name" field.
	 * @type {string}
	 * @memberof EntUser
	 */
	lastName?: string;
	/**
	 * PasswordHash holds the value of the "password_hash" field.
	 * @type {string}
	 * @memberof EntUser
	 */
	passwordHash?: string;
	/**
	 * Phone holds the value of the "phone" field.
	 * @type {string}
	 * @memberof EntUser
	 */
	phone?: string;
	/**
	 * PhoneVerified holds the value of the "phone_verified" field.
	 * @type {boolean}
	 * @memberof EntUser
	 */
	phoneVerified?: boolean;
	/**
	 * Role holds the value of the "role" field.
	 * @type {SchemaRole}
	 * @memberof EntUser
	 */
	role?: SchemaRole;
	/**
	 * Status holds the value of the "status" field.
	 * @type {UserStatus}
	 * @memberof EntUser
	 */
	status?: UserStatus;
	/**
	 * UpdatedAt holds the value of the "updated_at" field.
	 * @type {string}
	 * @memberof EntUser
	 */
	updatedAt?: string;
}

/**
 * Check if a given object implements the EntUser interface.
 */
export function instanceOfEntUser(value: object): value is EntUser {
	return true;
}

export function EntUserFromJSON(json: any): EntUser {
	return EntUserFromJSONTyped(json, false);
}

export function EntUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntUser {
	if (json == null) {
		return json;
	}
	return {
		createdAt: json["created_at"] == null ? undefined : json["created_at"],
		edges: json["edges"] == null ? undefined : EntUserEdgesFromJSON(json["edges"]),
		email: json["email"] == null ? undefined : json["email"],
		emailVerified: json["email_verified"] == null ? undefined : json["email_verified"],
		firstName: json["first_name"] == null ? undefined : json["first_name"],
		id: json["id"] == null ? undefined : json["id"],
		lastLogin: json["last_login"] == null ? undefined : json["last_login"],
		lastName: json["last_name"] == null ? undefined : json["last_name"],
		passwordHash: json["password_hash"] == null ? undefined : json["password_hash"],
		phone: json["phone"] == null ? undefined : json["phone"],
		phoneVerified: json["phone_verified"] == null ? undefined : json["phone_verified"],
		role: json["role"] == null ? undefined : SchemaRoleFromJSON(json["role"]),
		status: json["status"] == null ? undefined : UserStatusFromJSON(json["status"]),
		updatedAt: json["updated_at"] == null ? undefined : json["updated_at"]
	};
}

export function EntUserToJSON(json: any): EntUser {
	return EntUserToJSONTyped(json, false);
}

export function EntUserToJSONTyped(
	value?: EntUser | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		created_at: value["createdAt"],
		edges: EntUserEdgesToJSON(value["edges"]),
		email: value["email"],
		email_verified: value["emailVerified"],
		first_name: value["firstName"],
		id: value["id"],
		last_login: value["lastLogin"],
		last_name: value["lastName"],
		password_hash: value["passwordHash"],
		phone: value["phone"],
		phone_verified: value["phoneVerified"],
		role: SchemaRoleToJSON(value["role"]),
		status: UserStatusToJSON(value["status"]),
		updated_at: value["updatedAt"]
	};
}
