/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { EntClientProfile } from "./EntClientProfile";
import {
	EntClientProfileFromJSON,
	EntClientProfileFromJSONTyped,
	EntClientProfileToJSON,
	EntClientProfileToJSONTyped
} from "./EntClientProfile";
import type { EntCourierProfile } from "./EntCourierProfile";
import {
	EntCourierProfileFromJSON,
	EntCourierProfileFromJSONTyped,
	EntCourierProfileToJSON,
	EntCourierProfileToJSONTyped
} from "./EntCourierProfile";
import type { EntVendorProfile } from "./EntVendorProfile";
import {
	EntVendorProfileFromJSON,
	EntVendorProfileFromJSONTyped,
	EntVendorProfileToJSON,
	EntVendorProfileToJSONTyped
} from "./EntVendorProfile";

/**
 *
 * @export
 * @interface EntUserEdges
 */
export interface EntUserEdges {
	/**
	 * ClientProfile holds the value of the client_profile edge.
	 * @type {EntClientProfile}
	 * @memberof EntUserEdges
	 */
	clientProfile?: EntClientProfile;
	/**
	 * CourierProfile holds the value of the courier_profile edge.
	 * @type {EntCourierProfile}
	 * @memberof EntUserEdges
	 */
	courierProfile?: EntCourierProfile;
	/**
	 * VendorProfile holds the value of the vendor_profile edge.
	 * @type {EntVendorProfile}
	 * @memberof EntUserEdges
	 */
	vendorProfile?: EntVendorProfile;
}

/**
 * Check if a given object implements the EntUserEdges interface.
 */
export function instanceOfEntUserEdges(value: object): value is EntUserEdges {
	return true;
}

export function EntUserEdgesFromJSON(json: any): EntUserEdges {
	return EntUserEdgesFromJSONTyped(json, false);
}

export function EntUserEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntUserEdges {
	if (json == null) {
		return json;
	}
	return {
		clientProfile:
			json["client_profile"] == null ? undefined : EntClientProfileFromJSON(json["client_profile"]),
		courierProfile:
			json["courier_profile"] == null
				? undefined
				: EntCourierProfileFromJSON(json["courier_profile"]),
		vendorProfile:
			json["vendor_profile"] == null ? undefined : EntVendorProfileFromJSON(json["vendor_profile"])
	};
}

export function EntUserEdgesToJSON(json: any): EntUserEdges {
	return EntUserEdgesToJSONTyped(json, false);
}

export function EntUserEdgesToJSONTyped(
	value?: EntUserEdges | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		client_profile: EntClientProfileToJSON(value["clientProfile"]),
		courier_profile: EntCourierProfileToJSON(value["courierProfile"]),
		vendor_profile: EntVendorProfileToJSON(value["vendorProfile"])
	};
}
