/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { EntCourierProfile } from "./EntCourierProfile";
import {
	EntCourierProfileFromJSON,
	EntCourierProfileFromJSONTyped,
	EntCourierProfileToJSON,
	EntCourierProfileToJSONTyped
} from "./EntCourierProfile";

/**
 *
 * @export
 * @interface EntVehicleTypeEdges
 */
export interface EntVehicleTypeEdges {
	/**
	 * CourierProfiles holds the value of the courier_profiles edge.
	 * @type {Array<EntCourierProfile>}
	 * @memberof EntVehicleTypeEdges
	 */
	courierProfiles?: Array<EntCourierProfile>;
}

/**
 * Check if a given object implements the EntVehicleTypeEdges interface.
 */
export function instanceOfEntVehicleTypeEdges(value: object): value is EntVehicleTypeEdges {
	return true;
}

export function EntVehicleTypeEdgesFromJSON(json: any): EntVehicleTypeEdges {
	return EntVehicleTypeEdgesFromJSONTyped(json, false);
}

export function EntVehicleTypeEdgesFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): EntVehicleTypeEdges {
	if (json == null) {
		return json;
	}
	return {
		courierProfiles:
			json["courier_profiles"] == null
				? undefined
				: (json["courier_profiles"] as Array<any>).map(EntCourierProfileFromJSON)
	};
}

export function EntVehicleTypeEdgesToJSON(json: any): EntVehicleTypeEdges {
	return EntVehicleTypeEdgesToJSONTyped(json, false);
}

export function EntVehicleTypeEdgesToJSONTyped(
	value?: EntVehicleTypeEdges | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		courier_profiles:
			value["courierProfiles"] == null
				? undefined
				: (value["courierProfiles"] as Array<any>).map(EntCourierProfileToJSON)
	};
}
