/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { EntProduct } from "./EntProduct";
import {
	EntProductFromJSON,
	EntProductFromJSONTyped,
	EntProductToJSON,
	EntProductToJSONTyped
} from "./EntProduct";
import type { EntUser } from "./EntUser";
import {
	EntUserFromJSON,
	EntUserFromJSONTyped,
	EntUserToJSON,
	EntUserToJSONTyped
} from "./EntUser";

/**
 *
 * @export
 * @interface EntVendorProfileEdges
 */
export interface EntVendorProfileEdges {
	/**
	 * Products holds the value of the products edge.
	 * @type {Array<EntProduct>}
	 * @memberof EntVendorProfileEdges
	 */
	products?: Array<EntProduct>;
	/**
	 * User holds the value of the user edge.
	 * @type {EntUser}
	 * @memberof EntVendorProfileEdges
	 */
	user?: EntUser;
}

/**
 * Check if a given object implements the EntVendorProfileEdges interface.
 */
export function instanceOfEntVendorProfileEdges(value: object): value is EntVendorProfileEdges {
	return true;
}

export function EntVendorProfileEdgesFromJSON(json: any): EntVendorProfileEdges {
	return EntVendorProfileEdgesFromJSONTyped(json, false);
}

export function EntVendorProfileEdgesFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): EntVendorProfileEdges {
	if (json == null) {
		return json;
	}
	return {
		products:
			json["products"] == null
				? undefined
				: (json["products"] as Array<any>).map(EntProductFromJSON),
		user: json["user"] == null ? undefined : EntUserFromJSON(json["user"])
	};
}

export function EntVendorProfileEdgesToJSON(json: any): EntVendorProfileEdges {
	return EntVendorProfileEdgesToJSONTyped(json, false);
}

export function EntVendorProfileEdgesToJSONTyped(
	value?: EntVendorProfileEdges | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		products:
			value["products"] == null
				? undefined
				: (value["products"] as Array<any>).map(EntProductToJSON),
		user: EntUserToJSON(value["user"])
	};
}
