/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { SchemaBusinessDay } from "./SchemaBusinessDay";
import {
	SchemaBusinessDayFromJSON,
	SchemaBusinessDayFromJSONTyped,
	SchemaBusinessDayToJSON,
	SchemaBusinessDayToJSONTyped
} from "./SchemaBusinessDay";
import type { EntVendorProfileEdges } from "./EntVendorProfileEdges";
import {
	EntVendorProfileEdgesFromJSON,
	EntVendorProfileEdgesFromJSONTyped,
	EntVendorProfileEdgesToJSON,
	EntVendorProfileEdgesToJSONTyped
} from "./EntVendorProfileEdges";
import type { VendorprofileStatus } from "./VendorprofileStatus";
import {
	VendorprofileStatusFromJSON,
	VendorprofileStatusFromJSONTyped,
	VendorprofileStatusToJSON,
	VendorprofileStatusToJSONTyped
} from "./VendorprofileStatus";

/**
 *
 * @export
 * @interface EntVendorProfile
 */
export interface EntVendorProfile {
	/**
	 * Address holds the value of the "address" field.
	 * @type {string}
	 * @memberof EntVendorProfile
	 */
	address?: string;
	/**
	 * BusinessDays holds the value of the "business_days" field.
	 * @type {Array<SchemaBusinessDay>}
	 * @memberof EntVendorProfile
	 */
	businessDays?: Array<SchemaBusinessDay>;
	/**
	 * BusinessName holds the value of the "business_name" field.
	 * @type {string}
	 * @memberof EntVendorProfile
	 */
	businessName?: string;
	/**
	 * City holds the value of the "city" field.
	 * @type {string}
	 * @memberof EntVendorProfile
	 */
	city?: string;
	/**
	 * CreatedAt holds the value of the "created_at" field.
	 * @type {string}
	 * @memberof EntVendorProfile
	 */
	createdAt?: string;
	/**
	 * Description holds the value of the "description" field.
	 * @type {string}
	 * @memberof EntVendorProfile
	 */
	description?: string;
	/**
	 * Edges holds the relations/edges for other nodes in the graph.
	 * The values are being populated by the VendorProfileQuery when eager-loading is set.
	 * @type {EntVendorProfileEdges}
	 * @memberof EntVendorProfile
	 */
	edges?: EntVendorProfileEdges;
	/**
	 * ID of the ent.
	 * @type {string}
	 * @memberof EntVendorProfile
	 */
	id?: string;
	/**
	 * IdentityCardS3 holds the value of the "identity_card_s3" field.
	 * @type {string}
	 * @memberof EntVendorProfile
	 */
	identityCardS3?: string;
	/**
	 * InsuranceS3 holds the value of the "insurance_s3" field.
	 * @type {string}
	 * @memberof EntVendorProfile
	 */
	insuranceS3?: string;
	/**
	 * KbisS3 holds the value of the "kbis_s3" field.
	 * @type {string}
	 * @memberof EntVendorProfile
	 */
	kbisS3?: string;
	/**
	 * Latitude holds the value of the "latitude" field.
	 * @type {number}
	 * @memberof EntVendorProfile
	 */
	latitude?: number;
	/**
	 * Longitude holds the value of the "longitude" field.
	 * @type {number}
	 * @memberof EntVendorProfile
	 */
	longitude?: number;
	/**
	 * MinOrderAmount holds the value of the "min_order_amount" field.
	 * @type {number}
	 * @memberof EntVendorProfile
	 */
	minOrderAmount?: number;
	/**
	 * PostalCode holds the value of the "postal_code" field.
	 * @type {string}
	 * @memberof EntVendorProfile
	 */
	postalCode?: string;
	/**
	 * PreparationTimeMinutes holds the value of the "preparation_time_minutes" field.
	 * @type {number}
	 * @memberof EntVendorProfile
	 */
	preparationTimeMinutes?: number;
	/**
	 * Siret holds the value of the "siret" field.
	 * @type {string}
	 * @memberof EntVendorProfile
	 */
	siret?: string;
	/**
	 * Status holds the value of the "status" field.
	 * @type {VendorprofileStatus}
	 * @memberof EntVendorProfile
	 */
	status?: VendorprofileStatus;
	/**
	 * StripeAccountID holds the value of the "stripe_account_id" field.
	 * @type {string}
	 * @memberof EntVendorProfile
	 */
	stripeAccountId?: string;
	/**
	 * StripeActive holds the value of the "stripe_active" field.
	 * @type {boolean}
	 * @memberof EntVendorProfile
	 */
	stripeActive?: boolean;
	/**
	 * Timezone holds the value of the "timezone" field.
	 * @type {string}
	 * @memberof EntVendorProfile
	 */
	timezone?: string;
	/**
	 * UpdatedAt holds the value of the "updated_at" field.
	 * @type {string}
	 * @memberof EntVendorProfile
	 */
	updatedAt?: string;
	/**
	 * UserID holds the value of the "user_id" field.
	 * @type {string}
	 * @memberof EntVendorProfile
	 */
	userId?: string;
}

/**
 * Check if a given object implements the EntVendorProfile interface.
 */
export function instanceOfEntVendorProfile(value: object): value is EntVendorProfile {
	return true;
}

export function EntVendorProfileFromJSON(json: any): EntVendorProfile {
	return EntVendorProfileFromJSONTyped(json, false);
}

export function EntVendorProfileFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): EntVendorProfile {
	if (json == null) {
		return json;
	}
	return {
		address: json["address"] == null ? undefined : json["address"],
		businessDays:
			json["business_days"] == null
				? undefined
				: (json["business_days"] as Array<any>).map(SchemaBusinessDayFromJSON),
		businessName: json["business_name"] == null ? undefined : json["business_name"],
		city: json["city"] == null ? undefined : json["city"],
		createdAt: json["created_at"] == null ? undefined : json["created_at"],
		description: json["description"] == null ? undefined : json["description"],
		edges: json["edges"] == null ? undefined : EntVendorProfileEdgesFromJSON(json["edges"]),
		id: json["id"] == null ? undefined : json["id"],
		identityCardS3: json["identity_card_s3"] == null ? undefined : json["identity_card_s3"],
		insuranceS3: json["insurance_s3"] == null ? undefined : json["insurance_s3"],
		kbisS3: json["kbis_s3"] == null ? undefined : json["kbis_s3"],
		latitude: json["latitude"] == null ? undefined : json["latitude"],
		longitude: json["longitude"] == null ? undefined : json["longitude"],
		minOrderAmount: json["min_order_amount"] == null ? undefined : json["min_order_amount"],
		postalCode: json["postal_code"] == null ? undefined : json["postal_code"],
		preparationTimeMinutes:
			json["preparation_time_minutes"] == null ? undefined : json["preparation_time_minutes"],
		siret: json["siret"] == null ? undefined : json["siret"],
		status: json["status"] == null ? undefined : VendorprofileStatusFromJSON(json["status"]),
		stripeAccountId: json["stripe_account_id"] == null ? undefined : json["stripe_account_id"],
		stripeActive: json["stripe_active"] == null ? undefined : json["stripe_active"],
		timezone: json["timezone"] == null ? undefined : json["timezone"],
		updatedAt: json["updated_at"] == null ? undefined : json["updated_at"],
		userId: json["user_id"] == null ? undefined : json["user_id"]
	};
}

export function EntVendorProfileToJSON(json: any): EntVendorProfile {
	return EntVendorProfileToJSONTyped(json, false);
}

export function EntVendorProfileToJSONTyped(
	value?: EntVendorProfile | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		address: value["address"],
		business_days:
			value["businessDays"] == null
				? undefined
				: (value["businessDays"] as Array<any>).map(SchemaBusinessDayToJSON),
		business_name: value["businessName"],
		city: value["city"],
		created_at: value["createdAt"],
		description: value["description"],
		edges: EntVendorProfileEdgesToJSON(value["edges"]),
		id: value["id"],
		identity_card_s3: value["identityCardS3"],
		insurance_s3: value["insuranceS3"],
		kbis_s3: value["kbisS3"],
		latitude: value["latitude"],
		longitude: value["longitude"],
		min_order_amount: value["minOrderAmount"],
		postal_code: value["postalCode"],
		preparation_time_minutes: value["preparationTimeMinutes"],
		siret: value["siret"],
		status: VendorprofileStatusToJSON(value["status"]),
		stripe_account_id: value["stripeAccountId"],
		stripe_active: value["stripeActive"],
		timezone: value["timezone"],
		updated_at: value["updatedAt"],
		user_id: value["userId"]
	};
}
