/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { EntVehicleTypeEdges } from "./EntVehicleTypeEdges";
import {
	EntVehicleTypeEdgesFromJSON,
	EntVehicleTypeEdgesFromJSONTyped,
	EntVehicleTypeEdgesToJSON,
	EntVehicleTypeEdgesToJSONTyped
} from "./EntVehicleTypeEdges";

/**
 *
 * @export
 * @interface EntVehicleType
 */
export interface EntVehicleType {
	/**
	 * Edges holds the relations/edges for other nodes in the graph.
	 * The values are being populated by the VehicleTypeQuery when eager-loading is set.
	 * @type {EntVehicleTypeEdges}
	 * @memberof EntVehicleType
	 */
	edges?: EntVehicleTypeEdges;
	/**
	 * ID of the ent.
	 * @type {number}
	 * @memberof EntVehicleType
	 */
	id?: number;
	/**
	 * Label holds the value of the "label" field.
	 * @type {string}
	 * @memberof EntVehicleType
	 */
	label?: string;
	/**
	 * MaxDistanceKm holds the value of the "max_distance_km" field.
	 * @type {number}
	 * @memberof EntVehicleType
	 */
	maxDistanceKm?: number;
	/**
	 * MaxHeightCm holds the value of the "max_height_cm" field.
	 * @type {number}
	 * @memberof EntVehicleType
	 */
	maxHeightCm?: number;
	/**
	 * MaxLengthCm holds the value of the "max_length_cm" field.
	 * @type {number}
	 * @memberof EntVehicleType
	 */
	maxLengthCm?: number;
	/**
	 * MaxWeightKg holds the value of the "max_weight_kg" field.
	 * @type {number}
	 * @memberof EntVehicleType
	 */
	maxWeightKg?: number;
	/**
	 * MaxWidthCm holds the value of the "max_width_cm" field.
	 * @type {number}
	 * @memberof EntVehicleType
	 */
	maxWidthCm?: number;
	/**
	 * NeedsDocuments holds the value of the "needs_documents" field.
	 * @type {boolean}
	 * @memberof EntVehicleType
	 */
	needsDocuments?: boolean;
}

/**
 * Check if a given object implements the EntVehicleType interface.
 */
export function instanceOfEntVehicleType(value: object): value is EntVehicleType {
	return true;
}

export function EntVehicleTypeFromJSON(json: any): EntVehicleType {
	return EntVehicleTypeFromJSONTyped(json, false);
}

export function EntVehicleTypeFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): EntVehicleType {
	if (json == null) {
		return json;
	}
	return {
		edges: json["edges"] == null ? undefined : EntVehicleTypeEdgesFromJSON(json["edges"]),
		id: json["id"] == null ? undefined : json["id"],
		label: json["label"] == null ? undefined : json["label"],
		maxDistanceKm: json["max_distance_km"] == null ? undefined : json["max_distance_km"],
		maxHeightCm: json["max_height_cm"] == null ? undefined : json["max_height_cm"],
		maxLengthCm: json["max_length_cm"] == null ? undefined : json["max_length_cm"],
		maxWeightKg: json["max_weight_kg"] == null ? undefined : json["max_weight_kg"],
		maxWidthCm: json["max_width_cm"] == null ? undefined : json["max_width_cm"],
		needsDocuments: json["needs_documents"] == null ? undefined : json["needs_documents"]
	};
}

export function EntVehicleTypeToJSON(json: any): EntVehicleType {
	return EntVehicleTypeToJSONTyped(json, false);
}

export function EntVehicleTypeToJSONTyped(
	value?: EntVehicleType | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		edges: EntVehicleTypeEdgesToJSON(value["edges"]),
		id: value["id"],
		label: value["label"],
		max_distance_km: value["maxDistanceKm"],
		max_height_cm: value["maxHeightCm"],
		max_length_cm: value["maxLengthCm"],
		max_weight_kg: value["maxWeightKg"],
		max_width_cm: value["maxWidthCm"],
		needs_documents: value["needsDocuments"]
	};
}
