/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface HttputilsSuccessResponse
 */
export interface HttputilsSuccessResponse {
	/**
	 *
	 * @type {string}
	 * @memberof HttputilsSuccessResponse
	 */
	message?: string;
}

/**
 * Check if a given object implements the HttputilsSuccessResponse interface.
 */
export function instanceOfHttputilsSuccessResponse(
	value: object
): value is HttputilsSuccessResponse {
	return true;
}

export function HttputilsSuccessResponseFromJSON(json: any): HttputilsSuccessResponse {
	return HttputilsSuccessResponseFromJSONTyped(json, false);
}

export function HttputilsSuccessResponseFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): HttputilsSuccessResponse {
	if (json == null) {
		return json;
	}
	return {
		message: json["message"] == null ? undefined : json["message"]
	};
}

export function HttputilsSuccessResponseToJSON(json: any): HttputilsSuccessResponse {
	return HttputilsSuccessResponseToJSONTyped(json, false);
}

export function HttputilsSuccessResponseToJSONTyped(
	value?: HttputilsSuccessResponse | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		message: value["message"]
	};
}
