/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface HttputilsErrorResponse
 */
export interface HttputilsErrorResponse {
	/**
	 *
	 * @type {number}
	 * @memberof HttputilsErrorResponse
	 */
	code?: number;
	/**
	 *
	 * @type {string}
	 * @memberof HttputilsErrorResponse
	 */
	message?: string;
}

/**
 * Check if a given object implements the HttputilsErrorResponse interface.
 */
export function instanceOfHttputilsErrorResponse(value: object): value is HttputilsErrorResponse {
	return true;
}

export function HttputilsErrorResponseFromJSON(json: any): HttputilsErrorResponse {
	return HttputilsErrorResponseFromJSONTyped(json, false);
}

export function HttputilsErrorResponseFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): HttputilsErrorResponse {
	if (json == null) {
		return json;
	}
	return {
		code: json["code"] == null ? undefined : json["code"],
		message: json["message"] == null ? undefined : json["message"]
	};
}

export function HttputilsErrorResponseToJSON(json: any): HttputilsErrorResponse {
	return HttputilsErrorResponseToJSONTyped(json, false);
}

export function HttputilsErrorResponseToJSONTyped(
	value?: HttputilsErrorResponse | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		code: value["code"],
		message: value["message"]
	};
}
