/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface RoutesRegisterRequest
 */
export interface RoutesRegisterRequest {
	/**
	 *
	 * @type {string}
	 * @memberof RoutesRegisterRequest
	 */
	email: string;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesRegisterRequest
	 */
	firstName?: string;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesRegisterRequest
	 */
	lastName?: string;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesRegisterRequest
	 */
	password: string;
	/**
	 * E.164 format (e.g., +1234567890), optional
	 * @type {string}
	 * @memberof RoutesRegisterRequest
	 */
	phone?: string;
}

/**
 * Check if a given object implements the RoutesRegisterRequest interface.
 */
export function instanceOfRoutesRegisterRequest(value: object): value is RoutesRegisterRequest {
	if (!("email" in value) || value["email"] === undefined) return false;
	if (!("password" in value) || value["password"] === undefined) return false;
	return true;
}

export function RoutesRegisterRequestFromJSON(json: any): RoutesRegisterRequest {
	return RoutesRegisterRequestFromJSONTyped(json, false);
}

export function RoutesRegisterRequestFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): RoutesRegisterRequest {
	if (json == null) {
		return json;
	}
	return {
		email: json["email"],
		firstName: json["first_name"] == null ? undefined : json["first_name"],
		lastName: json["last_name"] == null ? undefined : json["last_name"],
		password: json["password"],
		phone: json["phone"] == null ? undefined : json["phone"]
	};
}

export function RoutesRegisterRequestToJSON(json: any): RoutesRegisterRequest {
	return RoutesRegisterRequestToJSONTyped(json, false);
}

export function RoutesRegisterRequestToJSONTyped(
	value?: RoutesRegisterRequest | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		email: value["email"],
		first_name: value["firstName"],
		last_name: value["lastName"],
		password: value["password"],
		phone: value["phone"]
	};
}
