/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { RoutesProductResponse } from "./RoutesProductResponse";
import {
	RoutesProductResponseFromJSON,
	RoutesProductResponseFromJSONTyped,
	RoutesProductResponseToJSON,
	RoutesProductResponseToJSONTyped
} from "./RoutesProductResponse";

/**
 *
 * @export
 * @interface RoutesVendorProductListResponse
 */
export interface RoutesVendorProductListResponse {
	/**
	 *
	 * @type {boolean}
	 * @memberof RoutesVendorProductListResponse
	 */
	hasMore?: boolean;
	/**
	 *
	 * @type {number}
	 * @memberof RoutesVendorProductListResponse
	 */
	limit?: number;
	/**
	 *
	 * @type {number}
	 * @memberof RoutesVendorProductListResponse
	 */
	page?: number;
	/**
	 *
	 * @type {Array<RoutesProductResponse>}
	 * @memberof RoutesVendorProductListResponse
	 */
	products?: Array<RoutesProductResponse>;
	/**
	 *
	 * @type {number}
	 * @memberof RoutesVendorProductListResponse
	 */
	total?: number;
}

/**
 * Check if a given object implements the RoutesVendorProductListResponse interface.
 */
export function instanceOfRoutesVendorProductListResponse(
	value: object
): value is RoutesVendorProductListResponse {
	return true;
}

export function RoutesVendorProductListResponseFromJSON(
	json: any
): RoutesVendorProductListResponse {
	return RoutesVendorProductListResponseFromJSONTyped(json, false);
}

export function RoutesVendorProductListResponseFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): RoutesVendorProductListResponse {
	if (json == null) {
		return json;
	}
	return {
		hasMore: json["has_more"] == null ? undefined : json["has_more"],
		limit: json["limit"] == null ? undefined : json["limit"],
		page: json["page"] == null ? undefined : json["page"],
		products:
			json["products"] == null
				? undefined
				: (json["products"] as Array<any>).map(RoutesProductResponseFromJSON),
		total: json["total"] == null ? undefined : json["total"]
	};
}

export function RoutesVendorProductListResponseToJSON(json: any): RoutesVendorProductListResponse {
	return RoutesVendorProductListResponseToJSONTyped(json, false);
}

export function RoutesVendorProductListResponseToJSONTyped(
	value?: RoutesVendorProductListResponse | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		has_more: value["hasMore"],
		limit: value["limit"],
		page: value["page"],
		products:
			value["products"] == null
				? undefined
				: (value["products"] as Array<any>).map(RoutesProductResponseToJSON),
		total: value["total"]
	};
}
