/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface RoutesVerifyPasswordResetResponse
 */
export interface RoutesVerifyPasswordResetResponse {
	/**
	 *
	 * @type {string}
	 * @memberof RoutesVerifyPasswordResetResponse
	 */
	message?: string;
}

/**
 * Check if a given object implements the RoutesVerifyPasswordResetResponse interface.
 */
export function instanceOfRoutesVerifyPasswordResetResponse(
	value: object
): value is RoutesVerifyPasswordResetResponse {
	return true;
}

export function RoutesVerifyPasswordResetResponseFromJSON(
	json: any
): RoutesVerifyPasswordResetResponse {
	return RoutesVerifyPasswordResetResponseFromJSONTyped(json, false);
}

export function RoutesVerifyPasswordResetResponseFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): RoutesVerifyPasswordResetResponse {
	if (json == null) {
		return json;
	}
	return {
		message: json["message"] == null ? undefined : json["message"]
	};
}

export function RoutesVerifyPasswordResetResponseToJSON(
	json: any
): RoutesVerifyPasswordResetResponse {
	return RoutesVerifyPasswordResetResponseToJSONTyped(json, false);
}

export function RoutesVerifyPasswordResetResponseToJSONTyped(
	value?: RoutesVerifyPasswordResetResponse | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		message: value["message"]
	};
}
