/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface RoutesUpdateProductRequest
 */
export interface RoutesUpdateProductRequest {
	/**
	 *
	 * @type {string}
	 * @memberof RoutesUpdateProductRequest
	 */
	categoryId?: string;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesUpdateProductRequest
	 */
	description?: string;
	/**
	 *
	 * @type {number}
	 * @memberof RoutesUpdateProductRequest
	 */
	height?: number;
	/**
	 *
	 * @type {number}
	 * @memberof RoutesUpdateProductRequest
	 */
	length?: number;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesUpdateProductRequest
	 */
	name?: string;
	/**
	 *
	 * @type {number}
	 * @memberof RoutesUpdateProductRequest
	 */
	price?: number;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesUpdateProductRequest
	 */
	reference?: string;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesUpdateProductRequest
	 */
	status?: string;
	/**
	 *
	 * @type {number}
	 * @memberof RoutesUpdateProductRequest
	 */
	stockQuantity?: number;
	/**
	 *
	 * @type {number}
	 * @memberof RoutesUpdateProductRequest
	 */
	weight?: number;
	/**
	 *
	 * @type {number}
	 * @memberof RoutesUpdateProductRequest
	 */
	width?: number;
}

/**
 * Check if a given object implements the RoutesUpdateProductRequest interface.
 */
export function instanceOfRoutesUpdateProductRequest(
	value: object
): value is RoutesUpdateProductRequest {
	return true;
}

export function RoutesUpdateProductRequestFromJSON(json: any): RoutesUpdateProductRequest {
	return RoutesUpdateProductRequestFromJSONTyped(json, false);
}

export function RoutesUpdateProductRequestFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): RoutesUpdateProductRequest {
	if (json == null) {
		return json;
	}
	return {
		categoryId: json["category_id"] == null ? undefined : json["category_id"],
		description: json["description"] == null ? undefined : json["description"],
		height: json["height"] == null ? undefined : json["height"],
		length: json["length"] == null ? undefined : json["length"],
		name: json["name"] == null ? undefined : json["name"],
		price: json["price"] == null ? undefined : json["price"],
		reference: json["reference"] == null ? undefined : json["reference"],
		status: json["status"] == null ? undefined : json["status"],
		stockQuantity: json["stock_quantity"] == null ? undefined : json["stock_quantity"],
		weight: json["weight"] == null ? undefined : json["weight"],
		width: json["width"] == null ? undefined : json["width"]
	};
}

export function RoutesUpdateProductRequestToJSON(json: any): RoutesUpdateProductRequest {
	return RoutesUpdateProductRequestToJSONTyped(json, false);
}

export function RoutesUpdateProductRequestToJSONTyped(
	value?: RoutesUpdateProductRequest | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		category_id: value["categoryId"],
		description: value["description"],
		height: value["height"],
		length: value["length"],
		name: value["name"],
		price: value["price"],
		reference: value["reference"],
		status: value["status"],
		stock_quantity: value["stockQuantity"],
		weight: value["weight"],
		width: value["width"]
	};
}
