/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface RoutesVerifyEmailResponse
 */
export interface RoutesVerifyEmailResponse {
	/**
	 *
	 * @type {string}
	 * @memberof RoutesVerifyEmailResponse
	 */
	message?: string;
}

/**
 * Check if a given object implements the RoutesVerifyEmailResponse interface.
 */
export function instanceOfRoutesVerifyEmailResponse(
	value: object
): value is RoutesVerifyEmailResponse {
	return true;
}

export function RoutesVerifyEmailResponseFromJSON(json: any): RoutesVerifyEmailResponse {
	return RoutesVerifyEmailResponseFromJSONTyped(json, false);
}

export function RoutesVerifyEmailResponseFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): RoutesVerifyEmailResponse {
	if (json == null) {
		return json;
	}
	return {
		message: json["message"] == null ? undefined : json["message"]
	};
}

export function RoutesVerifyEmailResponseToJSON(json: any): RoutesVerifyEmailResponse {
	return RoutesVerifyEmailResponseToJSONTyped(json, false);
}

export function RoutesVerifyEmailResponseToJSONTyped(
	value?: RoutesVerifyEmailResponse | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		message: value["message"]
	};
}
