/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface RoutesOnboardingStatusResponse
 */
export interface RoutesOnboardingStatusResponse {
	/**
	 *
	 * @type {boolean}
	 * @memberof RoutesOnboardingStatusResponse
	 */
	canGenerateStripeLink?: boolean;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesOnboardingStatusResponse
	 */
	status?: string;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesOnboardingStatusResponse
	 */
	stripeAccountId?: string;
	/**
	 *
	 * @type {boolean}
	 * @memberof RoutesOnboardingStatusResponse
	 */
	stripeActive?: boolean;
}

/**
 * Check if a given object implements the RoutesOnboardingStatusResponse interface.
 */
export function instanceOfRoutesOnboardingStatusResponse(
	value: object
): value is RoutesOnboardingStatusResponse {
	return true;
}

export function RoutesOnboardingStatusResponseFromJSON(json: any): RoutesOnboardingStatusResponse {
	return RoutesOnboardingStatusResponseFromJSONTyped(json, false);
}

export function RoutesOnboardingStatusResponseFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): RoutesOnboardingStatusResponse {
	if (json == null) {
		return json;
	}
	return {
		canGenerateStripeLink:
			json["can_generate_stripe_link"] == null ? undefined : json["can_generate_stripe_link"],
		status: json["status"] == null ? undefined : json["status"],
		stripeAccountId: json["stripe_account_id"] == null ? undefined : json["stripe_account_id"],
		stripeActive: json["stripe_active"] == null ? undefined : json["stripe_active"]
	};
}

export function RoutesOnboardingStatusResponseToJSON(json: any): RoutesOnboardingStatusResponse {
	return RoutesOnboardingStatusResponseToJSONTyped(json, false);
}

export function RoutesOnboardingStatusResponseToJSONTyped(
	value?: RoutesOnboardingStatusResponse | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		can_generate_stripe_link: value["canGenerateStripeLink"],
		status: value["status"],
		stripe_account_id: value["stripeAccountId"],
		stripe_active: value["stripeActive"]
	};
}
