/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface RoutesVerifyPhoneResponse
 */
export interface RoutesVerifyPhoneResponse {
	/**
	 *
	 * @type {string}
	 * @memberof RoutesVerifyPhoneResponse
	 */
	message?: string;
}

/**
 * Check if a given object implements the RoutesVerifyPhoneResponse interface.
 */
export function instanceOfRoutesVerifyPhoneResponse(
	value: object
): value is RoutesVerifyPhoneResponse {
	return true;
}

export function RoutesVerifyPhoneResponseFromJSON(json: any): RoutesVerifyPhoneResponse {
	return RoutesVerifyPhoneResponseFromJSONTyped(json, false);
}

export function RoutesVerifyPhoneResponseFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): RoutesVerifyPhoneResponse {
	if (json == null) {
		return json;
	}
	return {
		message: json["message"] == null ? undefined : json["message"]
	};
}

export function RoutesVerifyPhoneResponseToJSON(json: any): RoutesVerifyPhoneResponse {
	return RoutesVerifyPhoneResponseToJSONTyped(json, false);
}

export function RoutesVerifyPhoneResponseToJSONTyped(
	value?: RoutesVerifyPhoneResponse | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		message: value["message"]
	};
}
