/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface RoutesVerifyPasswordResetRequest
 */
export interface RoutesVerifyPasswordResetRequest {
	/**
	 *
	 * @type {string}
	 * @memberof RoutesVerifyPasswordResetRequest
	 */
	newPassword: string;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesVerifyPasswordResetRequest
	 */
	token: string;
}

/**
 * Check if a given object implements the RoutesVerifyPasswordResetRequest interface.
 */
export function instanceOfRoutesVerifyPasswordResetRequest(
	value: object
): value is RoutesVerifyPasswordResetRequest {
	if (!("newPassword" in value) || value["newPassword"] === undefined) return false;
	if (!("token" in value) || value["token"] === undefined) return false;
	return true;
}

export function RoutesVerifyPasswordResetRequestFromJSON(
	json: any
): RoutesVerifyPasswordResetRequest {
	return RoutesVerifyPasswordResetRequestFromJSONTyped(json, false);
}

export function RoutesVerifyPasswordResetRequestFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): RoutesVerifyPasswordResetRequest {
	if (json == null) {
		return json;
	}
	return {
		newPassword: json["new_password"],
		token: json["token"]
	};
}

export function RoutesVerifyPasswordResetRequestToJSON(
	json: any
): RoutesVerifyPasswordResetRequest {
	return RoutesVerifyPasswordResetRequestToJSONTyped(json, false);
}

export function RoutesVerifyPasswordResetRequestToJSONTyped(
	value?: RoutesVerifyPasswordResetRequest | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		new_password: value["newPassword"],
		token: value["token"]
	};
}
