/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface RoutesVerifyPhoneRequest
 */
export interface RoutesVerifyPhoneRequest {
	/**
	 *
	 * @type {string}
	 * @memberof RoutesVerifyPhoneRequest
	 */
	code: string;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesVerifyPhoneRequest
	 */
	phone: string;
}

/**
 * Check if a given object implements the RoutesVerifyPhoneRequest interface.
 */
export function instanceOfRoutesVerifyPhoneRequest(
	value: object
): value is RoutesVerifyPhoneRequest {
	if (!("code" in value) || value["code"] === undefined) return false;
	if (!("phone" in value) || value["phone"] === undefined) return false;
	return true;
}

export function RoutesVerifyPhoneRequestFromJSON(json: any): RoutesVerifyPhoneRequest {
	return RoutesVerifyPhoneRequestFromJSONTyped(json, false);
}

export function RoutesVerifyPhoneRequestFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): RoutesVerifyPhoneRequest {
	if (json == null) {
		return json;
	}
	return {
		code: json["code"],
		phone: json["phone"]
	};
}

export function RoutesVerifyPhoneRequestToJSON(json: any): RoutesVerifyPhoneRequest {
	return RoutesVerifyPhoneRequestToJSONTyped(json, false);
}

export function RoutesVerifyPhoneRequestToJSONTyped(
	value?: RoutesVerifyPhoneRequest | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		code: value["code"],
		phone: value["phone"]
	};
}
