/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface RoutesSendEmailVerificationResponse
 */
export interface RoutesSendEmailVerificationResponse {
	/**
	 *
	 * @type {string}
	 * @memberof RoutesSendEmailVerificationResponse
	 */
	message?: string;
}

/**
 * Check if a given object implements the RoutesSendEmailVerificationResponse interface.
 */
export function instanceOfRoutesSendEmailVerificationResponse(
	value: object
): value is RoutesSendEmailVerificationResponse {
	return true;
}

export function RoutesSendEmailVerificationResponseFromJSON(
	json: any
): RoutesSendEmailVerificationResponse {
	return RoutesSendEmailVerificationResponseFromJSONTyped(json, false);
}

export function RoutesSendEmailVerificationResponseFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): RoutesSendEmailVerificationResponse {
	if (json == null) {
		return json;
	}
	return {
		message: json["message"] == null ? undefined : json["message"]
	};
}

export function RoutesSendEmailVerificationResponseToJSON(
	json: any
): RoutesSendEmailVerificationResponse {
	return RoutesSendEmailVerificationResponseToJSONTyped(json, false);
}

export function RoutesSendEmailVerificationResponseToJSONTyped(
	value?: RoutesSendEmailVerificationResponse | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		message: value["message"]
	};
}
