/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface RoutesProductImageResponse
 */
export interface RoutesProductImageResponse {
	/**
	 *
	 * @type {string}
	 * @memberof RoutesProductImageResponse
	 */
	url?: string;
}

/**
 * Check if a given object implements the RoutesProductImageResponse interface.
 */
export function instanceOfRoutesProductImageResponse(
	value: object
): value is RoutesProductImageResponse {
	return true;
}

export function RoutesProductImageResponseFromJSON(json: any): RoutesProductImageResponse {
	return RoutesProductImageResponseFromJSONTyped(json, false);
}

export function RoutesProductImageResponseFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): RoutesProductImageResponse {
	if (json == null) {
		return json;
	}
	return {
		url: json["url"] == null ? undefined : json["url"]
	};
}

export function RoutesProductImageResponseToJSON(json: any): RoutesProductImageResponse {
	return RoutesProductImageResponseToJSONTyped(json, false);
}

export function RoutesProductImageResponseToJSONTyped(
	value?: RoutesProductImageResponse | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		url: value["url"]
	};
}
