/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { SchemaBusinessDay } from "./SchemaBusinessDay";
import {
	SchemaBusinessDayFromJSON,
	SchemaBusinessDayFromJSONTyped,
	SchemaBusinessDayToJSON,
	SchemaBusinessDayToJSONTyped
} from "./SchemaBusinessDay";

/**
 *
 * @export
 * @interface RoutesVendorRegistrationRequest
 */
export interface RoutesVendorRegistrationRequest {
	/**
	 *
	 * @type {string}
	 * @memberof RoutesVendorRegistrationRequest
	 */
	address: string;
	/**
	 *
	 * @type {Array<SchemaBusinessDay>}
	 * @memberof RoutesVendorRegistrationRequest
	 */
	businessDays?: Array<SchemaBusinessDay>;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesVendorRegistrationRequest
	 */
	businessName: string;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesVendorRegistrationRequest
	 */
	city: string;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesVendorRegistrationRequest
	 */
	confirmPassword: string;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesVendorRegistrationRequest
	 */
	description?: string;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesVendorRegistrationRequest
	 */
	email: string;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesVendorRegistrationRequest
	 */
	firstName: string;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesVendorRegistrationRequest
	 */
	identityCard?: string;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesVendorRegistrationRequest
	 */
	insurance?: string;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesVendorRegistrationRequest
	 */
	kbis?: string;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesVendorRegistrationRequest
	 */
	lastName: string;
	/**
	 *
	 * @type {number}
	 * @memberof RoutesVendorRegistrationRequest
	 */
	minOrderAmount?: number;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesVendorRegistrationRequest
	 */
	password: string;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesVendorRegistrationRequest
	 */
	phone: string;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesVendorRegistrationRequest
	 */
	postalCode: string;
	/**
	 *
	 * @type {number}
	 * @memberof RoutesVendorRegistrationRequest
	 */
	preparationTimeMinutes?: number;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesVendorRegistrationRequest
	 */
	siret: string;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesVendorRegistrationRequest
	 */
	timezone?: string;
}

/**
 * Check if a given object implements the RoutesVendorRegistrationRequest interface.
 */
export function instanceOfRoutesVendorRegistrationRequest(
	value: object
): value is RoutesVendorRegistrationRequest {
	if (!("address" in value) || value["address"] === undefined) return false;
	if (!("businessName" in value) || value["businessName"] === undefined) return false;
	if (!("city" in value) || value["city"] === undefined) return false;
	if (!("confirmPassword" in value) || value["confirmPassword"] === undefined) return false;
	if (!("email" in value) || value["email"] === undefined) return false;
	if (!("firstName" in value) || value["firstName"] === undefined) return false;
	if (!("lastName" in value) || value["lastName"] === undefined) return false;
	if (!("password" in value) || value["password"] === undefined) return false;
	if (!("phone" in value) || value["phone"] === undefined) return false;
	if (!("postalCode" in value) || value["postalCode"] === undefined) return false;
	if (!("siret" in value) || value["siret"] === undefined) return false;
	return true;
}

export function RoutesVendorRegistrationRequestFromJSON(
	json: any
): RoutesVendorRegistrationRequest {
	return RoutesVendorRegistrationRequestFromJSONTyped(json, false);
}

export function RoutesVendorRegistrationRequestFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): RoutesVendorRegistrationRequest {
	if (json == null) {
		return json;
	}
	return {
		address: json["address"],
		businessDays:
			json["business_days"] == null
				? undefined
				: (json["business_days"] as Array<any>).map(SchemaBusinessDayFromJSON),
		businessName: json["business_name"],
		city: json["city"],
		confirmPassword: json["confirm_password"],
		description: json["description"] == null ? undefined : json["description"],
		email: json["email"],
		firstName: json["first_name"],
		identityCard: json["identity_card"] == null ? undefined : json["identity_card"],
		insurance: json["insurance"] == null ? undefined : json["insurance"],
		kbis: json["kbis"] == null ? undefined : json["kbis"],
		lastName: json["last_name"],
		minOrderAmount: json["min_order_amount"] == null ? undefined : json["min_order_amount"],
		password: json["password"],
		phone: json["phone"],
		postalCode: json["postal_code"],
		preparationTimeMinutes:
			json["preparation_time_minutes"] == null ? undefined : json["preparation_time_minutes"],
		siret: json["siret"],
		timezone: json["timezone"] == null ? undefined : json["timezone"]
	};
}

export function RoutesVendorRegistrationRequestToJSON(json: any): RoutesVendorRegistrationRequest {
	return RoutesVendorRegistrationRequestToJSONTyped(json, false);
}

export function RoutesVendorRegistrationRequestToJSONTyped(
	value?: RoutesVendorRegistrationRequest | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		address: value["address"],
		business_days:
			value["businessDays"] == null
				? undefined
				: (value["businessDays"] as Array<any>).map(SchemaBusinessDayToJSON),
		business_name: value["businessName"],
		city: value["city"],
		confirm_password: value["confirmPassword"],
		description: value["description"],
		email: value["email"],
		first_name: value["firstName"],
		identity_card: value["identityCard"],
		insurance: value["insurance"],
		kbis: value["kbis"],
		last_name: value["lastName"],
		min_order_amount: value["minOrderAmount"],
		password: value["password"],
		phone: value["phone"],
		postal_code: value["postalCode"],
		preparation_time_minutes: value["preparationTimeMinutes"],
		siret: value["siret"],
		timezone: value["timezone"]
	};
}
