/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { RoutesCategoryInfo } from "./RoutesCategoryInfo";
import {
	RoutesCategoryInfoFromJSON,
	RoutesCategoryInfoFromJSONTyped,
	RoutesCategoryInfoToJSON,
	RoutesCategoryInfoToJSONTyped
} from "./RoutesCategoryInfo";
import type { EntVendorProfile } from "./EntVendorProfile";
import {
	EntVendorProfileFromJSON,
	EntVendorProfileFromJSONTyped,
	EntVendorProfileToJSON,
	EntVendorProfileToJSONTyped
} from "./EntVendorProfile";

/**
 *
 * @export
 * @interface RoutesProductResponse
 */
export interface RoutesProductResponse {
	/**
	 *
	 * @type {RoutesCategoryInfo}
	 * @memberof RoutesProductResponse
	 */
	category?: RoutesCategoryInfo;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesProductResponse
	 */
	categoryId?: string;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesProductResponse
	 */
	createdAt?: string;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesProductResponse
	 */
	description?: string;
	/**
	 *
	 * @type {number}
	 * @memberof RoutesProductResponse
	 */
	height?: number;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesProductResponse
	 */
	id?: string;
	/**
	 *
	 * @type {number}
	 * @memberof RoutesProductResponse
	 */
	length?: number;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesProductResponse
	 */
	name?: string;
	/**
	 *
	 * @type {number}
	 * @memberof RoutesProductResponse
	 */
	price?: number;
	/**
	 *
	 * @type {Array<string>}
	 * @memberof RoutesProductResponse
	 */
	productImages?: Array<string>;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesProductResponse
	 */
	reference?: string;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesProductResponse
	 */
	status?: string;
	/**
	 *
	 * @type {number}
	 * @memberof RoutesProductResponse
	 */
	stockQuantity?: number;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesProductResponse
	 */
	updatedAt?: string;
	/**
	 *
	 * @type {EntVendorProfile}
	 * @memberof RoutesProductResponse
	 */
	vendor?: EntVendorProfile;
	/**
	 *
	 * @type {number}
	 * @memberof RoutesProductResponse
	 */
	weight?: number;
	/**
	 *
	 * @type {number}
	 * @memberof RoutesProductResponse
	 */
	width?: number;
}

/**
 * Check if a given object implements the RoutesProductResponse interface.
 */
export function instanceOfRoutesProductResponse(value: object): value is RoutesProductResponse {
	return true;
}

export function RoutesProductResponseFromJSON(json: any): RoutesProductResponse {
	return RoutesProductResponseFromJSONTyped(json, false);
}

export function RoutesProductResponseFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): RoutesProductResponse {
	if (json == null) {
		return json;
	}
	return {
		category: json["category"] == null ? undefined : RoutesCategoryInfoFromJSON(json["category"]),
		categoryId: json["category_id"] == null ? undefined : json["category_id"],
		createdAt: json["created_at"] == null ? undefined : json["created_at"],
		description: json["description"] == null ? undefined : json["description"],
		height: json["height"] == null ? undefined : json["height"],
		id: json["id"] == null ? undefined : json["id"],
		length: json["length"] == null ? undefined : json["length"],
		name: json["name"] == null ? undefined : json["name"],
		price: json["price"] == null ? undefined : json["price"],
		productImages: json["product_images"] == null ? undefined : json["product_images"],
		reference: json["reference"] == null ? undefined : json["reference"],
		status: json["status"] == null ? undefined : json["status"],
		stockQuantity: json["stock_quantity"] == null ? undefined : json["stock_quantity"],
		updatedAt: json["updated_at"] == null ? undefined : json["updated_at"],
		vendor: json["vendor"] == null ? undefined : EntVendorProfileFromJSON(json["vendor"]),
		weight: json["weight"] == null ? undefined : json["weight"],
		width: json["width"] == null ? undefined : json["width"]
	};
}

export function RoutesProductResponseToJSON(json: any): RoutesProductResponse {
	return RoutesProductResponseToJSONTyped(json, false);
}

export function RoutesProductResponseToJSONTyped(
	value?: RoutesProductResponse | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		category: RoutesCategoryInfoToJSON(value["category"]),
		category_id: value["categoryId"],
		created_at: value["createdAt"],
		description: value["description"],
		height: value["height"],
		id: value["id"],
		length: value["length"],
		name: value["name"],
		price: value["price"],
		product_images: value["productImages"],
		reference: value["reference"],
		status: value["status"],
		stock_quantity: value["stockQuantity"],
		updated_at: value["updatedAt"],
		vendor: EntVendorProfileToJSON(value["vendor"]),
		weight: value["weight"],
		width: value["width"]
	};
}
