/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface RoutesSendPhoneVerificationResponse
 */
export interface RoutesSendPhoneVerificationResponse {
	/**
	 *
	 * @type {string}
	 * @memberof RoutesSendPhoneVerificationResponse
	 */
	message?: string;
}

/**
 * Check if a given object implements the RoutesSendPhoneVerificationResponse interface.
 */
export function instanceOfRoutesSendPhoneVerificationResponse(
	value: object
): value is RoutesSendPhoneVerificationResponse {
	return true;
}

export function RoutesSendPhoneVerificationResponseFromJSON(
	json: any
): RoutesSendPhoneVerificationResponse {
	return RoutesSendPhoneVerificationResponseFromJSONTyped(json, false);
}

export function RoutesSendPhoneVerificationResponseFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): RoutesSendPhoneVerificationResponse {
	if (json == null) {
		return json;
	}
	return {
		message: json["message"] == null ? undefined : json["message"]
	};
}

export function RoutesSendPhoneVerificationResponseToJSON(
	json: any
): RoutesSendPhoneVerificationResponse {
	return RoutesSendPhoneVerificationResponseToJSONTyped(json, false);
}

export function RoutesSendPhoneVerificationResponseToJSONTyped(
	value?: RoutesSendPhoneVerificationResponse | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		message: value["message"]
	};
}
