/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface RoutesCourierStripeLinkResponse
 */
export interface RoutesCourierStripeLinkResponse {
	/**
	 *
	 * @type {string}
	 * @memberof RoutesCourierStripeLinkResponse
	 */
	accountLink?: string;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesCourierStripeLinkResponse
	 */
	clientSecret?: string;
}

/**
 * Check if a given object implements the RoutesCourierStripeLinkResponse interface.
 */
export function instanceOfRoutesCourierStripeLinkResponse(
	value: object
): value is RoutesCourierStripeLinkResponse {
	return true;
}

export function RoutesCourierStripeLinkResponseFromJSON(
	json: any
): RoutesCourierStripeLinkResponse {
	return RoutesCourierStripeLinkResponseFromJSONTyped(json, false);
}

export function RoutesCourierStripeLinkResponseFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): RoutesCourierStripeLinkResponse {
	if (json == null) {
		return json;
	}
	return {
		accountLink: json["account_link"] == null ? undefined : json["account_link"],
		clientSecret: json["client_secret"] == null ? undefined : json["client_secret"]
	};
}

export function RoutesCourierStripeLinkResponseToJSON(json: any): RoutesCourierStripeLinkResponse {
	return RoutesCourierStripeLinkResponseToJSONTyped(json, false);
}

export function RoutesCourierStripeLinkResponseToJSONTyped(
	value?: RoutesCourierStripeLinkResponse | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		account_link: value["accountLink"],
		client_secret: value["clientSecret"]
	};
}
