/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface RoutesRegisterResponse
 */
export interface RoutesRegisterResponse {
	/**
	 *
	 * @type {string}
	 * @memberof RoutesRegisterResponse
	 */
	message?: string;
}

/**
 * Check if a given object implements the RoutesRegisterResponse interface.
 */
export function instanceOfRoutesRegisterResponse(value: object): value is RoutesRegisterResponse {
	return true;
}

export function RoutesRegisterResponseFromJSON(json: any): RoutesRegisterResponse {
	return RoutesRegisterResponseFromJSONTyped(json, false);
}

export function RoutesRegisterResponseFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): RoutesRegisterResponse {
	if (json == null) {
		return json;
	}
	return {
		message: json["message"] == null ? undefined : json["message"]
	};
}

export function RoutesRegisterResponseToJSON(json: any): RoutesRegisterResponse {
	return RoutesRegisterResponseToJSONTyped(json, false);
}

export function RoutesRegisterResponseToJSONTyped(
	value?: RoutesRegisterResponse | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		message: value["message"]
	};
}
