/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface RoutesSendPasswordResetResponse
 */
export interface RoutesSendPasswordResetResponse {
	/**
	 *
	 * @type {string}
	 * @memberof RoutesSendPasswordResetResponse
	 */
	message?: string;
}

/**
 * Check if a given object implements the RoutesSendPasswordResetResponse interface.
 */
export function instanceOfRoutesSendPasswordResetResponse(
	value: object
): value is RoutesSendPasswordResetResponse {
	return true;
}

export function RoutesSendPasswordResetResponseFromJSON(
	json: any
): RoutesSendPasswordResetResponse {
	return RoutesSendPasswordResetResponseFromJSONTyped(json, false);
}

export function RoutesSendPasswordResetResponseFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): RoutesSendPasswordResetResponse {
	if (json == null) {
		return json;
	}
	return {
		message: json["message"] == null ? undefined : json["message"]
	};
}

export function RoutesSendPasswordResetResponseToJSON(json: any): RoutesSendPasswordResetResponse {
	return RoutesSendPasswordResetResponseToJSONTyped(json, false);
}

export function RoutesSendPasswordResetResponseToJSONTyped(
	value?: RoutesSendPasswordResetResponse | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		message: value["message"]
	};
}
