/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface RoutesSendPasswordResetRequest
 */
export interface RoutesSendPasswordResetRequest {
	/**
	 *
	 * @type {string}
	 * @memberof RoutesSendPasswordResetRequest
	 */
	email: string;
}

/**
 * Check if a given object implements the RoutesSendPasswordResetRequest interface.
 */
export function instanceOfRoutesSendPasswordResetRequest(
	value: object
): value is RoutesSendPasswordResetRequest {
	if (!("email" in value) || value["email"] === undefined) return false;
	return true;
}

export function RoutesSendPasswordResetRequestFromJSON(json: any): RoutesSendPasswordResetRequest {
	return RoutesSendPasswordResetRequestFromJSONTyped(json, false);
}

export function RoutesSendPasswordResetRequestFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): RoutesSendPasswordResetRequest {
	if (json == null) {
		return json;
	}
	return {
		email: json["email"]
	};
}

export function RoutesSendPasswordResetRequestToJSON(json: any): RoutesSendPasswordResetRequest {
	return RoutesSendPasswordResetRequestToJSONTyped(json, false);
}

export function RoutesSendPasswordResetRequestToJSONTyped(
	value?: RoutesSendPasswordResetRequest | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		email: value["email"]
	};
}
