/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface RoutesCategoryResponse
 */
export interface RoutesCategoryResponse {
	/**
	 *
	 * @type {string}
	 * @memberof RoutesCategoryResponse
	 */
	id?: string;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesCategoryResponse
	 */
	name?: string;
	/**
	 *
	 * @type {number}
	 * @memberof RoutesCategoryResponse
	 */
	productCount?: number;
}

/**
 * Check if a given object implements the RoutesCategoryResponse interface.
 */
export function instanceOfRoutesCategoryResponse(value: object): value is RoutesCategoryResponse {
	return true;
}

export function RoutesCategoryResponseFromJSON(json: any): RoutesCategoryResponse {
	return RoutesCategoryResponseFromJSONTyped(json, false);
}

export function RoutesCategoryResponseFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): RoutesCategoryResponse {
	if (json == null) {
		return json;
	}
	return {
		id: json["id"] == null ? undefined : json["id"],
		name: json["name"] == null ? undefined : json["name"],
		productCount: json["product_count"] == null ? undefined : json["product_count"]
	};
}

export function RoutesCategoryResponseToJSON(json: any): RoutesCategoryResponse {
	return RoutesCategoryResponseToJSONTyped(json, false);
}

export function RoutesCategoryResponseToJSONTyped(
	value?: RoutesCategoryResponse | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		id: value["id"],
		name: value["name"],
		product_count: value["productCount"]
	};
}
