/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface RoutesCreateProductRequest
 */
export interface RoutesCreateProductRequest {
	/**
	 *
	 * @type {string}
	 * @memberof RoutesCreateProductRequest
	 */
	categoryId: string;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesCreateProductRequest
	 */
	description?: string;
	/**
	 *
	 * @type {number}
	 * @memberof RoutesCreateProductRequest
	 */
	height: number;
	/**
	 *
	 * @type {number}
	 * @memberof RoutesCreateProductRequest
	 */
	length: number;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesCreateProductRequest
	 */
	name: string;
	/**
	 *
	 * @type {number}
	 * @memberof RoutesCreateProductRequest
	 */
	price: number;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesCreateProductRequest
	 */
	reference?: string;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesCreateProductRequest
	 */
	status?: string;
	/**
	 *
	 * @type {number}
	 * @memberof RoutesCreateProductRequest
	 */
	stockQuantity?: number;
	/**
	 *
	 * @type {number}
	 * @memberof RoutesCreateProductRequest
	 */
	weight: number;
	/**
	 *
	 * @type {number}
	 * @memberof RoutesCreateProductRequest
	 */
	width: number;
}

/**
 * Check if a given object implements the RoutesCreateProductRequest interface.
 */
export function instanceOfRoutesCreateProductRequest(
	value: object
): value is RoutesCreateProductRequest {
	if (!("categoryId" in value) || value["categoryId"] === undefined) return false;
	if (!("height" in value) || value["height"] === undefined) return false;
	if (!("length" in value) || value["length"] === undefined) return false;
	if (!("name" in value) || value["name"] === undefined) return false;
	if (!("price" in value) || value["price"] === undefined) return false;
	if (!("weight" in value) || value["weight"] === undefined) return false;
	if (!("width" in value) || value["width"] === undefined) return false;
	return true;
}

export function RoutesCreateProductRequestFromJSON(json: any): RoutesCreateProductRequest {
	return RoutesCreateProductRequestFromJSONTyped(json, false);
}

export function RoutesCreateProductRequestFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): RoutesCreateProductRequest {
	if (json == null) {
		return json;
	}
	return {
		categoryId: json["category_id"],
		description: json["description"] == null ? undefined : json["description"],
		height: json["height"],
		length: json["length"],
		name: json["name"],
		price: json["price"],
		reference: json["reference"] == null ? undefined : json["reference"],
		status: json["status"] == null ? undefined : json["status"],
		stockQuantity: json["stock_quantity"] == null ? undefined : json["stock_quantity"],
		weight: json["weight"],
		width: json["width"]
	};
}

export function RoutesCreateProductRequestToJSON(json: any): RoutesCreateProductRequest {
	return RoutesCreateProductRequestToJSONTyped(json, false);
}

export function RoutesCreateProductRequestToJSONTyped(
	value?: RoutesCreateProductRequest | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		category_id: value["categoryId"],
		description: value["description"],
		height: value["height"],
		length: value["length"],
		name: value["name"],
		price: value["price"],
		reference: value["reference"],
		status: value["status"],
		stock_quantity: value["stockQuantity"],
		weight: value["weight"],
		width: value["width"]
	};
}
