/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface RoutesProductImageRequest
 */
export interface RoutesProductImageRequest {
	/**
	 *
	 * @type {string}
	 * @memberof RoutesProductImageRequest
	 */
	base64Data: string;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesProductImageRequest
	 */
	filename: string;
}

/**
 * Check if a given object implements the RoutesProductImageRequest interface.
 */
export function instanceOfRoutesProductImageRequest(
	value: object
): value is RoutesProductImageRequest {
	if (!("base64Data" in value) || value["base64Data"] === undefined) return false;
	if (!("filename" in value) || value["filename"] === undefined) return false;
	return true;
}

export function RoutesProductImageRequestFromJSON(json: any): RoutesProductImageRequest {
	return RoutesProductImageRequestFromJSONTyped(json, false);
}

export function RoutesProductImageRequestFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): RoutesProductImageRequest {
	if (json == null) {
		return json;
	}
	return {
		base64Data: json["base64_data"],
		filename: json["filename"]
	};
}

export function RoutesProductImageRequestToJSON(json: any): RoutesProductImageRequest {
	return RoutesProductImageRequestToJSONTyped(json, false);
}

export function RoutesProductImageRequestToJSONTyped(
	value?: RoutesProductImageRequest | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		base64_data: value["base64Data"],
		filename: value["filename"]
	};
}
