/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface RoutesLoginResponse
 */
export interface RoutesLoginResponse {
	/**
	 *
	 * @type {string}
	 * @memberof RoutesLoginResponse
	 */
	accessToken?: string;
	/**
	 *
	 * @type {number}
	 * @memberof RoutesLoginResponse
	 */
	expiresIn?: number;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesLoginResponse
	 */
	refreshToken?: string;
}

/**
 * Check if a given object implements the RoutesLoginResponse interface.
 */
export function instanceOfRoutesLoginResponse(value: object): value is RoutesLoginResponse {
	return true;
}

export function RoutesLoginResponseFromJSON(json: any): RoutesLoginResponse {
	return RoutesLoginResponseFromJSONTyped(json, false);
}

export function RoutesLoginResponseFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): RoutesLoginResponse {
	if (json == null) {
		return json;
	}
	return {
		accessToken: json["access_token"] == null ? undefined : json["access_token"],
		expiresIn: json["expires_in"] == null ? undefined : json["expires_in"],
		refreshToken: json["refresh_token"] == null ? undefined : json["refresh_token"]
	};
}

export function RoutesLoginResponseToJSON(json: any): RoutesLoginResponse {
	return RoutesLoginResponseToJSONTyped(json, false);
}

export function RoutesLoginResponseToJSONTyped(
	value?: RoutesLoginResponse | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		access_token: value["accessToken"],
		expires_in: value["expiresIn"],
		refresh_token: value["refreshToken"]
	};
}
