/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { SchemaBusinessDay } from "./SchemaBusinessDay";
import {
	SchemaBusinessDayFromJSON,
	SchemaBusinessDayFromJSONTyped,
	SchemaBusinessDayToJSON,
	SchemaBusinessDayToJSONTyped
} from "./SchemaBusinessDay";

/**
 *
 * @export
 * @interface RoutesPublicVendorResponse
 */
export interface RoutesPublicVendorResponse {
	/**
	 *
	 * @type {string}
	 * @memberof RoutesPublicVendorResponse
	 */
	address?: string;
	/**
	 *
	 * @type {Array<SchemaBusinessDay>}
	 * @memberof RoutesPublicVendorResponse
	 */
	businessDays?: Array<SchemaBusinessDay>;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesPublicVendorResponse
	 */
	businessName?: string;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesPublicVendorResponse
	 */
	city?: string;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesPublicVendorResponse
	 */
	description?: string;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesPublicVendorResponse
	 */
	id?: string;
	/**
	 *
	 * @type {number}
	 * @memberof RoutesPublicVendorResponse
	 */
	latitude?: number;
	/**
	 *
	 * @type {number}
	 * @memberof RoutesPublicVendorResponse
	 */
	longitude?: number;
	/**
	 *
	 * @type {number}
	 * @memberof RoutesPublicVendorResponse
	 */
	minOrderAmount?: number;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesPublicVendorResponse
	 */
	postalCode?: string;
	/**
	 *
	 * @type {number}
	 * @memberof RoutesPublicVendorResponse
	 */
	preparationTimeMinutes?: number;
	/**
	 *
	 * @type {number}
	 * @memberof RoutesPublicVendorResponse
	 */
	totalProducts?: number;
}

/**
 * Check if a given object implements the RoutesPublicVendorResponse interface.
 */
export function instanceOfRoutesPublicVendorResponse(
	value: object
): value is RoutesPublicVendorResponse {
	return true;
}

export function RoutesPublicVendorResponseFromJSON(json: any): RoutesPublicVendorResponse {
	return RoutesPublicVendorResponseFromJSONTyped(json, false);
}

export function RoutesPublicVendorResponseFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): RoutesPublicVendorResponse {
	if (json == null) {
		return json;
	}
	return {
		address: json["address"] == null ? undefined : json["address"],
		businessDays:
			json["business_days"] == null
				? undefined
				: (json["business_days"] as Array<any>).map(SchemaBusinessDayFromJSON),
		businessName: json["business_name"] == null ? undefined : json["business_name"],
		city: json["city"] == null ? undefined : json["city"],
		description: json["description"] == null ? undefined : json["description"],
		id: json["id"] == null ? undefined : json["id"],
		latitude: json["latitude"] == null ? undefined : json["latitude"],
		longitude: json["longitude"] == null ? undefined : json["longitude"],
		minOrderAmount: json["min_order_amount"] == null ? undefined : json["min_order_amount"],
		postalCode: json["postal_code"] == null ? undefined : json["postal_code"],
		preparationTimeMinutes:
			json["preparation_time_minutes"] == null ? undefined : json["preparation_time_minutes"],
		totalProducts: json["total_products"] == null ? undefined : json["total_products"]
	};
}

export function RoutesPublicVendorResponseToJSON(json: any): RoutesPublicVendorResponse {
	return RoutesPublicVendorResponseToJSONTyped(json, false);
}

export function RoutesPublicVendorResponseToJSONTyped(
	value?: RoutesPublicVendorResponse | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		address: value["address"],
		business_days:
			value["businessDays"] == null
				? undefined
				: (value["businessDays"] as Array<any>).map(SchemaBusinessDayToJSON),
		business_name: value["businessName"],
		city: value["city"],
		description: value["description"],
		id: value["id"],
		latitude: value["latitude"],
		longitude: value["longitude"],
		min_order_amount: value["minOrderAmount"],
		postal_code: value["postalCode"],
		preparation_time_minutes: value["preparationTimeMinutes"],
		total_products: value["totalProducts"]
	};
}
