/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { RoutesProductResponse } from "./RoutesProductResponse";
import {
	RoutesProductResponseFromJSON,
	RoutesProductResponseFromJSONTyped,
	RoutesProductResponseToJSON,
	RoutesProductResponseToJSONTyped
} from "./RoutesProductResponse";

/**
 *
 * @export
 * @interface RoutesProductListResponse
 */
export interface RoutesProductListResponse {
	/**
	 *
	 * @type {boolean}
	 * @memberof RoutesProductListResponse
	 */
	hasMore?: boolean;
	/**
	 *
	 * @type {number}
	 * @memberof RoutesProductListResponse
	 */
	limit?: number;
	/**
	 *
	 * @type {number}
	 * @memberof RoutesProductListResponse
	 */
	page?: number;
	/**
	 *
	 * @type {Array<RoutesProductResponse>}
	 * @memberof RoutesProductListResponse
	 */
	products?: Array<RoutesProductResponse>;
	/**
	 *
	 * @type {number}
	 * @memberof RoutesProductListResponse
	 */
	total?: number;
}

/**
 * Check if a given object implements the RoutesProductListResponse interface.
 */
export function instanceOfRoutesProductListResponse(
	value: object
): value is RoutesProductListResponse {
	return true;
}

export function RoutesProductListResponseFromJSON(json: any): RoutesProductListResponse {
	return RoutesProductListResponseFromJSONTyped(json, false);
}

export function RoutesProductListResponseFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): RoutesProductListResponse {
	if (json == null) {
		return json;
	}
	return {
		hasMore: json["has_more"] == null ? undefined : json["has_more"],
		limit: json["limit"] == null ? undefined : json["limit"],
		page: json["page"] == null ? undefined : json["page"],
		products:
			json["products"] == null
				? undefined
				: (json["products"] as Array<any>).map(RoutesProductResponseFromJSON),
		total: json["total"] == null ? undefined : json["total"]
	};
}

export function RoutesProductListResponseToJSON(json: any): RoutesProductListResponse {
	return RoutesProductListResponseToJSONTyped(json, false);
}

export function RoutesProductListResponseToJSONTyped(
	value?: RoutesProductListResponse | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		has_more: value["hasMore"],
		limit: value["limit"],
		page: value["page"],
		products:
			value["products"] == null
				? undefined
				: (value["products"] as Array<any>).map(RoutesProductResponseToJSON),
		total: value["total"]
	};
}
