/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface RoutesCourierRegistrationResponse
 */
export interface RoutesCourierRegistrationResponse {
	/**
	 *
	 * @type {string}
	 * @memberof RoutesCourierRegistrationResponse
	 */
	message?: string;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesCourierRegistrationResponse
	 */
	status?: string;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesCourierRegistrationResponse
	 */
	userId?: string;
}

/**
 * Check if a given object implements the RoutesCourierRegistrationResponse interface.
 */
export function instanceOfRoutesCourierRegistrationResponse(
	value: object
): value is RoutesCourierRegistrationResponse {
	return true;
}

export function RoutesCourierRegistrationResponseFromJSON(
	json: any
): RoutesCourierRegistrationResponse {
	return RoutesCourierRegistrationResponseFromJSONTyped(json, false);
}

export function RoutesCourierRegistrationResponseFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): RoutesCourierRegistrationResponse {
	if (json == null) {
		return json;
	}
	return {
		message: json["message"] == null ? undefined : json["message"],
		status: json["status"] == null ? undefined : json["status"],
		userId: json["user_id"] == null ? undefined : json["user_id"]
	};
}

export function RoutesCourierRegistrationResponseToJSON(
	json: any
): RoutesCourierRegistrationResponse {
	return RoutesCourierRegistrationResponseToJSONTyped(json, false);
}

export function RoutesCourierRegistrationResponseToJSONTyped(
	value?: RoutesCourierRegistrationResponse | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		message: value["message"],
		status: value["status"],
		user_id: value["userId"]
	};
}
