/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface RoutesLoginRequest
 */
export interface RoutesLoginRequest {
	/**
	 *
	 * @type {string}
	 * @memberof RoutesLoginRequest
	 */
	email: string;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesLoginRequest
	 */
	password: string;
}

/**
 * Check if a given object implements the RoutesLoginRequest interface.
 */
export function instanceOfRoutesLoginRequest(value: object): value is RoutesLoginRequest {
	if (!("email" in value) || value["email"] === undefined) return false;
	if (!("password" in value) || value["password"] === undefined) return false;
	return true;
}

export function RoutesLoginRequestFromJSON(json: any): RoutesLoginRequest {
	return RoutesLoginRequestFromJSONTyped(json, false);
}

export function RoutesLoginRequestFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): RoutesLoginRequest {
	if (json == null) {
		return json;
	}
	return {
		email: json["email"],
		password: json["password"]
	};
}

export function RoutesLoginRequestToJSON(json: any): RoutesLoginRequest {
	return RoutesLoginRequestToJSONTyped(json, false);
}

export function RoutesLoginRequestToJSONTyped(
	value?: RoutesLoginRequest | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		email: value["email"],
		password: value["password"]
	};
}
