/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface RoutesCategoryInfo
 */
export interface RoutesCategoryInfo {
	/**
	 *
	 * @type {string}
	 * @memberof RoutesCategoryInfo
	 */
	id?: string;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesCategoryInfo
	 */
	name?: string;
}

/**
 * Check if a given object implements the RoutesCategoryInfo interface.
 */
export function instanceOfRoutesCategoryInfo(value: object): value is RoutesCategoryInfo {
	return true;
}

export function RoutesCategoryInfoFromJSON(json: any): RoutesCategoryInfo {
	return RoutesCategoryInfoFromJSONTyped(json, false);
}

export function RoutesCategoryInfoFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): RoutesCategoryInfo {
	if (json == null) {
		return json;
	}
	return {
		id: json["id"] == null ? undefined : json["id"],
		name: json["name"] == null ? undefined : json["name"]
	};
}

export function RoutesCategoryInfoToJSON(json: any): RoutesCategoryInfo {
	return RoutesCategoryInfoToJSONTyped(json, false);
}

export function RoutesCategoryInfoToJSONTyped(
	value?: RoutesCategoryInfo | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		id: value["id"],
		name: value["name"]
	};
}
