/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { SchemaRole } from "./SchemaRole";
import {
	SchemaRoleFromJSON,
	SchemaRoleFromJSONTyped,
	SchemaRoleToJSON,
	SchemaRoleToJSONTyped
} from "./SchemaRole";

/**
 *
 * @export
 * @interface RoutesMeResponse
 */
export interface RoutesMeResponse {
	/**
	 *
	 * @type {string}
	 * @memberof RoutesMeResponse
	 */
	createdAt?: string;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesMeResponse
	 */
	email?: string;
	/**
	 *
	 * @type {boolean}
	 * @memberof RoutesMeResponse
	 */
	emailVerified?: boolean;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesMeResponse
	 */
	firstName?: string;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesMeResponse
	 */
	id?: string;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesMeResponse
	 */
	lastName?: string;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesMeResponse
	 */
	phone?: string;
	/**
	 *
	 * @type {boolean}
	 * @memberof RoutesMeResponse
	 */
	phoneVerified?: boolean;
	/**
	 *
	 * @type {SchemaRole}
	 * @memberof RoutesMeResponse
	 */
	role?: SchemaRole;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesMeResponse
	 */
	updatedAt?: string;
}

/**
 * Check if a given object implements the RoutesMeResponse interface.
 */
export function instanceOfRoutesMeResponse(value: object): value is RoutesMeResponse {
	return true;
}

export function RoutesMeResponseFromJSON(json: any): RoutesMeResponse {
	return RoutesMeResponseFromJSONTyped(json, false);
}

export function RoutesMeResponseFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): RoutesMeResponse {
	if (json == null) {
		return json;
	}
	return {
		createdAt: json["created_at"] == null ? undefined : json["created_at"],
		email: json["email"] == null ? undefined : json["email"],
		emailVerified: json["email_verified"] == null ? undefined : json["email_verified"],
		firstName: json["first_name"] == null ? undefined : json["first_name"],
		id: json["id"] == null ? undefined : json["id"],
		lastName: json["last_name"] == null ? undefined : json["last_name"],
		phone: json["phone"] == null ? undefined : json["phone"],
		phoneVerified: json["phone_verified"] == null ? undefined : json["phone_verified"],
		role: json["role"] == null ? undefined : SchemaRoleFromJSON(json["role"]),
		updatedAt: json["updated_at"] == null ? undefined : json["updated_at"]
	};
}

export function RoutesMeResponseToJSON(json: any): RoutesMeResponse {
	return RoutesMeResponseToJSONTyped(json, false);
}

export function RoutesMeResponseToJSONTyped(
	value?: RoutesMeResponse | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		created_at: value["createdAt"],
		email: value["email"],
		email_verified: value["emailVerified"],
		first_name: value["firstName"],
		id: value["id"],
		last_name: value["lastName"],
		phone: value["phone"],
		phone_verified: value["phoneVerified"],
		role: SchemaRoleToJSON(value["role"]),
		updated_at: value["updatedAt"]
	};
}
