/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface RoutesVendorRegistrationResponse
 */
export interface RoutesVendorRegistrationResponse {
	/**
	 *
	 * @type {string}
	 * @memberof RoutesVendorRegistrationResponse
	 */
	message?: string;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesVendorRegistrationResponse
	 */
	status?: string;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesVendorRegistrationResponse
	 */
	userId?: string;
}

/**
 * Check if a given object implements the RoutesVendorRegistrationResponse interface.
 */
export function instanceOfRoutesVendorRegistrationResponse(
	value: object
): value is RoutesVendorRegistrationResponse {
	return true;
}

export function RoutesVendorRegistrationResponseFromJSON(
	json: any
): RoutesVendorRegistrationResponse {
	return RoutesVendorRegistrationResponseFromJSONTyped(json, false);
}

export function RoutesVendorRegistrationResponseFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): RoutesVendorRegistrationResponse {
	if (json == null) {
		return json;
	}
	return {
		message: json["message"] == null ? undefined : json["message"],
		status: json["status"] == null ? undefined : json["status"],
		userId: json["user_id"] == null ? undefined : json["user_id"]
	};
}

export function RoutesVendorRegistrationResponseToJSON(
	json: any
): RoutesVendorRegistrationResponse {
	return RoutesVendorRegistrationResponseToJSONTyped(json, false);
}

export function RoutesVendorRegistrationResponseToJSONTyped(
	value?: RoutesVendorRegistrationResponse | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		message: value["message"],
		status: value["status"],
		user_id: value["userId"]
	};
}
