/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface RoutesCourierRegistrationRequest
 */
export interface RoutesCourierRegistrationRequest {
	/**
	 *
	 * @type {boolean}
	 * @memberof RoutesCourierRegistrationRequest
	 */
	attestation: boolean;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesCourierRegistrationRequest
	 */
	city: string;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesCourierRegistrationRequest
	 */
	confirmPassword: string;
	/**
	 * Permis de conduire
	 * @type {string}
	 * @memberof RoutesCourierRegistrationRequest
	 */
	driverLicense?: string;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesCourierRegistrationRequest
	 */
	email: string;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesCourierRegistrationRequest
	 */
	firstName: string;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesCourierRegistrationRequest
	 */
	lastName: string;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesCourierRegistrationRequest
	 */
	password: string;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesCourierRegistrationRequest
	 */
	phone: string;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesCourierRegistrationRequest
	 */
	postalCode: string;
	/**
	 * RC Pro
	 * @type {string}
	 * @memberof RoutesCourierRegistrationRequest
	 */
	professionalLiability?: string;
	/**
	 * Contrôle Technique
	 * @type {string}
	 * @memberof RoutesCourierRegistrationRequest
	 */
	technicalInspection?: string;
	/**
	 * Licence de transport
	 * @type {string}
	 * @memberof RoutesCourierRegistrationRequest
	 */
	transportLicense?: string;
	/**
	 * Assurance véhicule
	 * @type {string}
	 * @memberof RoutesCourierRegistrationRequest
	 */
	vehicleInsurance?: string;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesCourierRegistrationRequest
	 */
	vehicleModel?: string;
	/**
	 * Carte Grise
	 * @type {string}
	 * @memberof RoutesCourierRegistrationRequest
	 */
	vehicleRegistration?: string;
	/**
	 *
	 * @type {number}
	 * @memberof RoutesCourierRegistrationRequest
	 */
	vehicleType: number;
}

/**
 * Check if a given object implements the RoutesCourierRegistrationRequest interface.
 */
export function instanceOfRoutesCourierRegistrationRequest(
	value: object
): value is RoutesCourierRegistrationRequest {
	if (!("attestation" in value) || value["attestation"] === undefined) return false;
	if (!("city" in value) || value["city"] === undefined) return false;
	if (!("confirmPassword" in value) || value["confirmPassword"] === undefined) return false;
	if (!("email" in value) || value["email"] === undefined) return false;
	if (!("firstName" in value) || value["firstName"] === undefined) return false;
	if (!("lastName" in value) || value["lastName"] === undefined) return false;
	if (!("password" in value) || value["password"] === undefined) return false;
	if (!("phone" in value) || value["phone"] === undefined) return false;
	if (!("postalCode" in value) || value["postalCode"] === undefined) return false;
	if (!("vehicleType" in value) || value["vehicleType"] === undefined) return false;
	return true;
}

export function RoutesCourierRegistrationRequestFromJSON(
	json: any
): RoutesCourierRegistrationRequest {
	return RoutesCourierRegistrationRequestFromJSONTyped(json, false);
}

export function RoutesCourierRegistrationRequestFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): RoutesCourierRegistrationRequest {
	if (json == null) {
		return json;
	}
	return {
		attestation: json["attestation"],
		city: json["city"],
		confirmPassword: json["confirm_password"],
		driverLicense: json["driver_license"] == null ? undefined : json["driver_license"],
		email: json["email"],
		firstName: json["first_name"],
		lastName: json["last_name"],
		password: json["password"],
		phone: json["phone"],
		postalCode: json["postal_code"],
		professionalLiability:
			json["professional_liability"] == null ? undefined : json["professional_liability"],
		technicalInspection:
			json["technical_inspection"] == null ? undefined : json["technical_inspection"],
		transportLicense: json["transport_license"] == null ? undefined : json["transport_license"],
		vehicleInsurance: json["vehicle_insurance"] == null ? undefined : json["vehicle_insurance"],
		vehicleModel: json["vehicle_model"] == null ? undefined : json["vehicle_model"],
		vehicleRegistration:
			json["vehicle_registration"] == null ? undefined : json["vehicle_registration"],
		vehicleType: json["vehicle_type"]
	};
}

export function RoutesCourierRegistrationRequestToJSON(
	json: any
): RoutesCourierRegistrationRequest {
	return RoutesCourierRegistrationRequestToJSONTyped(json, false);
}

export function RoutesCourierRegistrationRequestToJSONTyped(
	value?: RoutesCourierRegistrationRequest | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		attestation: value["attestation"],
		city: value["city"],
		confirm_password: value["confirmPassword"],
		driver_license: value["driverLicense"],
		email: value["email"],
		first_name: value["firstName"],
		last_name: value["lastName"],
		password: value["password"],
		phone: value["phone"],
		postal_code: value["postalCode"],
		professional_liability: value["professionalLiability"],
		technical_inspection: value["technicalInspection"],
		transport_license: value["transportLicense"],
		vehicle_insurance: value["vehicleInsurance"],
		vehicle_model: value["vehicleModel"],
		vehicle_registration: value["vehicleRegistration"],
		vehicle_type: value["vehicleType"]
	};
}
