/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface RoutesClientProfileResponse
 */
export interface RoutesClientProfileResponse {
	/**
	 *
	 * @type {Array<string>}
	 * @memberof RoutesClientProfileResponse
	 */
	deliveryAddresses?: Array<string>;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesClientProfileResponse
	 */
	id?: string;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesClientProfileResponse
	 */
	stripeCustomerId?: string;
}

/**
 * Check if a given object implements the RoutesClientProfileResponse interface.
 */
export function instanceOfRoutesClientProfileResponse(
	value: object
): value is RoutesClientProfileResponse {
	return true;
}

export function RoutesClientProfileResponseFromJSON(json: any): RoutesClientProfileResponse {
	return RoutesClientProfileResponseFromJSONTyped(json, false);
}

export function RoutesClientProfileResponseFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): RoutesClientProfileResponse {
	if (json == null) {
		return json;
	}
	return {
		deliveryAddresses: json["delivery_addresses"] == null ? undefined : json["delivery_addresses"],
		id: json["id"] == null ? undefined : json["id"],
		stripeCustomerId: json["stripe_customer_id"] == null ? undefined : json["stripe_customer_id"]
	};
}

export function RoutesClientProfileResponseToJSON(json: any): RoutesClientProfileResponse {
	return RoutesClientProfileResponseToJSONTyped(json, false);
}

export function RoutesClientProfileResponseToJSONTyped(
	value?: RoutesClientProfileResponse | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		delivery_addresses: value["deliveryAddresses"],
		id: value["id"],
		stripe_customer_id: value["stripeCustomerId"]
	};
}
