/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface RoutesStripeLinkResponse
 */
export interface RoutesStripeLinkResponse {
	/**
	 *
	 * @type {string}
	 * @memberof RoutesStripeLinkResponse
	 */
	accountLink?: string;
	/**
	 *
	 * @type {string}
	 * @memberof RoutesStripeLinkResponse
	 */
	clientSecret?: string;
}

/**
 * Check if a given object implements the RoutesStripeLinkResponse interface.
 */
export function instanceOfRoutesStripeLinkResponse(
	value: object
): value is RoutesStripeLinkResponse {
	return true;
}

export function RoutesStripeLinkResponseFromJSON(json: any): RoutesStripeLinkResponse {
	return RoutesStripeLinkResponseFromJSONTyped(json, false);
}

export function RoutesStripeLinkResponseFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): RoutesStripeLinkResponse {
	if (json == null) {
		return json;
	}
	return {
		accountLink: json["account_link"] == null ? undefined : json["account_link"],
		clientSecret: json["client_secret"] == null ? undefined : json["client_secret"]
	};
}

export function RoutesStripeLinkResponseToJSON(json: any): RoutesStripeLinkResponse {
	return RoutesStripeLinkResponseToJSONTyped(json, false);
}

export function RoutesStripeLinkResponseToJSONTyped(
	value?: RoutesStripeLinkResponse | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		account_link: value["accountLink"],
		client_secret: value["clientSecret"]
	};
}
