/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { RoutesCategoryResponse } from "./RoutesCategoryResponse";
import {
	RoutesCategoryResponseFromJSON,
	RoutesCategoryResponseFromJSONTyped,
	RoutesCategoryResponseToJSON,
	RoutesCategoryResponseToJSONTyped
} from "./RoutesCategoryResponse";

/**
 *
 * @export
 * @interface RoutesCategoryListResponse
 */
export interface RoutesCategoryListResponse {
	/**
	 *
	 * @type {Array<RoutesCategoryResponse>}
	 * @memberof RoutesCategoryListResponse
	 */
	categories?: Array<RoutesCategoryResponse>;
	/**
	 *
	 * @type {number}
	 * @memberof RoutesCategoryListResponse
	 */
	total?: number;
}

/**
 * Check if a given object implements the RoutesCategoryListResponse interface.
 */
export function instanceOfRoutesCategoryListResponse(
	value: object
): value is RoutesCategoryListResponse {
	return true;
}

export function RoutesCategoryListResponseFromJSON(json: any): RoutesCategoryListResponse {
	return RoutesCategoryListResponseFromJSONTyped(json, false);
}

export function RoutesCategoryListResponseFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): RoutesCategoryListResponse {
	if (json == null) {
		return json;
	}
	return {
		categories:
			json["categories"] == null
				? undefined
				: (json["categories"] as Array<any>).map(RoutesCategoryResponseFromJSON),
		total: json["total"] == null ? undefined : json["total"]
	};
}

export function RoutesCategoryListResponseToJSON(json: any): RoutesCategoryListResponse {
	return RoutesCategoryListResponseToJSONTyped(json, false);
}

export function RoutesCategoryListResponseToJSONTyped(
	value?: RoutesCategoryListResponse | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		categories:
			value["categories"] == null
				? undefined
				: (value["categories"] as Array<any>).map(RoutesCategoryResponseToJSON),
		total: value["total"]
	};
}
