/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface RoutesRefreshRequest
 */
export interface RoutesRefreshRequest {
	/**
	 *
	 * @type {string}
	 * @memberof RoutesRefreshRequest
	 */
	refreshToken?: string;
}

/**
 * Check if a given object implements the RoutesRefreshRequest interface.
 */
export function instanceOfRoutesRefreshRequest(value: object): value is RoutesRefreshRequest {
	return true;
}

export function RoutesRefreshRequestFromJSON(json: any): RoutesRefreshRequest {
	return RoutesRefreshRequestFromJSONTyped(json, false);
}

export function RoutesRefreshRequestFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): RoutesRefreshRequest {
	if (json == null) {
		return json;
	}
	return {
		refreshToken: json["refresh_token"] == null ? undefined : json["refresh_token"]
	};
}

export function RoutesRefreshRequestToJSON(json: any): RoutesRefreshRequest {
	return RoutesRefreshRequestToJSONTyped(json, false);
}

export function RoutesRefreshRequestToJSONTyped(
	value?: RoutesRefreshRequest | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		refresh_token: value["refreshToken"]
	};
}
