/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface SchemaTimeSlot
 */
export interface SchemaTimeSlot {
	/**
	 *
	 * @type {string}
	 * @memberof SchemaTimeSlot
	 */
	end?: string;
	/**
	 *
	 * @type {string}
	 * @memberof SchemaTimeSlot
	 */
	start?: string;
}

/**
 * Check if a given object implements the SchemaTimeSlot interface.
 */
export function instanceOfSchemaTimeSlot(value: object): value is SchemaTimeSlot {
	return true;
}

export function SchemaTimeSlotFromJSON(json: any): SchemaTimeSlot {
	return SchemaTimeSlotFromJSONTyped(json, false);
}

export function SchemaTimeSlotFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): SchemaTimeSlot {
	if (json == null) {
		return json;
	}
	return {
		end: json["end"] == null ? undefined : json["end"],
		start: json["start"] == null ? undefined : json["start"]
	};
}

export function SchemaTimeSlotToJSON(json: any): SchemaTimeSlot {
	return SchemaTimeSlotToJSONTyped(json, false);
}

export function SchemaTimeSlotToJSONTyped(
	value?: SchemaTimeSlot | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		end: value["end"],
		start: value["start"]
	};
}
