/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const SchemaDayOfWeek = {
	DayMonday: "monday",
	DayTuesday: "tuesday",
	DayWednesday: "wednesday",
	DayThursday: "thursday",
	DayFriday: "friday",
	DaySaturday: "saturday",
	DaySunday: "sunday"
} as const;
export type SchemaDayOfWeek = (typeof SchemaDayOfWeek)[keyof typeof SchemaDayOfWeek];

export function instanceOfSchemaDayOfWeek(value: any): boolean {
	for (const key in SchemaDayOfWeek) {
		if (Object.prototype.hasOwnProperty.call(SchemaDayOfWeek, key)) {
			if (SchemaDayOfWeek[key as keyof typeof SchemaDayOfWeek] === value) {
				return true;
			}
		}
	}
	return false;
}

export function SchemaDayOfWeekFromJSON(json: any): SchemaDayOfWeek {
	return SchemaDayOfWeekFromJSONTyped(json, false);
}

export function SchemaDayOfWeekFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): SchemaDayOfWeek {
	return json as SchemaDayOfWeek;
}

export function SchemaDayOfWeekToJSON(value?: SchemaDayOfWeek | null): any {
	return value as any;
}

export function SchemaDayOfWeekToJSONTyped(
	value: any,
	ignoreDiscriminator: boolean
): SchemaDayOfWeek {
	return value as SchemaDayOfWeek;
}
