/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { SchemaDayOfWeek } from "./SchemaDayOfWeek";
import {
	SchemaDayOfWeekFromJSON,
	SchemaDayOfWeekFromJSONTyped,
	SchemaDayOfWeekToJSON,
	SchemaDayOfWeekToJSONTyped
} from "./SchemaDayOfWeek";
import type { SchemaTimeSlot } from "./SchemaTimeSlot";
import {
	SchemaTimeSlotFromJSON,
	SchemaTimeSlotFromJSONTyped,
	SchemaTimeSlotToJSON,
	SchemaTimeSlotToJSONTyped
} from "./SchemaTimeSlot";

/**
 *
 * @export
 * @interface SchemaBusinessDay
 */
export interface SchemaBusinessDay {
	/**
	 *
	 * @type {Array<SchemaTimeSlot>}
	 * @memberof SchemaBusinessDay
	 */
	breaks?: Array<SchemaTimeSlot>;
	/**
	 *
	 * @type {string}
	 * @memberof SchemaBusinessDay
	 */
	closeTime?: string;
	/**
	 *
	 * @type {SchemaDayOfWeek}
	 * @memberof SchemaBusinessDay
	 */
	dayOfWeek?: SchemaDayOfWeek;
	/**
	 *
	 * @type {boolean}
	 * @memberof SchemaBusinessDay
	 */
	isClosed?: boolean;
	/**
	 *
	 * @type {string}
	 * @memberof SchemaBusinessDay
	 */
	openTime?: string;
}

/**
 * Check if a given object implements the SchemaBusinessDay interface.
 */
export function instanceOfSchemaBusinessDay(value: object): value is SchemaBusinessDay {
	return true;
}

export function SchemaBusinessDayFromJSON(json: any): SchemaBusinessDay {
	return SchemaBusinessDayFromJSONTyped(json, false);
}

export function SchemaBusinessDayFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): SchemaBusinessDay {
	if (json == null) {
		return json;
	}
	return {
		breaks:
			json["breaks"] == null
				? undefined
				: (json["breaks"] as Array<any>).map(SchemaTimeSlotFromJSON),
		closeTime: json["close_time"] == null ? undefined : json["close_time"],
		dayOfWeek:
			json["day_of_week"] == null ? undefined : SchemaDayOfWeekFromJSON(json["day_of_week"]),
		isClosed: json["is_closed"] == null ? undefined : json["is_closed"],
		openTime: json["open_time"] == null ? undefined : json["open_time"]
	};
}

export function SchemaBusinessDayToJSON(json: any): SchemaBusinessDay {
	return SchemaBusinessDayToJSONTyped(json, false);
}

export function SchemaBusinessDayToJSONTyped(
	value?: SchemaBusinessDay | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		breaks:
			value["breaks"] == null
				? undefined
				: (value["breaks"] as Array<any>).map(SchemaTimeSlotToJSON),
		close_time: value["closeTime"],
		day_of_week: SchemaDayOfWeekToJSON(value["dayOfWeek"]),
		is_closed: value["isClosed"],
		open_time: value["openTime"]
	};
}
