/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const SchemaRole = {
	RoleClient: "client",
	RoleCourier: "courier",
	RoleVendor: "vendor",
	RoleVendorEmployee: "vendor_employee",
	RoleAdmin: "admin"
} as const;
export type SchemaRole = (typeof SchemaRole)[keyof typeof SchemaRole];

export function instanceOfSchemaRole(value: any): boolean {
	for (const key in SchemaRole) {
		if (Object.prototype.hasOwnProperty.call(SchemaRole, key)) {
			if (SchemaRole[key as keyof typeof SchemaRole] === value) {
				return true;
			}
		}
	}
	return false;
}

export function SchemaRoleFromJSON(json: any): SchemaRole {
	return SchemaRoleFromJSONTyped(json, false);
}

export function SchemaRoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): SchemaRole {
	return json as SchemaRole;
}

export function SchemaRoleToJSON(value?: SchemaRole | null): any {
	return value as any;
}

export function SchemaRoleToJSONTyped(value: any, ignoreDiscriminator: boolean): SchemaRole {
	return value as SchemaRole;
}
