/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const VendorprofileStatus = {
	DefaultStatus: "pending_approval",
	StatusPendingApproval: "pending_approval",
	StatusApproved: "approved",
	StatusActive: "active",
	StatusRejected: "rejected"
} as const;
export type VendorprofileStatus = (typeof VendorprofileStatus)[keyof typeof VendorprofileStatus];

export function instanceOfVendorprofileStatus(value: any): boolean {
	for (const key in VendorprofileStatus) {
		if (Object.prototype.hasOwnProperty.call(VendorprofileStatus, key)) {
			if (VendorprofileStatus[key as keyof typeof VendorprofileStatus] === value) {
				return true;
			}
		}
	}
	return false;
}

export function VendorprofileStatusFromJSON(json: any): VendorprofileStatus {
	return VendorprofileStatusFromJSONTyped(json, false);
}

export function VendorprofileStatusFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): VendorprofileStatus {
	return json as VendorprofileStatus;
}

export function VendorprofileStatusToJSON(value?: VendorprofileStatus | null): any {
	return value as any;
}

export function VendorprofileStatusToJSONTyped(
	value: any,
	ignoreDiscriminator: boolean
): VendorprofileStatus {
	return value as VendorprofileStatus;
}
