/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type {
	AdminAdminCourierResponse,
	AdminAdminUserResponse,
	AdminAdminVendorResponse,
	AdminCategoryListResponse,
	AdminCategoryResponse,
	AdminCreateCategoryRequest,
	AdminCreateVehicleTypeRequest,
	AdminListCouriersResponse,
	AdminListUsersResponse,
	AdminListVendorsResponse,
	AdminUpdateCategoryRequest,
	AdminUpdateUserRequest,
	AdminUpdateVehicleTypeRequest,
	AdminVehicleTypeResponse,
	HttputilsErrorResponse,
	HttputilsSuccessResponse
} from "../models/index";
import {
	AdminAdminCourierResponseFromJSON,
	AdminAdminCourierResponseToJSON,
	AdminAdminUserResponseFromJSON,
	AdminAdminUserResponseToJSON,
	AdminAdminVendorResponseFromJSON,
	AdminAdminVendorResponseToJSON,
	AdminCategoryListResponseFromJSON,
	AdminCategoryListResponseToJSON,
	AdminCategoryResponseFromJSON,
	AdminCategoryResponseToJSON,
	AdminCreateCategoryRequestFromJSON,
	AdminCreateCategoryRequestToJSON,
	AdminCreateVehicleTypeRequestFromJSON,
	AdminCreateVehicleTypeRequestToJSON,
	AdminListCouriersResponseFromJSON,
	AdminListCouriersResponseToJSON,
	AdminListUsersResponseFromJSON,
	AdminListUsersResponseToJSON,
	AdminListVendorsResponseFromJSON,
	AdminListVendorsResponseToJSON,
	AdminUpdateCategoryRequestFromJSON,
	AdminUpdateCategoryRequestToJSON,
	AdminUpdateUserRequestFromJSON,
	AdminUpdateUserRequestToJSON,
	AdminUpdateVehicleTypeRequestFromJSON,
	AdminUpdateVehicleTypeRequestToJSON,
	AdminVehicleTypeResponseFromJSON,
	AdminVehicleTypeResponseToJSON,
	HttputilsErrorResponseFromJSON,
	HttputilsErrorResponseToJSON,
	HttputilsSuccessResponseFromJSON,
	HttputilsSuccessResponseToJSON
} from "../models/index";

export interface AdminCategoriesGetRequest {
	xLocale?: string;
	page?: number;
	limit?: number;
	search?: string;
}

export interface AdminCategoriesIdDeleteRequest {
	id: string;
	xLocale?: string;
}

export interface AdminCategoriesIdGetRequest {
	id: string;
	xLocale?: string;
}

export interface AdminCategoriesIdPutRequest {
	id: string;
	category: AdminUpdateCategoryRequest;
	xLocale?: string;
}

export interface AdminCategoriesPostRequest {
	category: AdminCreateCategoryRequest;
	xLocale?: string;
}

export interface AdminCouriersGetRequest {
	xLocale?: string;
	status?: string;
	page?: number;
	limit?: number;
}

export interface AdminCouriersIdApprovePostRequest {
	id: string;
	xLocale?: string;
}

export interface AdminCouriersIdDenyPostRequest {
	id: string;
	xLocale?: string;
}

export interface AdminCouriersIdDocumentsTypeGetRequest {
	id: string;
	type: string;
	xLocale?: string;
}

export interface AdminCouriersIdGetRequest {
	id: string;
	xLocale?: string;
}

export interface AdminUsersExportGetRequest {
	xLocale?: string;
	role?: AdminUsersExportGetRoleEnum;
	verified?: boolean;
	limit?: number;
}

export interface AdminUsersGetRequest {
	xLocale?: string;
	role?: AdminUsersGetRoleEnum;
	verified?: boolean;
	page?: number;
	limit?: number;
}

export interface AdminUsersIdGetRequest {
	id: string;
	xLocale?: string;
}

export interface AdminUsersIdPatchRequest {
	id: string;
	body: AdminUpdateUserRequest;
	xLocale?: string;
}

export interface AdminVehicleTypesIdDeleteRequest {
	id: number;
	xLocale?: string;
}

export interface AdminVehicleTypesIdGetRequest {
	id: number;
	xLocale?: string;
}

export interface AdminVehicleTypesIdPutRequest {
	id: number;
	vehicleType: AdminUpdateVehicleTypeRequest;
	xLocale?: string;
}

export interface AdminVehicleTypesPostRequest {
	vehicleType: AdminCreateVehicleTypeRequest;
	xLocale?: string;
}

export interface AdminVendorsGetRequest {
	xLocale?: string;
	status?: string;
	page?: number;
	limit?: number;
}

export interface AdminVendorsIdApprovePostRequest {
	id: string;
	xLocale?: string;
}

export interface AdminVendorsIdDenyPostRequest {
	id: string;
	xLocale?: string;
}

export interface AdminVendorsIdDocumentsTypeGetRequest {
	id: string;
	type: string;
	xLocale?: string;
}

export interface AdminVendorsIdGetRequest {
	id: string;
	xLocale?: string;
}

/**
 *
 */
export class AdminApi extends runtime.BaseAPI {
	/**
	 * List all product categories (admin only)
	 * List all categories
	 */
	async adminCategoriesGetRaw(
		requestParameters: AdminCategoriesGetRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<AdminCategoryListResponse>> {
		const queryParameters: any = {};

		if (requestParameters["page"] != null) {
			queryParameters["page"] = requestParameters["page"];
		}

		if (requestParameters["limit"] != null) {
			queryParameters["limit"] = requestParameters["limit"];
		}

		if (requestParameters["search"] != null) {
			queryParameters["search"] = requestParameters["search"];
		}

		const headerParameters: runtime.HTTPHeaders = {};

		if (requestParameters["xLocale"] != null) {
			headerParameters["x-locale"] = String(requestParameters["xLocale"]);
		}

		let urlPath = `/admin/categories`;

		const response = await this.request(
			{
				path: urlPath,
				method: "GET",
				headers: headerParameters,
				query: queryParameters
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			AdminCategoryListResponseFromJSON(jsonValue)
		);
	}

	/**
	 * List all product categories (admin only)
	 * List all categories
	 */
	async adminCategoriesGet(
		requestParameters: AdminCategoriesGetRequest = {},
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<AdminCategoryListResponse> {
		const response = await this.adminCategoriesGetRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 * Delete a product category (admin only)
	 * Delete category
	 */
	async adminCategoriesIdDeleteRaw(
		requestParameters: AdminCategoriesIdDeleteRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<HttputilsSuccessResponse>> {
		if (requestParameters["id"] == null) {
			throw new runtime.RequiredError(
				"id",
				'Required parameter "id" was null or undefined when calling adminCategoriesIdDelete().'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		if (requestParameters["xLocale"] != null) {
			headerParameters["x-locale"] = String(requestParameters["xLocale"]);
		}

		let urlPath = `/admin/categories/{id}`;
		urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters["id"])));

		const response = await this.request(
			{
				path: urlPath,
				method: "DELETE",
				headers: headerParameters,
				query: queryParameters
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			HttputilsSuccessResponseFromJSON(jsonValue)
		);
	}

	/**
	 * Delete a product category (admin only)
	 * Delete category
	 */
	async adminCategoriesIdDelete(
		requestParameters: AdminCategoriesIdDeleteRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<HttputilsSuccessResponse> {
		const response = await this.adminCategoriesIdDeleteRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 * Get a specific category by ID (admin only)
	 * Get category by ID
	 */
	async adminCategoriesIdGetRaw(
		requestParameters: AdminCategoriesIdGetRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<AdminCategoryResponse>> {
		if (requestParameters["id"] == null) {
			throw new runtime.RequiredError(
				"id",
				'Required parameter "id" was null or undefined when calling adminCategoriesIdGet().'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		if (requestParameters["xLocale"] != null) {
			headerParameters["x-locale"] = String(requestParameters["xLocale"]);
		}

		let urlPath = `/admin/categories/{id}`;
		urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters["id"])));

		const response = await this.request(
			{
				path: urlPath,
				method: "GET",
				headers: headerParameters,
				query: queryParameters
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			AdminCategoryResponseFromJSON(jsonValue)
		);
	}

	/**
	 * Get a specific category by ID (admin only)
	 * Get category by ID
	 */
	async adminCategoriesIdGet(
		requestParameters: AdminCategoriesIdGetRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<AdminCategoryResponse> {
		const response = await this.adminCategoriesIdGetRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 * Update a product category (admin only)
	 * Update category
	 */
	async adminCategoriesIdPutRaw(
		requestParameters: AdminCategoriesIdPutRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<AdminCategoryResponse>> {
		if (requestParameters["id"] == null) {
			throw new runtime.RequiredError(
				"id",
				'Required parameter "id" was null or undefined when calling adminCategoriesIdPut().'
			);
		}

		if (requestParameters["category"] == null) {
			throw new runtime.RequiredError(
				"category",
				'Required parameter "category" was null or undefined when calling adminCategoriesIdPut().'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		headerParameters["Content-Type"] = "application/json";

		if (requestParameters["xLocale"] != null) {
			headerParameters["x-locale"] = String(requestParameters["xLocale"]);
		}

		let urlPath = `/admin/categories/{id}`;
		urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters["id"])));

		const response = await this.request(
			{
				path: urlPath,
				method: "PUT",
				headers: headerParameters,
				query: queryParameters,
				body: AdminUpdateCategoryRequestToJSON(requestParameters["category"])
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			AdminCategoryResponseFromJSON(jsonValue)
		);
	}

	/**
	 * Update a product category (admin only)
	 * Update category
	 */
	async adminCategoriesIdPut(
		requestParameters: AdminCategoriesIdPutRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<AdminCategoryResponse> {
		const response = await this.adminCategoriesIdPutRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 * Create a new product category (admin only)
	 * Create category
	 */
	async adminCategoriesPostRaw(
		requestParameters: AdminCategoriesPostRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<AdminCategoryResponse>> {
		if (requestParameters["category"] == null) {
			throw new runtime.RequiredError(
				"category",
				'Required parameter "category" was null or undefined when calling adminCategoriesPost().'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		headerParameters["Content-Type"] = "application/json";

		if (requestParameters["xLocale"] != null) {
			headerParameters["x-locale"] = String(requestParameters["xLocale"]);
		}

		let urlPath = `/admin/categories`;

		const response = await this.request(
			{
				path: urlPath,
				method: "POST",
				headers: headerParameters,
				query: queryParameters,
				body: AdminCreateCategoryRequestToJSON(requestParameters["category"])
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			AdminCategoryResponseFromJSON(jsonValue)
		);
	}

	/**
	 * Create a new product category (admin only)
	 * Create category
	 */
	async adminCategoriesPost(
		requestParameters: AdminCategoriesPostRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<AdminCategoryResponse> {
		const response = await this.adminCategoriesPostRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 * Get a paginated list of couriers with optional filters
	 * List couriers (admin)
	 */
	async adminCouriersGetRaw(
		requestParameters: AdminCouriersGetRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<AdminListCouriersResponse>> {
		const queryParameters: any = {};

		if (requestParameters["status"] != null) {
			queryParameters["status"] = requestParameters["status"];
		}

		if (requestParameters["page"] != null) {
			queryParameters["page"] = requestParameters["page"];
		}

		if (requestParameters["limit"] != null) {
			queryParameters["limit"] = requestParameters["limit"];
		}

		const headerParameters: runtime.HTTPHeaders = {};

		if (requestParameters["xLocale"] != null) {
			headerParameters["x-locale"] = String(requestParameters["xLocale"]);
		}

		let urlPath = `/admin/couriers`;

		const response = await this.request(
			{
				path: urlPath,
				method: "GET",
				headers: headerParameters,
				query: queryParameters
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			AdminListCouriersResponseFromJSON(jsonValue)
		);
	}

	/**
	 * Get a paginated list of couriers with optional filters
	 * List couriers (admin)
	 */
	async adminCouriersGet(
		requestParameters: AdminCouriersGetRequest = {},
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<AdminListCouriersResponse> {
		const response = await this.adminCouriersGetRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 * Approve a courier application, create Stripe Connect account and send onboarding email
	 * Approve courier (admin)
	 */
	async adminCouriersIdApprovePostRaw(
		requestParameters: AdminCouriersIdApprovePostRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<HttputilsSuccessResponse>> {
		if (requestParameters["id"] == null) {
			throw new runtime.RequiredError(
				"id",
				'Required parameter "id" was null or undefined when calling adminCouriersIdApprovePost().'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		if (requestParameters["xLocale"] != null) {
			headerParameters["x-locale"] = String(requestParameters["xLocale"]);
		}

		let urlPath = `/admin/couriers/{id}/approve`;
		urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters["id"])));

		const response = await this.request(
			{
				path: urlPath,
				method: "POST",
				headers: headerParameters,
				query: queryParameters
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			HttputilsSuccessResponseFromJSON(jsonValue)
		);
	}

	/**
	 * Approve a courier application, create Stripe Connect account and send onboarding email
	 * Approve courier (admin)
	 */
	async adminCouriersIdApprovePost(
		requestParameters: AdminCouriersIdApprovePostRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<HttputilsSuccessResponse> {
		const response = await this.adminCouriersIdApprovePostRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 * Deny a courier application
	 * Deny courier (admin)
	 */
	async adminCouriersIdDenyPostRaw(
		requestParameters: AdminCouriersIdDenyPostRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<HttputilsSuccessResponse>> {
		if (requestParameters["id"] == null) {
			throw new runtime.RequiredError(
				"id",
				'Required parameter "id" was null or undefined when calling adminCouriersIdDenyPost().'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		if (requestParameters["xLocale"] != null) {
			headerParameters["x-locale"] = String(requestParameters["xLocale"]);
		}

		let urlPath = `/admin/couriers/{id}/deny`;
		urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters["id"])));

		const response = await this.request(
			{
				path: urlPath,
				method: "POST",
				headers: headerParameters,
				query: queryParameters
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			HttputilsSuccessResponseFromJSON(jsonValue)
		);
	}

	/**
	 * Deny a courier application
	 * Deny courier (admin)
	 */
	async adminCouriersIdDenyPost(
		requestParameters: AdminCouriersIdDenyPostRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<HttputilsSuccessResponse> {
		const response = await this.adminCouriersIdDenyPostRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 * Download/view a specific document for a courier (admin only, GDPR compliant)
	 * Get courier document (admin)
	 */
	async adminCouriersIdDocumentsTypeGetRaw(
		requestParameters: AdminCouriersIdDocumentsTypeGetRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<Blob>> {
		if (requestParameters["id"] == null) {
			throw new runtime.RequiredError(
				"id",
				'Required parameter "id" was null or undefined when calling adminCouriersIdDocumentsTypeGet().'
			);
		}

		if (requestParameters["type"] == null) {
			throw new runtime.RequiredError(
				"type",
				'Required parameter "type" was null or undefined when calling adminCouriersIdDocumentsTypeGet().'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		if (requestParameters["xLocale"] != null) {
			headerParameters["x-locale"] = String(requestParameters["xLocale"]);
		}

		let urlPath = `/admin/couriers/{id}/documents/{type}`;
		urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters["id"])));
		urlPath = urlPath.replace(`{${"type"}}`, encodeURIComponent(String(requestParameters["type"])));

		const response = await this.request(
			{
				path: urlPath,
				method: "GET",
				headers: headerParameters,
				query: queryParameters
			},
			initOverrides
		);

		return new runtime.BlobApiResponse(response);
	}

	/**
	 * Download/view a specific document for a courier (admin only, GDPR compliant)
	 * Get courier document (admin)
	 */
	async adminCouriersIdDocumentsTypeGet(
		requestParameters: AdminCouriersIdDocumentsTypeGetRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<Blob> {
		const response = await this.adminCouriersIdDocumentsTypeGetRaw(
			requestParameters,
			initOverrides
		);
		return await response.value();
	}

	/**
	 * Get a specific courier by their ID (admin only)
	 * Get courier by ID (admin)
	 */
	async adminCouriersIdGetRaw(
		requestParameters: AdminCouriersIdGetRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<AdminAdminCourierResponse>> {
		if (requestParameters["id"] == null) {
			throw new runtime.RequiredError(
				"id",
				'Required parameter "id" was null or undefined when calling adminCouriersIdGet().'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		if (requestParameters["xLocale"] != null) {
			headerParameters["x-locale"] = String(requestParameters["xLocale"]);
		}

		let urlPath = `/admin/couriers/{id}`;
		urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters["id"])));

		const response = await this.request(
			{
				path: urlPath,
				method: "GET",
				headers: headerParameters,
				query: queryParameters
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			AdminAdminCourierResponseFromJSON(jsonValue)
		);
	}

	/**
	 * Get a specific courier by their ID (admin only)
	 * Get courier by ID (admin)
	 */
	async adminCouriersIdGet(
		requestParameters: AdminCouriersIdGetRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<AdminAdminCourierResponse> {
		const response = await this.adminCouriersIdGetRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 * Export users to CSV with optional filters
	 * Export users (admin)
	 */
	async adminUsersExportGetRaw(
		requestParameters: AdminUsersExportGetRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<Blob>> {
		const queryParameters: any = {};

		if (requestParameters["role"] != null) {
			queryParameters["role"] = requestParameters["role"];
		}

		if (requestParameters["verified"] != null) {
			queryParameters["verified"] = requestParameters["verified"];
		}

		if (requestParameters["limit"] != null) {
			queryParameters["limit"] = requestParameters["limit"];
		}

		const headerParameters: runtime.HTTPHeaders = {};

		if (requestParameters["xLocale"] != null) {
			headerParameters["x-locale"] = String(requestParameters["xLocale"]);
		}

		let urlPath = `/admin/users/export`;

		const response = await this.request(
			{
				path: urlPath,
				method: "GET",
				headers: headerParameters,
				query: queryParameters
			},
			initOverrides
		);

		return new runtime.BlobApiResponse(response);
	}

	/**
	 * Export users to CSV with optional filters
	 * Export users (admin)
	 */
	async adminUsersExportGet(
		requestParameters: AdminUsersExportGetRequest = {},
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<Blob> {
		const response = await this.adminUsersExportGetRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 * Get a paginated list of users with optional filters
	 * List users (admin)
	 */
	async adminUsersGetRaw(
		requestParameters: AdminUsersGetRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<AdminListUsersResponse>> {
		const queryParameters: any = {};

		if (requestParameters["role"] != null) {
			queryParameters["role"] = requestParameters["role"];
		}

		if (requestParameters["verified"] != null) {
			queryParameters["verified"] = requestParameters["verified"];
		}

		if (requestParameters["page"] != null) {
			queryParameters["page"] = requestParameters["page"];
		}

		if (requestParameters["limit"] != null) {
			queryParameters["limit"] = requestParameters["limit"];
		}

		const headerParameters: runtime.HTTPHeaders = {};

		if (requestParameters["xLocale"] != null) {
			headerParameters["x-locale"] = String(requestParameters["xLocale"]);
		}

		let urlPath = `/admin/users`;

		const response = await this.request(
			{
				path: urlPath,
				method: "GET",
				headers: headerParameters,
				query: queryParameters
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			AdminListUsersResponseFromJSON(jsonValue)
		);
	}

	/**
	 * Get a paginated list of users with optional filters
	 * List users (admin)
	 */
	async adminUsersGet(
		requestParameters: AdminUsersGetRequest = {},
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<AdminListUsersResponse> {
		const response = await this.adminUsersGetRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 * Get detailed information about a specific user
	 * Get user by ID (admin)
	 */
	async adminUsersIdGetRaw(
		requestParameters: AdminUsersIdGetRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<AdminAdminUserResponse>> {
		if (requestParameters["id"] == null) {
			throw new runtime.RequiredError(
				"id",
				'Required parameter "id" was null or undefined when calling adminUsersIdGet().'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		if (requestParameters["xLocale"] != null) {
			headerParameters["x-locale"] = String(requestParameters["xLocale"]);
		}

		let urlPath = `/admin/users/{id}`;
		urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters["id"])));

		const response = await this.request(
			{
				path: urlPath,
				method: "GET",
				headers: headerParameters,
				query: queryParameters
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			AdminAdminUserResponseFromJSON(jsonValue)
		);
	}

	/**
	 * Get detailed information about a specific user
	 * Get user by ID (admin)
	 */
	async adminUsersIdGet(
		requestParameters: AdminUsersIdGetRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<AdminAdminUserResponse> {
		const response = await this.adminUsersIdGetRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 * Update user information including status, role, and verification status
	 * Update user (admin)
	 */
	async adminUsersIdPatchRaw(
		requestParameters: AdminUsersIdPatchRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<AdminAdminUserResponse>> {
		if (requestParameters["id"] == null) {
			throw new runtime.RequiredError(
				"id",
				'Required parameter "id" was null or undefined when calling adminUsersIdPatch().'
			);
		}

		if (requestParameters["body"] == null) {
			throw new runtime.RequiredError(
				"body",
				'Required parameter "body" was null or undefined when calling adminUsersIdPatch().'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		headerParameters["Content-Type"] = "application/json";

		if (requestParameters["xLocale"] != null) {
			headerParameters["x-locale"] = String(requestParameters["xLocale"]);
		}

		let urlPath = `/admin/users/{id}`;
		urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters["id"])));

		const response = await this.request(
			{
				path: urlPath,
				method: "PATCH",
				headers: headerParameters,
				query: queryParameters,
				body: AdminUpdateUserRequestToJSON(requestParameters["body"])
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			AdminAdminUserResponseFromJSON(jsonValue)
		);
	}

	/**
	 * Update user information including status, role, and verification status
	 * Update user (admin)
	 */
	async adminUsersIdPatch(
		requestParameters: AdminUsersIdPatchRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<AdminAdminUserResponse> {
		const response = await this.adminUsersIdPatchRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 * Delete a vehicle type
	 * Delete vehicle type (admin)
	 */
	async adminVehicleTypesIdDeleteRaw(
		requestParameters: AdminVehicleTypesIdDeleteRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<void>> {
		if (requestParameters["id"] == null) {
			throw new runtime.RequiredError(
				"id",
				'Required parameter "id" was null or undefined when calling adminVehicleTypesIdDelete().'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		if (requestParameters["xLocale"] != null) {
			headerParameters["x-locale"] = String(requestParameters["xLocale"]);
		}

		let urlPath = `/admin/vehicle-types/{id}`;
		urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters["id"])));

		const response = await this.request(
			{
				path: urlPath,
				method: "DELETE",
				headers: headerParameters,
				query: queryParameters
			},
			initOverrides
		);

		return new runtime.VoidApiResponse(response);
	}

	/**
	 * Delete a vehicle type
	 * Delete vehicle type (admin)
	 */
	async adminVehicleTypesIdDelete(
		requestParameters: AdminVehicleTypesIdDeleteRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<void> {
		await this.adminVehicleTypesIdDeleteRaw(requestParameters, initOverrides);
	}

	/**
	 * Get detailed information about a specific vehicle type
	 * Get vehicle type by ID (admin)
	 */
	async adminVehicleTypesIdGetRaw(
		requestParameters: AdminVehicleTypesIdGetRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<AdminVehicleTypeResponse>> {
		if (requestParameters["id"] == null) {
			throw new runtime.RequiredError(
				"id",
				'Required parameter "id" was null or undefined when calling adminVehicleTypesIdGet().'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		if (requestParameters["xLocale"] != null) {
			headerParameters["x-locale"] = String(requestParameters["xLocale"]);
		}

		let urlPath = `/admin/vehicle-types/{id}`;
		urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters["id"])));

		const response = await this.request(
			{
				path: urlPath,
				method: "GET",
				headers: headerParameters,
				query: queryParameters
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			AdminVehicleTypeResponseFromJSON(jsonValue)
		);
	}

	/**
	 * Get detailed information about a specific vehicle type
	 * Get vehicle type by ID (admin)
	 */
	async adminVehicleTypesIdGet(
		requestParameters: AdminVehicleTypesIdGetRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<AdminVehicleTypeResponse> {
		const response = await this.adminVehicleTypesIdGetRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 * Update an existing vehicle type
	 * Update vehicle type (admin)
	 */
	async adminVehicleTypesIdPutRaw(
		requestParameters: AdminVehicleTypesIdPutRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<AdminVehicleTypeResponse>> {
		if (requestParameters["id"] == null) {
			throw new runtime.RequiredError(
				"id",
				'Required parameter "id" was null or undefined when calling adminVehicleTypesIdPut().'
			);
		}

		if (requestParameters["vehicleType"] == null) {
			throw new runtime.RequiredError(
				"vehicleType",
				'Required parameter "vehicleType" was null or undefined when calling adminVehicleTypesIdPut().'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		headerParameters["Content-Type"] = "application/json";

		if (requestParameters["xLocale"] != null) {
			headerParameters["x-locale"] = String(requestParameters["xLocale"]);
		}

		let urlPath = `/admin/vehicle-types/{id}`;
		urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters["id"])));

		const response = await this.request(
			{
				path: urlPath,
				method: "PUT",
				headers: headerParameters,
				query: queryParameters,
				body: AdminUpdateVehicleTypeRequestToJSON(requestParameters["vehicleType"])
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			AdminVehicleTypeResponseFromJSON(jsonValue)
		);
	}

	/**
	 * Update an existing vehicle type
	 * Update vehicle type (admin)
	 */
	async adminVehicleTypesIdPut(
		requestParameters: AdminVehicleTypesIdPutRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<AdminVehicleTypeResponse> {
		const response = await this.adminVehicleTypesIdPutRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 * Create a new vehicle type with specifications
	 * Create vehicle type (admin)
	 */
	async adminVehicleTypesPostRaw(
		requestParameters: AdminVehicleTypesPostRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<AdminVehicleTypeResponse>> {
		if (requestParameters["vehicleType"] == null) {
			throw new runtime.RequiredError(
				"vehicleType",
				'Required parameter "vehicleType" was null or undefined when calling adminVehicleTypesPost().'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		headerParameters["Content-Type"] = "application/json";

		if (requestParameters["xLocale"] != null) {
			headerParameters["x-locale"] = String(requestParameters["xLocale"]);
		}

		let urlPath = `/admin/vehicle-types`;

		const response = await this.request(
			{
				path: urlPath,
				method: "POST",
				headers: headerParameters,
				query: queryParameters,
				body: AdminCreateVehicleTypeRequestToJSON(requestParameters["vehicleType"])
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			AdminVehicleTypeResponseFromJSON(jsonValue)
		);
	}

	/**
	 * Create a new vehicle type with specifications
	 * Create vehicle type (admin)
	 */
	async adminVehicleTypesPost(
		requestParameters: AdminVehicleTypesPostRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<AdminVehicleTypeResponse> {
		const response = await this.adminVehicleTypesPostRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 * Get a paginated list of vendors with optional filters
	 * List vendors (admin)
	 */
	async adminVendorsGetRaw(
		requestParameters: AdminVendorsGetRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<AdminListVendorsResponse>> {
		const queryParameters: any = {};

		if (requestParameters["status"] != null) {
			queryParameters["status"] = requestParameters["status"];
		}

		if (requestParameters["page"] != null) {
			queryParameters["page"] = requestParameters["page"];
		}

		if (requestParameters["limit"] != null) {
			queryParameters["limit"] = requestParameters["limit"];
		}

		const headerParameters: runtime.HTTPHeaders = {};

		if (requestParameters["xLocale"] != null) {
			headerParameters["x-locale"] = String(requestParameters["xLocale"]);
		}

		let urlPath = `/admin/vendors`;

		const response = await this.request(
			{
				path: urlPath,
				method: "GET",
				headers: headerParameters,
				query: queryParameters
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			AdminListVendorsResponseFromJSON(jsonValue)
		);
	}

	/**
	 * Get a paginated list of vendors with optional filters
	 * List vendors (admin)
	 */
	async adminVendorsGet(
		requestParameters: AdminVendorsGetRequest = {},
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<AdminListVendorsResponse> {
		const response = await this.adminVendorsGetRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 * Approve a pending vendor and create their Stripe Connect account
	 * Approve vendor (admin)
	 */
	async adminVendorsIdApprovePostRaw(
		requestParameters: AdminVendorsIdApprovePostRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<HttputilsSuccessResponse>> {
		if (requestParameters["id"] == null) {
			throw new runtime.RequiredError(
				"id",
				'Required parameter "id" was null or undefined when calling adminVendorsIdApprovePost().'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		if (requestParameters["xLocale"] != null) {
			headerParameters["x-locale"] = String(requestParameters["xLocale"]);
		}

		let urlPath = `/admin/vendors/{id}/approve`;
		urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters["id"])));

		const response = await this.request(
			{
				path: urlPath,
				method: "POST",
				headers: headerParameters,
				query: queryParameters
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			HttputilsSuccessResponseFromJSON(jsonValue)
		);
	}

	/**
	 * Approve a pending vendor and create their Stripe Connect account
	 * Approve vendor (admin)
	 */
	async adminVendorsIdApprovePost(
		requestParameters: AdminVendorsIdApprovePostRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<HttputilsSuccessResponse> {
		const response = await this.adminVendorsIdApprovePostRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 * Deny a pending vendor
	 * Deny vendor (admin)
	 */
	async adminVendorsIdDenyPostRaw(
		requestParameters: AdminVendorsIdDenyPostRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<HttputilsSuccessResponse>> {
		if (requestParameters["id"] == null) {
			throw new runtime.RequiredError(
				"id",
				'Required parameter "id" was null or undefined when calling adminVendorsIdDenyPost().'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		if (requestParameters["xLocale"] != null) {
			headerParameters["x-locale"] = String(requestParameters["xLocale"]);
		}

		let urlPath = `/admin/vendors/{id}/deny`;
		urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters["id"])));

		const response = await this.request(
			{
				path: urlPath,
				method: "POST",
				headers: headerParameters,
				query: queryParameters
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			HttputilsSuccessResponseFromJSON(jsonValue)
		);
	}

	/**
	 * Deny a pending vendor
	 * Deny vendor (admin)
	 */
	async adminVendorsIdDenyPost(
		requestParameters: AdminVendorsIdDenyPostRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<HttputilsSuccessResponse> {
		const response = await this.adminVendorsIdDenyPostRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 * Download/view a specific document for a vendor (admin only, GDPR compliant)
	 * Get vendor document (admin)
	 */
	async adminVendorsIdDocumentsTypeGetRaw(
		requestParameters: AdminVendorsIdDocumentsTypeGetRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<Blob>> {
		if (requestParameters["id"] == null) {
			throw new runtime.RequiredError(
				"id",
				'Required parameter "id" was null or undefined when calling adminVendorsIdDocumentsTypeGet().'
			);
		}

		if (requestParameters["type"] == null) {
			throw new runtime.RequiredError(
				"type",
				'Required parameter "type" was null or undefined when calling adminVendorsIdDocumentsTypeGet().'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		if (requestParameters["xLocale"] != null) {
			headerParameters["x-locale"] = String(requestParameters["xLocale"]);
		}

		let urlPath = `/admin/vendors/{id}/documents/{type}`;
		urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters["id"])));
		urlPath = urlPath.replace(`{${"type"}}`, encodeURIComponent(String(requestParameters["type"])));

		const response = await this.request(
			{
				path: urlPath,
				method: "GET",
				headers: headerParameters,
				query: queryParameters
			},
			initOverrides
		);

		return new runtime.BlobApiResponse(response);
	}

	/**
	 * Download/view a specific document for a vendor (admin only, GDPR compliant)
	 * Get vendor document (admin)
	 */
	async adminVendorsIdDocumentsTypeGet(
		requestParameters: AdminVendorsIdDocumentsTypeGetRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<Blob> {
		const response = await this.adminVendorsIdDocumentsTypeGetRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 * Get a specific vendor by their ID (admin only)
	 * Get vendor by ID (admin)
	 */
	async adminVendorsIdGetRaw(
		requestParameters: AdminVendorsIdGetRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<AdminAdminVendorResponse>> {
		if (requestParameters["id"] == null) {
			throw new runtime.RequiredError(
				"id",
				'Required parameter "id" was null or undefined when calling adminVendorsIdGet().'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		if (requestParameters["xLocale"] != null) {
			headerParameters["x-locale"] = String(requestParameters["xLocale"]);
		}

		let urlPath = `/admin/vendors/{id}`;
		urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters["id"])));

		const response = await this.request(
			{
				path: urlPath,
				method: "GET",
				headers: headerParameters,
				query: queryParameters
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			AdminAdminVendorResponseFromJSON(jsonValue)
		);
	}

	/**
	 * Get a specific vendor by their ID (admin only)
	 * Get vendor by ID (admin)
	 */
	async adminVendorsIdGet(
		requestParameters: AdminVendorsIdGetRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<AdminAdminVendorResponse> {
		const response = await this.adminVendorsIdGetRaw(requestParameters, initOverrides);
		return await response.value();
	}
}

/**
 * @export
 */
export const AdminUsersExportGetRoleEnum = {
	Client: "client",
	Courier: "courier",
	Vendor: "vendor",
	VendorEmployee: "vendor_employee",
	Admin: "admin"
} as const;
export type AdminUsersExportGetRoleEnum =
	(typeof AdminUsersExportGetRoleEnum)[keyof typeof AdminUsersExportGetRoleEnum];
/**
 * @export
 */
export const AdminUsersGetRoleEnum = {
	Client: "client",
	Courier: "courier",
	Vendor: "vendor",
	VendorEmployee: "vendor_employee",
	Admin: "admin"
} as const;
export type AdminUsersGetRoleEnum =
	(typeof AdminUsersGetRoleEnum)[keyof typeof AdminUsersGetRoleEnum];
