/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type {
	HttputilsErrorResponse,
	RoutesLoginRequest,
	RoutesLoginResponse,
	RoutesRefreshRequest,
	RoutesRegisterRequest,
	RoutesRegisterResponse
} from "../models/index";
import {
	HttputilsErrorResponseFromJSON,
	HttputilsErrorResponseToJSON,
	RoutesLoginRequestFromJSON,
	RoutesLoginRequestToJSON,
	RoutesLoginResponseFromJSON,
	RoutesLoginResponseToJSON,
	RoutesRefreshRequestFromJSON,
	RoutesRefreshRequestToJSON,
	RoutesRegisterRequestFromJSON,
	RoutesRegisterRequestToJSON,
	RoutesRegisterResponseFromJSON,
	RoutesRegisterResponseToJSON
} from "../models/index";

export interface AuthLoginPostRequest {
	body: RoutesLoginRequest;
	xLocale?: string;
}

export interface AuthRefreshPostRequest {
	body: RoutesRefreshRequest;
}

export interface AuthRegisterPostRequest {
	body: RoutesRegisterRequest;
	xLocale?: string;
}

/**
 *
 */
export class AuthApi extends runtime.BaseAPI {
	/**
	 * Authenticate user with email and password
	 * Login user
	 */
	async authLoginPostRaw(
		requestParameters: AuthLoginPostRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<RoutesLoginResponse>> {
		if (requestParameters["body"] == null) {
			throw new runtime.RequiredError(
				"body",
				'Required parameter "body" was null or undefined when calling authLoginPost().'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		headerParameters["Content-Type"] = "application/json";

		if (requestParameters["xLocale"] != null) {
			headerParameters["X-Locale"] = String(requestParameters["xLocale"]);
		}

		let urlPath = `/auth/login`;

		const response = await this.request(
			{
				path: urlPath,
				method: "POST",
				headers: headerParameters,
				query: queryParameters,
				body: RoutesLoginRequestToJSON(requestParameters["body"])
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			RoutesLoginResponseFromJSON(jsonValue)
		);
	}

	/**
	 * Authenticate user with email and password
	 * Login user
	 */
	async authLoginPost(
		requestParameters: AuthLoginPostRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<RoutesLoginResponse> {
		const response = await this.authLoginPostRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 * Invalidate session and clear cookies
	 * Logout user
	 */
	async authLogoutPostRaw(
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<{ [key: string]: string }>> {
		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		let urlPath = `/auth/logout`;

		const response = await this.request(
			{
				path: urlPath,
				method: "POST",
				headers: headerParameters,
				query: queryParameters
			},
			initOverrides
		);

		return new runtime.JSONApiResponse<any>(response);
	}

	/**
	 * Invalidate session and clear cookies
	 * Logout user
	 */
	async authLogoutPost(
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<{ [key: string]: string }> {
		const response = await this.authLogoutPostRaw(initOverrides);
		return await response.value();
	}

	/**
	 * Get new access token using refresh token
	 * Refresh access token
	 */
	async authRefreshPostRaw(
		requestParameters: AuthRefreshPostRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<RoutesLoginResponse>> {
		if (requestParameters["body"] == null) {
			throw new runtime.RequiredError(
				"body",
				'Required parameter "body" was null or undefined when calling authRefreshPost().'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		headerParameters["Content-Type"] = "application/json";

		let urlPath = `/auth/refresh`;

		const response = await this.request(
			{
				path: urlPath,
				method: "POST",
				headers: headerParameters,
				query: queryParameters,
				body: RoutesRefreshRequestToJSON(requestParameters["body"])
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			RoutesLoginResponseFromJSON(jsonValue)
		);
	}

	/**
	 * Get new access token using refresh token
	 * Refresh access token
	 */
	async authRefreshPost(
		requestParameters: AuthRefreshPostRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<RoutesLoginResponse> {
		const response = await this.authRefreshPostRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 * This function is used to register a new user
	 * Register a new user
	 */
	async authRegisterPostRaw(
		requestParameters: AuthRegisterPostRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<RoutesRegisterResponse>> {
		if (requestParameters["body"] == null) {
			throw new runtime.RequiredError(
				"body",
				'Required parameter "body" was null or undefined when calling authRegisterPost().'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		headerParameters["Content-Type"] = "application/json";

		if (requestParameters["xLocale"] != null) {
			headerParameters["X-Locale"] = String(requestParameters["xLocale"]);
		}

		let urlPath = `/auth/register`;

		const response = await this.request(
			{
				path: urlPath,
				method: "POST",
				headers: headerParameters,
				query: queryParameters,
				body: RoutesRegisterRequestToJSON(requestParameters["body"])
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			RoutesRegisterResponseFromJSON(jsonValue)
		);
	}

	/**
	 * This function is used to register a new user
	 * Register a new user
	 */
	async authRegisterPost(
		requestParameters: AuthRegisterPostRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<RoutesRegisterResponse> {
		const response = await this.authRegisterPostRaw(requestParameters, initOverrides);
		return await response.value();
	}
}
