/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type { HttputilsErrorResponse, RoutesClientProfileResponse } from "../models/index";
import {
	HttputilsErrorResponseFromJSON,
	HttputilsErrorResponseToJSON,
	RoutesClientProfileResponseFromJSON,
	RoutesClientProfileResponseToJSON
} from "../models/index";

/**
 *
 */
export class ClientApi extends runtime.BaseAPI {
	/**
	 * Get the profile of the authenticated client
	 * Get client profile
	 */
	async clientProfileGetRaw(
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<RoutesClientProfileResponse>> {
		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		let urlPath = `/client/profile`;

		const response = await this.request(
			{
				path: urlPath,
				method: "GET",
				headers: headerParameters,
				query: queryParameters
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			RoutesClientProfileResponseFromJSON(jsonValue)
		);
	}

	/**
	 * Get the profile of the authenticated client
	 * Get client profile
	 */
	async clientProfileGet(
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<RoutesClientProfileResponse> {
		const response = await this.clientProfileGetRaw(initOverrides);
		return await response.value();
	}
}
