/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type {
	HttputilsErrorResponse,
	RoutesCourierOnboardingStatusResponse,
	RoutesCourierRegistrationRequest,
	RoutesCourierRegistrationResponse,
	RoutesCourierStripeLinkResponse
} from "../models/index";
import {
	HttputilsErrorResponseFromJSON,
	HttputilsErrorResponseToJSON,
	RoutesCourierOnboardingStatusResponseFromJSON,
	RoutesCourierOnboardingStatusResponseToJSON,
	RoutesCourierRegistrationRequestFromJSON,
	RoutesCourierRegistrationRequestToJSON,
	RoutesCourierRegistrationResponseFromJSON,
	RoutesCourierRegistrationResponseToJSON,
	RoutesCourierStripeLinkResponseFromJSON,
	RoutesCourierStripeLinkResponseToJSON
} from "../models/index";

export interface AuthRegisterCourierPostRequest {
	registration: RoutesCourierRegistrationRequest;
}

export interface CourierOnboardingStatusGetRequest {
	xLocale?: string;
}

export interface CourierStripeLinkPostRequest {
	xLocale?: string;
}

/**
 *
 */
export class CourierApi extends runtime.BaseAPI {
	/**
	 * Register a new courier with the provided details
	 * Register a new courier
	 */
	async authRegisterCourierPostRaw(
		requestParameters: AuthRegisterCourierPostRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<RoutesCourierRegistrationResponse>> {
		if (requestParameters["registration"] == null) {
			throw new runtime.RequiredError(
				"registration",
				'Required parameter "registration" was null or undefined when calling authRegisterCourierPost().'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		headerParameters["Content-Type"] = "application/json";

		let urlPath = `/auth/register-courier`;

		const response = await this.request(
			{
				path: urlPath,
				method: "POST",
				headers: headerParameters,
				query: queryParameters,
				body: RoutesCourierRegistrationRequestToJSON(requestParameters["registration"])
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			RoutesCourierRegistrationResponseFromJSON(jsonValue)
		);
	}

	/**
	 * Register a new courier with the provided details
	 * Register a new courier
	 */
	async authRegisterCourierPost(
		requestParameters: AuthRegisterCourierPostRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<RoutesCourierRegistrationResponse> {
		const response = await this.authRegisterCourierPostRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 * Get the current onboarding status for the courier
	 * Get onboarding status (courier)
	 */
	async courierOnboardingStatusGetRaw(
		requestParameters: CourierOnboardingStatusGetRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<RoutesCourierOnboardingStatusResponse>> {
		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		if (requestParameters["xLocale"] != null) {
			headerParameters["x-locale"] = String(requestParameters["xLocale"]);
		}

		let urlPath = `/courier/onboarding-status`;

		const response = await this.request(
			{
				path: urlPath,
				method: "GET",
				headers: headerParameters,
				query: queryParameters
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			RoutesCourierOnboardingStatusResponseFromJSON(jsonValue)
		);
	}

	/**
	 * Get the current onboarding status for the courier
	 * Get onboarding status (courier)
	 */
	async courierOnboardingStatusGet(
		requestParameters: CourierOnboardingStatusGetRequest = {},
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<RoutesCourierOnboardingStatusResponse> {
		const response = await this.courierOnboardingStatusGetRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 * Generate a fresh Stripe onboarding link for an approved courier
	 * Generate Stripe onboarding link (courier)
	 */
	async courierStripeLinkPostRaw(
		requestParameters: CourierStripeLinkPostRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<RoutesCourierStripeLinkResponse>> {
		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		if (requestParameters["xLocale"] != null) {
			headerParameters["x-locale"] = String(requestParameters["xLocale"]);
		}

		let urlPath = `/courier/stripe-link`;

		const response = await this.request(
			{
				path: urlPath,
				method: "POST",
				headers: headerParameters,
				query: queryParameters
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			RoutesCourierStripeLinkResponseFromJSON(jsonValue)
		);
	}

	/**
	 * Generate a fresh Stripe onboarding link for an approved courier
	 * Generate Stripe onboarding link (courier)
	 */
	async courierStripeLinkPost(
		requestParameters: CourierStripeLinkPostRequest = {},
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<RoutesCourierStripeLinkResponse> {
		const response = await this.courierStripeLinkPostRaw(requestParameters, initOverrides);
		return await response.value();
	}
}
