/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type {
	HttputilsErrorResponse,
	RoutesCategoryListResponse,
	RoutesCategoryResponse,
	RoutesPublicVehicleTypeResponse,
	RoutesPublicVendorResponse,
	RoutesVendorProductListResponse
} from "../models/index";
import {
	HttputilsErrorResponseFromJSON,
	HttputilsErrorResponseToJSON,
	RoutesCategoryListResponseFromJSON,
	RoutesCategoryListResponseToJSON,
	RoutesCategoryResponseFromJSON,
	RoutesCategoryResponseToJSON,
	RoutesPublicVehicleTypeResponseFromJSON,
	RoutesPublicVehicleTypeResponseToJSON,
	RoutesPublicVendorResponseFromJSON,
	RoutesPublicVendorResponseToJSON,
	RoutesVendorProductListResponseFromJSON,
	RoutesVendorProductListResponseToJSON
} from "../models/index";

export interface CategoriesGetRequest {
	xLocale?: string;
}

export interface CategoriesIdGetRequest {
	id: string;
	xLocale?: string;
}

export interface VehicleTypesGetRequest {
	xLocale?: string;
}

export interface VendorsIdGetRequest {
	id: string;
	xLocale?: string;
}

export interface VendorsIdProductsGetRequest {
	id: string;
	xLocale?: string;
	page?: number;
	limit?: number;
	categoryId?: string;
	search?: string;
}

/**
 *
 */
export class MarketplaceApi extends runtime.BaseAPI {
	/**
	 * Get all available product categories
	 * Get all categories
	 */
	async categoriesGetRaw(
		requestParameters: CategoriesGetRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<RoutesCategoryListResponse>> {
		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		if (requestParameters["xLocale"] != null) {
			headerParameters["x-locale"] = String(requestParameters["xLocale"]);
		}

		let urlPath = `/categories`;

		const response = await this.request(
			{
				path: urlPath,
				method: "GET",
				headers: headerParameters,
				query: queryParameters
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			RoutesCategoryListResponseFromJSON(jsonValue)
		);
	}

	/**
	 * Get all available product categories
	 * Get all categories
	 */
	async categoriesGet(
		requestParameters: CategoriesGetRequest = {},
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<RoutesCategoryListResponse> {
		const response = await this.categoriesGetRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 * Get detailed information about a specific category
	 * Get category by ID
	 */
	async categoriesIdGetRaw(
		requestParameters: CategoriesIdGetRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<RoutesCategoryResponse>> {
		if (requestParameters["id"] == null) {
			throw new runtime.RequiredError(
				"id",
				'Required parameter "id" was null or undefined when calling categoriesIdGet().'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		if (requestParameters["xLocale"] != null) {
			headerParameters["x-locale"] = String(requestParameters["xLocale"]);
		}

		let urlPath = `/categories/{id}`;
		urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters["id"])));

		const response = await this.request(
			{
				path: urlPath,
				method: "GET",
				headers: headerParameters,
				query: queryParameters
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			RoutesCategoryResponseFromJSON(jsonValue)
		);
	}

	/**
	 * Get detailed information about a specific category
	 * Get category by ID
	 */
	async categoriesIdGet(
		requestParameters: CategoriesIdGetRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<RoutesCategoryResponse> {
		const response = await this.categoriesIdGetRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 * Get all available vehicle types with their specifications
	 * List vehicle types
	 */
	async vehicleTypesGetRaw(
		requestParameters: VehicleTypesGetRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<Array<RoutesPublicVehicleTypeResponse>>> {
		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		if (requestParameters["xLocale"] != null) {
			headerParameters["x-locale"] = String(requestParameters["xLocale"]);
		}

		let urlPath = `/vehicle-types`;

		const response = await this.request(
			{
				path: urlPath,
				method: "GET",
				headers: headerParameters,
				query: queryParameters
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			jsonValue.map(RoutesPublicVehicleTypeResponseFromJSON)
		);
	}

	/**
	 * Get all available vehicle types with their specifications
	 * List vehicle types
	 */
	async vehicleTypesGet(
		requestParameters: VehicleTypesGetRequest = {},
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<Array<RoutesPublicVehicleTypeResponse>> {
		const response = await this.vehicleTypesGetRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 * Get public profile information for a specific vendor
	 * Get public vendor profile
	 */
	async vendorsIdGetRaw(
		requestParameters: VendorsIdGetRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<RoutesPublicVendorResponse>> {
		if (requestParameters["id"] == null) {
			throw new runtime.RequiredError(
				"id",
				'Required parameter "id" was null or undefined when calling vendorsIdGet().'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		if (requestParameters["xLocale"] != null) {
			headerParameters["x-locale"] = String(requestParameters["xLocale"]);
		}

		let urlPath = `/vendors/{id}`;
		urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters["id"])));

		const response = await this.request(
			{
				path: urlPath,
				method: "GET",
				headers: headerParameters,
				query: queryParameters
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			RoutesPublicVendorResponseFromJSON(jsonValue)
		);
	}

	/**
	 * Get public profile information for a specific vendor
	 * Get public vendor profile
	 */
	async vendorsIdGet(
		requestParameters: VendorsIdGetRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<RoutesPublicVendorResponse> {
		const response = await this.vendorsIdGetRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 * Get all public products for a specific vendor
	 * Get vendor products
	 */
	async vendorsIdProductsGetRaw(
		requestParameters: VendorsIdProductsGetRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<RoutesVendorProductListResponse>> {
		if (requestParameters["id"] == null) {
			throw new runtime.RequiredError(
				"id",
				'Required parameter "id" was null or undefined when calling vendorsIdProductsGet().'
			);
		}

		const queryParameters: any = {};

		if (requestParameters["page"] != null) {
			queryParameters["page"] = requestParameters["page"];
		}

		if (requestParameters["limit"] != null) {
			queryParameters["limit"] = requestParameters["limit"];
		}

		if (requestParameters["categoryId"] != null) {
			queryParameters["category_id"] = requestParameters["categoryId"];
		}

		if (requestParameters["search"] != null) {
			queryParameters["search"] = requestParameters["search"];
		}

		const headerParameters: runtime.HTTPHeaders = {};

		if (requestParameters["xLocale"] != null) {
			headerParameters["x-locale"] = String(requestParameters["xLocale"]);
		}

		let urlPath = `/vendors/{id}/products`;
		urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters["id"])));

		const response = await this.request(
			{
				path: urlPath,
				method: "GET",
				headers: headerParameters,
				query: queryParameters
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			RoutesVendorProductListResponseFromJSON(jsonValue)
		);
	}

	/**
	 * Get all public products for a specific vendor
	 * Get vendor products
	 */
	async vendorsIdProductsGet(
		requestParameters: VendorsIdProductsGetRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<RoutesVendorProductListResponse> {
		const response = await this.vendorsIdProductsGetRaw(requestParameters, initOverrides);
		return await response.value();
	}
}
