/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type { HttputilsErrorResponse, RoutesMeResponse } from "../models/index";
import {
	HttputilsErrorResponseFromJSON,
	HttputilsErrorResponseToJSON,
	RoutesMeResponseFromJSON,
	RoutesMeResponseToJSON
} from "../models/index";

/**
 *
 */
export class UserApi extends runtime.BaseAPI {
	/**
	 * Get information about the currently authenticated user
	 * Get current user information
	 */
	async meGetRaw(
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<RoutesMeResponse>> {
		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		let urlPath = `/me`;

		const response = await this.request(
			{
				path: urlPath,
				method: "GET",
				headers: headerParameters,
				query: queryParameters
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			RoutesMeResponseFromJSON(jsonValue)
		);
	}

	/**
	 * Get information about the currently authenticated user
	 * Get current user information
	 */
	async meGet(
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<RoutesMeResponse> {
		const response = await this.meGetRaw(initOverrides);
		return await response.value();
	}
}
