/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type {
	HttputilsErrorResponse,
	HttputilsSuccessResponse,
	RoutesCreateProductRequest,
	RoutesOnboardingStatusResponse,
	RoutesProductImageRequest,
	RoutesProductImageResponse,
	RoutesProductListResponse,
	RoutesProductResponse,
	RoutesStripeLinkResponse,
	RoutesUpdateProductRequest,
	RoutesVendorRegistrationRequest,
	RoutesVendorRegistrationResponse
} from "../models/index";
import {
	HttputilsErrorResponseFromJSON,
	HttputilsErrorResponseToJSON,
	HttputilsSuccessResponseFromJSON,
	HttputilsSuccessResponseToJSON,
	RoutesCreateProductRequestFromJSON,
	RoutesCreateProductRequestToJSON,
	RoutesOnboardingStatusResponseFromJSON,
	RoutesOnboardingStatusResponseToJSON,
	RoutesProductImageRequestFromJSON,
	RoutesProductImageRequestToJSON,
	RoutesProductImageResponseFromJSON,
	RoutesProductImageResponseToJSON,
	RoutesProductListResponseFromJSON,
	RoutesProductListResponseToJSON,
	RoutesProductResponseFromJSON,
	RoutesProductResponseToJSON,
	RoutesStripeLinkResponseFromJSON,
	RoutesStripeLinkResponseToJSON,
	RoutesUpdateProductRequestFromJSON,
	RoutesUpdateProductRequestToJSON,
	RoutesVendorRegistrationRequestFromJSON,
	RoutesVendorRegistrationRequestToJSON,
	RoutesVendorRegistrationResponseFromJSON,
	RoutesVendorRegistrationResponseToJSON
} from "../models/index";

export interface AuthRegisterVendorPostRequest {
	registration: RoutesVendorRegistrationRequest;
	xLocale?: string;
}

export interface VendorOnboardingStatusGetRequest {
	xLocale?: string;
}

export interface VendorProductsGetRequest {
	xLocale?: string;
	page?: number;
	limit?: number;
	categoryId?: string;
	status?: string;
	search?: string;
}

export interface VendorProductsIdDeleteRequest {
	id: string;
	xLocale?: string;
}

export interface VendorProductsIdGetRequest {
	id: string;
	xLocale?: string;
}

export interface VendorProductsIdImagesIndexDeleteRequest {
	id: string;
	index: string;
	xLocale?: string;
}

export interface VendorProductsIdImagesPostRequest {
	id: string;
	image: RoutesProductImageRequest;
	xLocale?: string;
}

export interface VendorProductsIdPutRequest {
	id: string;
	product: RoutesUpdateProductRequest;
	xLocale?: string;
}

export interface VendorProductsPostRequest {
	product: RoutesCreateProductRequest;
	xLocale?: string;
}

export interface VendorStripeLinkPostRequest {
	xLocale?: string;
}

/**
 *
 */
export class VendorApi extends runtime.BaseAPI {
	/**
	 * Register a new vendor with the provided details
	 * Register a new vendor
	 */
	async authRegisterVendorPostRaw(
		requestParameters: AuthRegisterVendorPostRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<RoutesVendorRegistrationResponse>> {
		if (requestParameters["registration"] == null) {
			throw new runtime.RequiredError(
				"registration",
				'Required parameter "registration" was null or undefined when calling authRegisterVendorPost().'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		headerParameters["Content-Type"] = "application/json";

		if (requestParameters["xLocale"] != null) {
			headerParameters["x-locale"] = String(requestParameters["xLocale"]);
		}

		let urlPath = `/auth/register-vendor`;

		const response = await this.request(
			{
				path: urlPath,
				method: "POST",
				headers: headerParameters,
				query: queryParameters,
				body: RoutesVendorRegistrationRequestToJSON(requestParameters["registration"])
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			RoutesVendorRegistrationResponseFromJSON(jsonValue)
		);
	}

	/**
	 * Register a new vendor with the provided details
	 * Register a new vendor
	 */
	async authRegisterVendorPost(
		requestParameters: AuthRegisterVendorPostRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<RoutesVendorRegistrationResponse> {
		const response = await this.authRegisterVendorPostRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 * Get the current onboarding status for the vendor
	 * Get onboarding status (vendor)
	 */
	async vendorOnboardingStatusGetRaw(
		requestParameters: VendorOnboardingStatusGetRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<RoutesOnboardingStatusResponse>> {
		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		if (requestParameters["xLocale"] != null) {
			headerParameters["x-locale"] = String(requestParameters["xLocale"]);
		}

		let urlPath = `/vendor/onboarding-status`;

		const response = await this.request(
			{
				path: urlPath,
				method: "GET",
				headers: headerParameters,
				query: queryParameters
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			RoutesOnboardingStatusResponseFromJSON(jsonValue)
		);
	}

	/**
	 * Get the current onboarding status for the vendor
	 * Get onboarding status (vendor)
	 */
	async vendorOnboardingStatusGet(
		requestParameters: VendorOnboardingStatusGetRequest = {},
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<RoutesOnboardingStatusResponse> {
		const response = await this.vendorOnboardingStatusGetRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 * List vendor products with pagination and filters (vendor only)
	 * List products
	 */
	async vendorProductsGetRaw(
		requestParameters: VendorProductsGetRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<RoutesProductListResponse>> {
		const queryParameters: any = {};

		if (requestParameters["page"] != null) {
			queryParameters["page"] = requestParameters["page"];
		}

		if (requestParameters["limit"] != null) {
			queryParameters["limit"] = requestParameters["limit"];
		}

		if (requestParameters["categoryId"] != null) {
			queryParameters["category_id"] = requestParameters["categoryId"];
		}

		if (requestParameters["status"] != null) {
			queryParameters["status"] = requestParameters["status"];
		}

		if (requestParameters["search"] != null) {
			queryParameters["search"] = requestParameters["search"];
		}

		const headerParameters: runtime.HTTPHeaders = {};

		if (requestParameters["xLocale"] != null) {
			headerParameters["x-locale"] = String(requestParameters["xLocale"]);
		}

		let urlPath = `/vendor/products`;

		const response = await this.request(
			{
				path: urlPath,
				method: "GET",
				headers: headerParameters,
				query: queryParameters
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			RoutesProductListResponseFromJSON(jsonValue)
		);
	}

	/**
	 * List vendor products with pagination and filters (vendor only)
	 * List products
	 */
	async vendorProductsGet(
		requestParameters: VendorProductsGetRequest = {},
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<RoutesProductListResponse> {
		const response = await this.vendorProductsGetRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 * Delete a product (vendor only)
	 * Delete product
	 */
	async vendorProductsIdDeleteRaw(
		requestParameters: VendorProductsIdDeleteRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<HttputilsSuccessResponse>> {
		if (requestParameters["id"] == null) {
			throw new runtime.RequiredError(
				"id",
				'Required parameter "id" was null or undefined when calling vendorProductsIdDelete().'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		if (requestParameters["xLocale"] != null) {
			headerParameters["x-locale"] = String(requestParameters["xLocale"]);
		}

		let urlPath = `/vendor/products/{id}`;
		urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters["id"])));

		const response = await this.request(
			{
				path: urlPath,
				method: "DELETE",
				headers: headerParameters,
				query: queryParameters
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			HttputilsSuccessResponseFromJSON(jsonValue)
		);
	}

	/**
	 * Delete a product (vendor only)
	 * Delete product
	 */
	async vendorProductsIdDelete(
		requestParameters: VendorProductsIdDeleteRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<HttputilsSuccessResponse> {
		const response = await this.vendorProductsIdDeleteRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 * Get a specific product by ID (vendor only)
	 * Get product
	 */
	async vendorProductsIdGetRaw(
		requestParameters: VendorProductsIdGetRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<RoutesProductResponse>> {
		if (requestParameters["id"] == null) {
			throw new runtime.RequiredError(
				"id",
				'Required parameter "id" was null or undefined when calling vendorProductsIdGet().'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		if (requestParameters["xLocale"] != null) {
			headerParameters["x-locale"] = String(requestParameters["xLocale"]);
		}

		let urlPath = `/vendor/products/{id}`;
		urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters["id"])));

		const response = await this.request(
			{
				path: urlPath,
				method: "GET",
				headers: headerParameters,
				query: queryParameters
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			RoutesProductResponseFromJSON(jsonValue)
		);
	}

	/**
	 * Get a specific product by ID (vendor only)
	 * Get product
	 */
	async vendorProductsIdGet(
		requestParameters: VendorProductsIdGetRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<RoutesProductResponse> {
		const response = await this.vendorProductsIdGetRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 * Delete an image from a product by index (vendor only)
	 * Delete product image
	 */
	async vendorProductsIdImagesIndexDeleteRaw(
		requestParameters: VendorProductsIdImagesIndexDeleteRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<HttputilsSuccessResponse>> {
		if (requestParameters["id"] == null) {
			throw new runtime.RequiredError(
				"id",
				'Required parameter "id" was null or undefined when calling vendorProductsIdImagesIndexDelete().'
			);
		}

		if (requestParameters["index"] == null) {
			throw new runtime.RequiredError(
				"index",
				'Required parameter "index" was null or undefined when calling vendorProductsIdImagesIndexDelete().'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		if (requestParameters["xLocale"] != null) {
			headerParameters["x-locale"] = String(requestParameters["xLocale"]);
		}

		let urlPath = `/vendor/products/{id}/images/{index}`;
		urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters["id"])));
		urlPath = urlPath.replace(
			`{${"index"}}`,
			encodeURIComponent(String(requestParameters["index"]))
		);

		const response = await this.request(
			{
				path: urlPath,
				method: "DELETE",
				headers: headerParameters,
				query: queryParameters
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			HttputilsSuccessResponseFromJSON(jsonValue)
		);
	}

	/**
	 * Delete an image from a product by index (vendor only)
	 * Delete product image
	 */
	async vendorProductsIdImagesIndexDelete(
		requestParameters: VendorProductsIdImagesIndexDeleteRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<HttputilsSuccessResponse> {
		const response = await this.vendorProductsIdImagesIndexDeleteRaw(
			requestParameters,
			initOverrides
		);
		return await response.value();
	}

	/**
	 * Add an image to a product (vendor only)
	 * Add product image
	 */
	async vendorProductsIdImagesPostRaw(
		requestParameters: VendorProductsIdImagesPostRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<RoutesProductImageResponse>> {
		if (requestParameters["id"] == null) {
			throw new runtime.RequiredError(
				"id",
				'Required parameter "id" was null or undefined when calling vendorProductsIdImagesPost().'
			);
		}

		if (requestParameters["image"] == null) {
			throw new runtime.RequiredError(
				"image",
				'Required parameter "image" was null or undefined when calling vendorProductsIdImagesPost().'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		headerParameters["Content-Type"] = "application/json";

		if (requestParameters["xLocale"] != null) {
			headerParameters["x-locale"] = String(requestParameters["xLocale"]);
		}

		let urlPath = `/vendor/products/{id}/images`;
		urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters["id"])));

		const response = await this.request(
			{
				path: urlPath,
				method: "POST",
				headers: headerParameters,
				query: queryParameters,
				body: RoutesProductImageRequestToJSON(requestParameters["image"])
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			RoutesProductImageResponseFromJSON(jsonValue)
		);
	}

	/**
	 * Add an image to a product (vendor only)
	 * Add product image
	 */
	async vendorProductsIdImagesPost(
		requestParameters: VendorProductsIdImagesPostRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<RoutesProductImageResponse> {
		const response = await this.vendorProductsIdImagesPostRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 * Update a product (vendor only)
	 * Update product
	 */
	async vendorProductsIdPutRaw(
		requestParameters: VendorProductsIdPutRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<RoutesProductResponse>> {
		if (requestParameters["id"] == null) {
			throw new runtime.RequiredError(
				"id",
				'Required parameter "id" was null or undefined when calling vendorProductsIdPut().'
			);
		}

		if (requestParameters["product"] == null) {
			throw new runtime.RequiredError(
				"product",
				'Required parameter "product" was null or undefined when calling vendorProductsIdPut().'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		headerParameters["Content-Type"] = "application/json";

		if (requestParameters["xLocale"] != null) {
			headerParameters["x-locale"] = String(requestParameters["xLocale"]);
		}

		let urlPath = `/vendor/products/{id}`;
		urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters["id"])));

		const response = await this.request(
			{
				path: urlPath,
				method: "PUT",
				headers: headerParameters,
				query: queryParameters,
				body: RoutesUpdateProductRequestToJSON(requestParameters["product"])
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			RoutesProductResponseFromJSON(jsonValue)
		);
	}

	/**
	 * Update a product (vendor only)
	 * Update product
	 */
	async vendorProductsIdPut(
		requestParameters: VendorProductsIdPutRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<RoutesProductResponse> {
		const response = await this.vendorProductsIdPutRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 * Create a new product (vendor only)
	 * Create product
	 */
	async vendorProductsPostRaw(
		requestParameters: VendorProductsPostRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<RoutesProductResponse>> {
		if (requestParameters["product"] == null) {
			throw new runtime.RequiredError(
				"product",
				'Required parameter "product" was null or undefined when calling vendorProductsPost().'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		headerParameters["Content-Type"] = "application/json";

		if (requestParameters["xLocale"] != null) {
			headerParameters["x-locale"] = String(requestParameters["xLocale"]);
		}

		let urlPath = `/vendor/products`;

		const response = await this.request(
			{
				path: urlPath,
				method: "POST",
				headers: headerParameters,
				query: queryParameters,
				body: RoutesCreateProductRequestToJSON(requestParameters["product"])
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			RoutesProductResponseFromJSON(jsonValue)
		);
	}

	/**
	 * Create a new product (vendor only)
	 * Create product
	 */
	async vendorProductsPost(
		requestParameters: VendorProductsPostRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<RoutesProductResponse> {
		const response = await this.vendorProductsPostRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 * Generate a fresh Stripe onboarding link for an approved vendor
	 * Generate Stripe onboarding link (vendor)
	 */
	async vendorStripeLinkPostRaw(
		requestParameters: VendorStripeLinkPostRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<RoutesStripeLinkResponse>> {
		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		if (requestParameters["xLocale"] != null) {
			headerParameters["x-locale"] = String(requestParameters["xLocale"]);
		}

		let urlPath = `/vendor/stripe-link`;

		const response = await this.request(
			{
				path: urlPath,
				method: "POST",
				headers: headerParameters,
				query: queryParameters
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			RoutesStripeLinkResponseFromJSON(jsonValue)
		);
	}

	/**
	 * Generate a fresh Stripe onboarding link for an approved vendor
	 * Generate Stripe onboarding link (vendor)
	 */
	async vendorStripeLinkPost(
		requestParameters: VendorStripeLinkPostRequest = {},
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<RoutesStripeLinkResponse> {
		const response = await this.vendorStripeLinkPostRaw(requestParameters, initOverrides);
		return await response.value();
	}
}
