/* tslint:disable */
/* eslint-disable */
/**
 * Briker API
 * This is the API documentation for the Briker backend.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type {
	HttputilsErrorResponse,
	RoutesSendEmailVerificationResponse,
	RoutesSendPasswordResetRequest,
	RoutesSendPasswordResetResponse,
	RoutesSendPhoneVerificationResponse,
	RoutesVerifyEmailResponse,
	RoutesVerifyPasswordResetRequest,
	RoutesVerifyPasswordResetResponse,
	RoutesVerifyPhoneRequest,
	RoutesVerifyPhoneResponse
} from "../models/index";
import {
	HttputilsErrorResponseFromJSON,
	HttputilsErrorResponseToJSON,
	RoutesSendEmailVerificationResponseFromJSON,
	RoutesSendEmailVerificationResponseToJSON,
	RoutesSendPasswordResetRequestFromJSON,
	RoutesSendPasswordResetRequestToJSON,
	RoutesSendPasswordResetResponseFromJSON,
	RoutesSendPasswordResetResponseToJSON,
	RoutesSendPhoneVerificationResponseFromJSON,
	RoutesSendPhoneVerificationResponseToJSON,
	RoutesVerifyEmailResponseFromJSON,
	RoutesVerifyEmailResponseToJSON,
	RoutesVerifyPasswordResetRequestFromJSON,
	RoutesVerifyPasswordResetRequestToJSON,
	RoutesVerifyPasswordResetResponseFromJSON,
	RoutesVerifyPasswordResetResponseToJSON,
	RoutesVerifyPhoneRequestFromJSON,
	RoutesVerifyPhoneRequestToJSON,
	RoutesVerifyPhoneResponseFromJSON,
	RoutesVerifyPhoneResponseToJSON
} from "../models/index";

export interface VerificationSendEmailPostRequest {
	xLocale?: string;
}

export interface VerificationSendPasswordResetPostRequest {
	body: RoutesSendPasswordResetRequest;
	xLocale?: string;
}

export interface VerificationSendPhonePostRequest {
	xLocale?: string;
}

export interface VerificationVerifyEmailTokenGetRequest {
	token: string;
	xLocale?: string;
}

export interface VerificationVerifyPasswordResetPostRequest {
	body: RoutesVerifyPasswordResetRequest;
	xLocale?: string;
}

export interface VerificationVerifyPhonePostRequest {
	body: RoutesVerifyPhoneRequest;
	xLocale?: string;
}

/**
 *
 */
export class VerificationApi extends runtime.BaseAPI {
	/**
	 * Send verification code to user\'s email address
	 * Send email verification code
	 */
	async verificationSendEmailPostRaw(
		requestParameters: VerificationSendEmailPostRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<RoutesSendEmailVerificationResponse>> {
		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		if (requestParameters["xLocale"] != null) {
			headerParameters["X-Locale"] = String(requestParameters["xLocale"]);
		}

		let urlPath = `/verification/send-email`;

		const response = await this.request(
			{
				path: urlPath,
				method: "POST",
				headers: headerParameters,
				query: queryParameters
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			RoutesSendEmailVerificationResponseFromJSON(jsonValue)
		);
	}

	/**
	 * Send verification code to user\'s email address
	 * Send email verification code
	 */
	async verificationSendEmailPost(
		requestParameters: VerificationSendEmailPostRequest = {},
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<RoutesSendEmailVerificationResponse> {
		const response = await this.verificationSendEmailPostRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 * Send password reset link to user\'s email
	 * Send password reset email
	 */
	async verificationSendPasswordResetPostRaw(
		requestParameters: VerificationSendPasswordResetPostRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<RoutesSendPasswordResetResponse>> {
		if (requestParameters["body"] == null) {
			throw new runtime.RequiredError(
				"body",
				'Required parameter "body" was null or undefined when calling verificationSendPasswordResetPost().'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		headerParameters["Content-Type"] = "application/json";

		if (requestParameters["xLocale"] != null) {
			headerParameters["X-Locale"] = String(requestParameters["xLocale"]);
		}

		let urlPath = `/verification/send-password-reset`;

		const response = await this.request(
			{
				path: urlPath,
				method: "POST",
				headers: headerParameters,
				query: queryParameters,
				body: RoutesSendPasswordResetRequestToJSON(requestParameters["body"])
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			RoutesSendPasswordResetResponseFromJSON(jsonValue)
		);
	}

	/**
	 * Send password reset link to user\'s email
	 * Send password reset email
	 */
	async verificationSendPasswordResetPost(
		requestParameters: VerificationSendPasswordResetPostRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<RoutesSendPasswordResetResponse> {
		const response = await this.verificationSendPasswordResetPostRaw(
			requestParameters,
			initOverrides
		);
		return await response.value();
	}

	/**
	 * Send SMS verification code to phone number using Twilio
	 * Send phone verification code
	 */
	async verificationSendPhonePostRaw(
		requestParameters: VerificationSendPhonePostRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<RoutesSendPhoneVerificationResponse>> {
		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		if (requestParameters["xLocale"] != null) {
			headerParameters["X-Locale"] = String(requestParameters["xLocale"]);
		}

		let urlPath = `/verification/send-phone`;

		const response = await this.request(
			{
				path: urlPath,
				method: "POST",
				headers: headerParameters,
				query: queryParameters
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			RoutesSendPhoneVerificationResponseFromJSON(jsonValue)
		);
	}

	/**
	 * Send SMS verification code to phone number using Twilio
	 * Send phone verification code
	 */
	async verificationSendPhonePost(
		requestParameters: VerificationSendPhonePostRequest = {},
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<RoutesSendPhoneVerificationResponse> {
		const response = await this.verificationSendPhonePostRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 * Verify email verification token
	 * Verify email token
	 */
	async verificationVerifyEmailTokenGetRaw(
		requestParameters: VerificationVerifyEmailTokenGetRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<RoutesVerifyEmailResponse>> {
		if (requestParameters["token"] == null) {
			throw new runtime.RequiredError(
				"token",
				'Required parameter "token" was null or undefined when calling verificationVerifyEmailTokenGet().'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		if (requestParameters["xLocale"] != null) {
			headerParameters["X-Locale"] = String(requestParameters["xLocale"]);
		}

		let urlPath = `/verification/verify-email/{token}`;
		urlPath = urlPath.replace(
			`{${"token"}}`,
			encodeURIComponent(String(requestParameters["token"]))
		);

		const response = await this.request(
			{
				path: urlPath,
				method: "GET",
				headers: headerParameters,
				query: queryParameters
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			RoutesVerifyEmailResponseFromJSON(jsonValue)
		);
	}

	/**
	 * Verify email verification token
	 * Verify email token
	 */
	async verificationVerifyEmailTokenGet(
		requestParameters: VerificationVerifyEmailTokenGetRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<RoutesVerifyEmailResponse> {
		const response = await this.verificationVerifyEmailTokenGetRaw(
			requestParameters,
			initOverrides
		);
		return await response.value();
	}

	/**
	 * Verify reset token and update user password
	 * Verify password reset and update password
	 */
	async verificationVerifyPasswordResetPostRaw(
		requestParameters: VerificationVerifyPasswordResetPostRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<RoutesVerifyPasswordResetResponse>> {
		if (requestParameters["body"] == null) {
			throw new runtime.RequiredError(
				"body",
				'Required parameter "body" was null or undefined when calling verificationVerifyPasswordResetPost().'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		headerParameters["Content-Type"] = "application/json";

		if (requestParameters["xLocale"] != null) {
			headerParameters["X-Locale"] = String(requestParameters["xLocale"]);
		}

		let urlPath = `/verification/verify-password-reset`;

		const response = await this.request(
			{
				path: urlPath,
				method: "POST",
				headers: headerParameters,
				query: queryParameters,
				body: RoutesVerifyPasswordResetRequestToJSON(requestParameters["body"])
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			RoutesVerifyPasswordResetResponseFromJSON(jsonValue)
		);
	}

	/**
	 * Verify reset token and update user password
	 * Verify password reset and update password
	 */
	async verificationVerifyPasswordResetPost(
		requestParameters: VerificationVerifyPasswordResetPostRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<RoutesVerifyPasswordResetResponse> {
		const response = await this.verificationVerifyPasswordResetPostRaw(
			requestParameters,
			initOverrides
		);
		return await response.value();
	}

	/**
	 * Verify SMS code sent to phone number
	 * Verify phone code
	 */
	async verificationVerifyPhonePostRaw(
		requestParameters: VerificationVerifyPhonePostRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<RoutesVerifyPhoneResponse>> {
		if (requestParameters["body"] == null) {
			throw new runtime.RequiredError(
				"body",
				'Required parameter "body" was null or undefined when calling verificationVerifyPhonePost().'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		headerParameters["Content-Type"] = "application/json";

		if (requestParameters["xLocale"] != null) {
			headerParameters["X-Locale"] = String(requestParameters["xLocale"]);
		}

		let urlPath = `/verification/verify-phone`;

		const response = await this.request(
			{
				path: urlPath,
				method: "POST",
				headers: headerParameters,
				query: queryParameters,
				body: RoutesVerifyPhoneRequestToJSON(requestParameters["body"])
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			RoutesVerifyPhoneResponseFromJSON(jsonValue)
		);
	}

	/**
	 * Verify SMS code sent to phone number
	 * Verify phone code
	 */
	async verificationVerifyPhonePost(
		requestParameters: VerificationVerifyPhonePostRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<RoutesVerifyPhoneResponse> {
		const response = await this.verificationVerifyPhonePostRaw(requestParameters, initOverrides);
		return await response.value();
	}
}
